import {useEffect,useState} from 'react';
export type AcademicContext={department_code:string;academic_year_id:string;batch_id:string;semester_id:string};
export const emptyAcademicContext:AcademicContext={department_code:'',academic_year_id:'',batch_id:'',semester_id:''};
type Option=Record<string,unknown>;
type Call=<T,>(path:string,method?:string,body?:unknown)=>Promise<T>;
export default function ErpAcademicFilters({call,value,onChange,onSetup}:{call:Call;value:AcademicContext;onChange:(value:AcademicContext)=>void;onSetup?:()=>void}){
 const [catalog,setCatalog]=useState<Record<string,Option[]>>({});const [loading,setLoading]=useState(true);const [failed,setFailed]=useState<string[]>([]);const [revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);const names=['departments','years','batches','sections','semesters'];void Promise.allSettled(names.map(async n=>(await call<{items:Option[]}>(`/api/college/erp/catalog/${n}`)).items)).then(results=>{if(!live)return;const items:Record<string,Option[]>={};const errors:string[]=[];results.forEach((r,i)=>{if(r.status==='fulfilled')items[names[i]]=r.value;else errors.push(names[i]);});setCatalog(items);setFailed(errors);setLoading(false);});return()=>{live=false};},[call,revision]);
 const department=catalog.departments?.find(d=>d.code===value.department_code);
 const batches=(catalog.batches||[]).filter(b=>!value.department_code||(catalog.sections||[]).some(s=>s.batch_id===b.id&&s.department_code===value.department_code)||(b.program_code&&b.program_code===department?.program));
 const semesters=(catalog.semesters||[]).filter(s=>s.academic_year_id===value.academic_year_id);
 return <section className="erp-academic-filters" aria-label="Academic filters"><div className="erp-filter-heading"><strong>Academic filters</strong><button className="erp-quiet" disabled={loading||!Object.values(value).some(Boolean)} onClick={()=>onChange(emptyAcademicContext)}>Clear filters</button></div><div className="erp-filter-grid">
 <label>Branch / Department<select aria-label="Filter department" disabled={loading} value={value.department_code} onChange={e=>onChange({...value,department_code:e.target.value,batch_id:''})}><option value="">All departments</option>{(catalog.departments||[]).map(d=><option key={String(d.code)} value={String(d.code)}>{String(d.display_name||d.code)}</option>)}</select></label>
 <label>Academic year<select aria-label="Filter academic year" disabled={loading} value={value.academic_year_id} onChange={e=>onChange({...value,academic_year_id:e.target.value,semester_id:''})}><option value="">All academic years</option>{(catalog.years||[]).map(y=><option key={String(y.id)} value={String(y.id)}>{String(y.label)}</option>)}</select></label>
 <label>Semester<select aria-label="Filter semester" disabled={loading||!value.academic_year_id} value={value.semester_id} onChange={e=>onChange({...value,semester_id:e.target.value})}><option value="">{value.academic_year_id?'All semesters':'Choose academic year first'}</option>{semesters.map(s=><option key={String(s.id)} value={String(s.id)}>Semester {String(s.number)}</option>)}</select></label>
 <label>Batch<select aria-label="Filter batch" disabled={loading} value={value.batch_id} onChange={e=>onChange({...value,batch_id:e.target.value})}><option value="">All batches</option>{batches.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.label)}</option>)}</select></label></div>
 {loading?<p role="status">Loading academic options…</p>:failed.length?<p role="alert">Could not load {failed.join(', ')}. <button className="erp-quiet" onClick={()=>setRevision(r=>r+1)}>Retry filters</button></p>:!catalog.years?.length||!catalog.batches?.length||!catalog.sections?.length?<p>Academic setup needs years, batches and class sections. {onSetup&&<button className="erp-option-refresh" onClick={onSetup}>Complete academic setup</button>}</p>:<p>Selections stay with you across service tabs and pre-fill uploads. Student records without a matching class assignment are excluded when academic filters are selected.</p>}
 </section>;
}
