import {useEffect,useId,useRef,useState} from 'react';
import {Download,Eye,Upload,X} from 'lucide-react';
import {emptyAcademicContext,type AcademicContext} from './ErpAcademicFilters';

type Call=<T,>(path:string,method?:string,body?:unknown)=>Promise<T>;
type Row={id:string;row_number:number;status:string;original_values:Record<string,unknown>;issues:Array<{action?:string}>};
type Option=Record<string,unknown>;
export default function ErpServiceBulk({module,heading,description,call,writable,onImported,onError,onWorkbook,onSetup,academicContext,downloadQuery}:{module:string;heading:string;description:string;call:Call;writable:boolean;onImported:()=>void;onError:(message:string)=>void;onWorkbook:()=>void;onSetup?:()=>void;academicContext?:AcademicContext;downloadQuery?:string}){
 const uploadButton=useRef<HTMLButtonElement>(null);const dialog=useRef<HTMLDialogElement>(null);const titleId=useId();const [uploadError,setUploadError]=useState('');
 const [catalog,setCatalog]=useState<Record<string,Option[]>>({});const [context,setContext]=useState<AcademicContext>(academicContext||emptyAcademicContext);
 const [catalogLoading,setCatalogLoading]=useState(true);const [failedCatalogs,setFailedCatalogs]=useState<string[]>([]);const [catalogRevision,setCatalogRevision]=useState(0);
 const [upload,setUpload]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [rows,setRows]=useState<Row[]>([]);const [batch,setBatch]=useState('');const [selected,setSelected]=useState<string[]>([]);const [category,setCategory]=useState('');const [offset,setOffset]=useState(0);const [confirmSkip,setConfirmSkip]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{if(!upload)return;const element=dialog.current;if(!element)return;element.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{element.close();document.body.style.overflow=previous;uploadButton.current?.focus();};},[upload]);
 function closeUpload(){if(busy)return;setUpload(false);setFile(null);setUploadError('');reset();}
 function reportError(message:string){setUploadError(message);onError(message);}
 useEffect(()=>{let live=true;setCatalogLoading(true);const names=['departments','years','batches','sections','semesters'];void Promise.allSettled(names.map(async name=>(await call<{items:Option[]}>(`/api/college/erp/catalog/${name}`)).items)).then(results=>{if(!live)return;const failed:string[]=[];const loaded:Record<string,Option[]>={};results.forEach((result,index)=>{if(result.status==='fulfilled')loaded[names[index]]=result.value;else failed.push(names[index]);});setCatalog(loaded);setFailedCatalogs(failed);setCatalogLoading(false);});return()=>{live=false};},[call,catalogRevision]);
 const semesters=(catalog.semesters||[]).filter(s=>s.academic_year_id===context.academic_year_id);
 const department=catalog.departments?.find(d=>d.code===context.department_code);
 const batches=(catalog.batches||[]).filter(b=>(catalog.sections||[]).some(s=>s.batch_id===b.id&&s.department_code===context.department_code)||(b.program_code&&b.program_code===department?.program));
 function reset(){setRows([]);setBatch('');setSelected([]);setCategory('');setConfirmSkip(false);setNotice('');setOffset(0);}
 async function download(template=false){setBusy(true);setUploadError('');onError('');try{const blob=await call<Blob>(`/api/college/erp/records/${module}/download${template?'?template=true':downloadQuery?`?${downloadQuery}`:''}`);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${module}-${template?'template':'records'}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){reportError((e as Error).message);}finally{setBusy(false);}}
 async function preview(){if(!file)return;setBusy(true);setUploadError('');onError('');reset();try{const body=new FormData();body.append('file',file);Object.entries(context).forEach(([key,value])=>body.append(key,value));const data=await call<{batch_id:string;rows:Row[]}>(`/api/college/erp/records/${module}/preview`,'POST',body);setRows(data.rows);setBatch(data.batch_id);setSelected(data.rows.filter(r=>r.status==='valid').map(r=>r.id));}catch(e){reportError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){setBusy(true);setUploadError('');onError('');try{const result=await call<{committed:number;skipped:number}>(`/api/college/erp/records/${module}/commit`,'POST',{batch_id:batch,approved_rows:selected});reset();setNotice(`${result.committed} records saved together. ${result.skipped} rows skipped.`);setFile(null);setUpload(false);onImported();}catch(e){reportError((e as Error).message);}finally{setBusy(false);}}
 function correctionReport(){
  const needingReview=rows.filter(row=>row.status!=='valid');const keys=[...new Set(needingReview.flatMap(row=>Object.keys(row.original_values)))];
  const escape=(value:unknown)=>{let text=String(value??'');if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};
  const data=[['Excel row','Review status','What to fix',...keys],...needingReview.map(row=>[row.row_number,row.status,row.issues.map(issue=>issue.action||'Review this record').join('; '),...keys.map(key=>row.original_values[key])])];
  const url=URL.createObjectURL(new Blob(['\ufeff'+data.map(row=>row.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${module}-correction-report.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 const types=[['valid','Valid'],['conflict','Conflicts'],['invalid','Errors']];const filtered=rows.filter(r=>r.status===category);const skipped=rows.length-selected.length;
 return <section className="erp-bulk-service" aria-label="Bulk data actions"><header className="erp-page-head erp-service-head"><div className="erp-service-title"><p className="erp-eyebrow">ACADEMIC SERVICE</p><h1>{heading}</h1><p>{description}</p></div><div className="erp-service-actions">{writable&&<button ref={uploadButton} className="erp-primary" disabled={busy} onClick={()=>{setUploadError('');onError('');setContext(academicContext||emptyAcademicContext);reset();setUpload(true);}}><Upload size={16}/>Upload</button>}<button className="erp-quiet" disabled={busy} onClick={()=>void download()}><Download size={16}/>Download</button><button className="erp-quiet" disabled={busy} onClick={()=>{setUpload(false);onImported();}}><Eye size={16}/>View</button></div></header>{notice&&<p className="erp-notice" role="status">{notice}</p>}
 {upload&&<dialog ref={dialog} className="erp-upload-dialog" aria-labelledby={titleId} onCancel={e=>{e.preventDefault();closeUpload();}}><div className="erp-card"><div className="erp-upload-dialog-head"><div><p className="erp-eyebrow">{heading}</p><h2 id={titleId}>Upload records in bulk</h2></div><button type="button" className="erp-quiet" aria-label="Close upload" disabled={busy} onClick={closeUpload} autoFocus><X size={20}/></button></div>{uploadError&&<div className="erp-error" role="alert">{uploadError}</div>}<p>Download the template for this service, fill it in and upload it. Keep the record ID and version when updating downloaded records.</p><div className="erp-form-actions"><button className="erp-quiet" disabled={busy} onClick={()=>void download(true)}>Download upload template</button><button className="erp-quiet" disabled={busy} onClick={()=>{closeUpload();onWorkbook();}}>Import standard Veltech workbook</button></div>{catalogLoading&&<p role="status">Loading academic options…</p>}{failedCatalogs.length>0&&<p role="alert">Could not load {failedCatalogs.join(', ')}. <button className="erp-quiet" onClick={()=>setCatalogRevision(r=>r+1)}>Retry options</button></p>}{!catalogLoading&&(!catalog.years?.length||!catalog.batches?.length||!catalog.semesters?.length)&&<div className="erp-notice"><strong>Academic setup is incomplete.</strong><p>Add the institution’s academic years, intake batches and semesters to make them available here.</p>{onSetup?<button className="erp-quiet" disabled={busy} onClick={()=>{closeUpload();onSetup?.();}}>Open Academic Setup</button>:<p>Ask your institution administrator to complete academic setup.</p>}</div>}<div className="erp-form-grid">
 <label>Branch / Department<select aria-label="Upload department" value={context.department_code} disabled={busy||catalogLoading} onChange={e=>{setContext({...context,department_code:e.target.value,batch_id:'',semester_id:''});reset();}}><option value="">{catalogLoading?"Loading branches…":catalog.departments?.length?"Select branch / department":"No branches configured"}</option>{(catalog.departments||[]).map(d=><option key={String(d.code)} value={String(d.code)}>{String(d.display_name||d.code)}</option>)}</select></label>
 <label>Academic year<select aria-label="Upload academic year" value={context.academic_year_id} disabled={busy||catalogLoading||!context.department_code} onChange={e=>{setContext({...context,academic_year_id:e.target.value,batch_id:'',semester_id:''});reset();}}><option value="">{catalogLoading?"Loading academic years…":catalog.years?.length?"Select academic year":"No academic years configured"}</option>{(catalog.years||[]).map(y=><option key={String(y.id)} value={String(y.id)}>{String(y.label)}</option>)}</select></label>
 <label>Semester<select aria-label="Upload semester" value={context.semester_id} disabled={busy||catalogLoading||!context.academic_year_id} onChange={e=>{setContext({...context,semester_id:e.target.value});reset();}}><option value="">{!context.academic_year_id?"Select academic year first":semesters.length?"Select semester (optional)":"No semesters configured for this year"}</option>{semesters.map(s=><option key={String(s.id)} value={String(s.id)}>Semester {String(s.number)}</option>)}</select></label>
 <label>Batch<select aria-label="Upload batch" value={context.batch_id} disabled={busy||catalogLoading||!context.academic_year_id} onChange={e=>{setContext({...context,batch_id:e.target.value});reset();}}><option value="">{!context.department_code?"Select branch first":batches.length?"Select batch":"No batches configured for this branch"}</option>{batches.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.label)}</option>)}</select></label>
 <label>Excel or CSV file<input aria-label="Service upload file" type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);reset();}}/></label></div><p>Students must already have a class assignment for the selected department, year and batch. Missing academic setup must be completed before uploading.</p><button className="erp-primary" disabled={busy||!file||!context.department_code||!context.academic_year_id||!context.batch_id} onClick={()=>void preview()}>{busy?'Processing…':'Check records'}</button>
 {batch&&<><div className="erp-form-actions"><button className="erp-quiet" disabled={busy||!rows.some(row=>row.status!=='valid')} onClick={correctionReport}><Download size={16}/>Download correction report</button></div><div className="erp-form-actions">{types.map(([key,title])=><button key={key} className={category===key?'erp-primary':'erp-quiet'} aria-pressed={category===key} onClick={()=>{setCategory(key);setOffset(0);}}>{title} ({rows.filter(r=>r.status===key).length})</button>)}</div><p>{selected.length} selected · {skipped} will be skipped. Existing records require approval in Conflicts.</p>
 {category&&<><div className="erp-form-actions">{category!=='invalid'&&<button className="erp-quiet" onClick={()=>{setSelected([...new Set([...selected,...filtered.map(r=>r.id)])]);setConfirmSkip(false);}}>Select all {category==='conflict'?'updates':'valid rows'}</button>}</div><div className="erp-table-wrap"><table><thead><tr><th>Import</th><th>Excel row</th><th>Values</th><th>Review</th></tr></thead><tbody>{filtered.slice(offset,offset+10).map(row=><tr key={row.id}><td><input aria-label={`Import row ${row.row_number}`} type="checkbox" disabled={row.status==='invalid'||busy} checked={selected.includes(row.id)} onChange={e=>{setSelected(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id));setConfirmSkip(false);}}/></td><td>{row.row_number}</td><td><details><summary>View uploaded values</summary>{Object.entries(row.original_values).map(([key,value])=><p key={key}><strong>{key}:</strong> {String(value??'—')}</p>)}</details></td><td>{row.issues.map((issue,i)=><p key={i}>{issue.action}</p>)}</td></tr>)}</tbody></table></div><div className="erp-form-actions"><button className="erp-quiet" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-10))}>Previous</button><span>Page {Math.floor(offset/10)+1}</span><button className="erp-quiet" disabled={offset+10>=filtered.length} onClick={()=>setOffset(offset+10)}>Next</button></div></>}
 {skipped>0&&<label><input type="checkbox" checked={confirmSkip} onChange={e=>setConfirmSkip(e.target.checked)}/> Skip the {skipped} unselected rows</label>}<div className="erp-form-actions"><button className="erp-primary" disabled={busy||!selected.length||(skipped>0&&!confirmSkip)} onClick={()=>void commit()}>Import {selected.length} selected rows</button></div></>}
 </div></dialog>}</section>;
}
