import {useEffect,useState} from 'react';
import {Download,Eye,Upload} from 'lucide-react';

type Call=<T,>(path:string,method?:string,body?:unknown)=>Promise<T>;
type Row={id:string;row_number:number;status:string;original_values:Record<string,unknown>;issues:Array<{action?:string}>};
type Option=Record<string,unknown>;
export default function ErpServiceBulk({module,heading,description,call,writable,onImported,onError,onWorkbook}:{module:string;heading:string;description:string;call:Call;writable:boolean;onImported:()=>void;onError:(message:string)=>void;onWorkbook:()=>void}){
 const [catalog,setCatalog]=useState<Record<string,Option[]>>({});const [context,setContext]=useState({department_code:'',academic_year_id:'',batch_id:''});
 const [upload,setUpload]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [rows,setRows]=useState<Row[]>([]);const [batch,setBatch]=useState('');const [selected,setSelected]=useState<string[]>([]);const [category,setCategory]=useState('');const [offset,setOffset]=useState(0);const [confirmSkip,setConfirmSkip]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{let live=true;void Promise.all(['departments','years','batches','sections'].map(async name=>[name,(await call<{items:Option[]}>(`/api/college/erp/catalog/${name}`)).items] as const)).then(values=>{if(live)setCatalog(Object.fromEntries(values));}).catch(e=>{if(live)onError((e as Error).message);});return()=>{live=false};},[call]);
 const department=catalog.departments?.find(d=>d.code===context.department_code);
 const batches=(catalog.batches||[]).filter(b=>(catalog.sections||[]).some(s=>s.batch_id===b.id&&s.department_code===context.department_code)||(b.program_code&&b.program_code===department?.program));
 function reset(){setRows([]);setBatch('');setSelected([]);setCategory('');setConfirmSkip(false);setNotice('');setOffset(0);}
 async function download(template=false){setBusy(true);onError('');try{const blob=await call<Blob>(`/api/college/erp/records/${module}/download${template?'?template=true':''}`);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${module}-${template?'template':'records'}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 async function preview(){if(!file)return;setBusy(true);onError('');reset();try{const body=new FormData();body.append('file',file);Object.entries(context).forEach(([key,value])=>body.append(key,value));const data=await call<{batch_id:string;rows:Row[]}>(`/api/college/erp/records/${module}/preview`,'POST',body);setRows(data.rows);setBatch(data.batch_id);setSelected(data.rows.filter(r=>r.status==='valid').map(r=>r.id));}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){setBusy(true);onError('');try{const result=await call<{committed:number;skipped:number}>(`/api/college/erp/records/${module}/commit`,'POST',{batch_id:batch,approved_rows:selected});reset();setNotice(`${result.committed} records saved together. ${result.skipped} rows skipped.`);setFile(null);onImported();}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 const types=[['valid','Valid'],['conflict','Conflicts'],['invalid','Errors']];const filtered=rows.filter(r=>r.status===category);const skipped=rows.length-selected.length;
 return <section className="erp-bulk-service" aria-label="Bulk data actions"><header className="erp-page-head erp-service-head"><div className="erp-service-title"><p className="erp-eyebrow">ACADEMIC SERVICE</p><h1>{heading}</h1><p>{description}</p></div><div className="erp-service-actions">{writable&&<button className="erp-primary" disabled={busy} onClick={()=>setUpload(!upload)}><Upload size={16}/>Upload</button>}<button className="erp-quiet" disabled={busy} onClick={()=>void download()}><Download size={16}/>Download</button><button className="erp-quiet" disabled={busy} onClick={()=>{setUpload(false);onImported();}}><Eye size={16}/>View</button></div></header>{notice&&<p className="erp-notice" role="status">{notice}</p>}
 {upload&&<div className="erp-card"><h2>Upload records in bulk</h2><p>Download the template for this service, fill it in and upload it. Keep the record ID and version when updating downloaded records.</p><div className="erp-form-actions"><button className="erp-quiet" disabled={busy} onClick={()=>void download(true)}>Download upload template</button><button className="erp-quiet" disabled={busy} onClick={onWorkbook}>Import standard Veltech workbook</button></div><div className="erp-form-grid">
 <label>Department<select aria-label="Upload department" value={context.department_code} disabled={busy} onChange={e=>{setContext({...context,department_code:e.target.value,batch_id:''});reset();}}><option value="">Select department</option>{(catalog.departments||[]).map(d=><option key={String(d.code)} value={String(d.code)}>{String(d.display_name||d.code)}</option>)}</select></label>
 <label>Academic year<select aria-label="Upload academic year" value={context.academic_year_id} disabled={busy||!context.department_code} onChange={e=>{setContext({...context,academic_year_id:e.target.value,batch_id:''});reset();}}><option value="">Select academic year</option>{(catalog.years||[]).map(y=><option key={String(y.id)} value={String(y.id)}>{String(y.label)}</option>)}</select></label>
 <label>Batch<select aria-label="Upload batch" value={context.batch_id} disabled={busy||!context.academic_year_id} onChange={e=>{setContext({...context,batch_id:e.target.value});reset();}}><option value="">Select batch</option>{batches.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.label)}</option>)}</select></label>
 <label>Excel or CSV file<input aria-label="Service upload file" type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);reset();}}/></label></div><p>Students must already have a class assignment for the selected department, year and batch. Missing academic setup must be completed before uploading.</p><button className="erp-primary" disabled={busy||!file||!context.department_code||!context.academic_year_id||!context.batch_id} onClick={()=>void preview()}>{busy?'Processing…':'Check records'}</button>
 {batch&&<><div className="erp-form-actions">{types.map(([key,title])=><button key={key} className={category===key?'erp-primary':'erp-quiet'} aria-pressed={category===key} onClick={()=>{setCategory(key);setOffset(0);}}>{title} ({rows.filter(r=>r.status===key).length})</button>)}</div><p>{selected.length} selected · {skipped} will be skipped. Existing records require approval in Conflicts.</p>
 {category&&<><div className="erp-form-actions">{category!=='invalid'&&<button className="erp-quiet" onClick={()=>{setSelected([...new Set([...selected,...filtered.map(r=>r.id)])]);setConfirmSkip(false);}}>Select all {category==='conflict'?'updates':'valid rows'}</button>}</div><div className="erp-table-wrap"><table><thead><tr><th>Import</th><th>Excel row</th><th>Values</th><th>Review</th></tr></thead><tbody>{filtered.slice(offset,offset+10).map(row=><tr key={row.id}><td><input aria-label={`Import row ${row.row_number}`} type="checkbox" disabled={row.status==='invalid'||busy} checked={selected.includes(row.id)} onChange={e=>{setSelected(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id));setConfirmSkip(false);}}/></td><td>{row.row_number}</td><td><details><summary>View uploaded values</summary>{Object.entries(row.original_values).map(([key,value])=><p key={key}><strong>{key}:</strong> {String(value??'—')}</p>)}</details></td><td>{row.issues.map((issue,i)=><p key={i}>{issue.action}</p>)}</td></tr>)}</tbody></table></div><div className="erp-form-actions"><button className="erp-quiet" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-10))}>Previous</button><span>Page {Math.floor(offset/10)+1}</span><button className="erp-quiet" disabled={offset+10>=filtered.length} onClick={()=>setOffset(offset+10)}>Next</button></div></>}
 {skipped>0&&<label><input type="checkbox" checked={confirmSkip} onChange={e=>setConfirmSkip(e.target.checked)}/> Skip the {skipped} unselected rows</label>}<div className="erp-form-actions"><button className="erp-primary" disabled={busy||!selected.length||(skipped>0&&!confirmSkip)} onClick={()=>void commit()}>Import {selected.length} selected rows</button></div></>}
 </div>}</section>;
}
