import {useState} from 'react';
import {Download,FileSpreadsheet,ArrowRight,Check,Settings2} from 'lucide-react';
import {ErpFields,type ErpCall} from './ErpFields';
type MappingSheet={source_sheet:string;target_sheet:string|null;header_row:number;columns:Record<string,number>;defaults:Record<string,unknown>};
type Mapping={sheets:MappingSheet[]};
type Sheet={name:string;data_rows:number;suggested_header_row:number;instruction_sheet:boolean;header_rows:{row:number;columns:{index:number;label:string}[]}[]};
type Template={id:string;name:string;mapping:Mapping};
type Inspection={sheets:Sheet[];mapping:Mapping;targets:{name:string;fields:string[];required:string[]}[];matching_templates:Template[];standard:{name:string;sheets:Record<string,string[]>}};
const personal=new Set(['Student ID','Roll Number','Registration Number','Student Name','Email','Guardian Name','Guardian Phone (with +91)','Guardian Email','Official Email','Staff Name']);
const sharedFields:Record<string,string>={'Program':'program','Department Code':'department_code','Academic Year ID':'academic_year_id','Semester ID':'semester_id','Subject ID':'subject_id','Class ID':'class_id','Reviewer Staff ID':'reviewer_staff_id','Staff ID':'staff_id'};
export default function ErpWorkbookImport({call,onPreview}:{call:ErpCall;onPreview:(result:unknown)=>void}){
 const [file,setFile]=useState<File|null>(null);const [csvType,setCsvType]=useState('Students');const [inspection,setInspection]=useState<Inspection|null>(null);const [mapping,setMapping]=useState<Mapping>({sheets:[]});const [active,setActive]=useState('');const [template,setTemplate]=useState('');const [saveStandard,setSaveStandard]=useState(false);const [standardName,setStandardName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [expanded,setExpanded]=useState(false);
 const formData=()=>{const data=new FormData();data.append('file',file!);if(file?.name.toLowerCase().endsWith('.csv'))data.append('sheet_name',csvType);return data};
 const isCsv=file?.name.toLowerCase().endsWith('.csv');
 async function inspect(){if(!file)return;setBusy(true);setError('');try{const result=await call<Inspection>('/api/college/erp/imports/inspect','POST',formData());setInspection(result);const standard=result.matching_templates[0];setMapping(standard?.mapping||result.mapping);setTemplate(standard?.id||'');setActive(result.sheets.find(s=>!s.instruction_sheet)?.name||result.sheets[0]?.name||'');setExpanded(false);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function update(sheet:string,patch:Partial<MappingSheet>){setMapping(prev=>({sheets:prev.sheets.map(s=>s.source_sheet===sheet?{...s,...patch}:s)}));setTemplate('')}
 function chooseTemplate(id:string){setTemplate(id);setMapping(id?inspection!.matching_templates.find(t=>t.id===id)!.mapping:inspection!.mapping);setExpanded(false)}
 async function preview(){setBusy(true);setError('');try{const data=formData();data.append('mapping_json',JSON.stringify(mapping));if(template)data.append('template_id',template);if(saveStandard)data.append('save_standard_name',standardName.trim());const result=await call('/api/college/erp/imports/preview','POST',data);onPreview(result);setExpanded(false);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function download(){setError('');try{const blob=await call<Blob>('/api/college/erp/imports/standard');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Veltech_ERP_Standard.xlsx';a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message)}}
 const selected=mapping.sheets.find(s=>s.source_sheet===active);const source=inspection?.sheets.find(s=>s.name===active);const target=inspection?.targets.find(t=>t.name===selected?.target_sheet);const header=source?.header_rows.find(r=>r.row===selected?.header_row);
 const mappedSheets=mapping.sheets.filter(s=>s.target_sheet);
 const missing=mapping.sheets.flatMap(s=>inspection?.targets.find(t=>t.name===s.target_sheet)?.required.filter(f=>!s.columns[f]&&(s.defaults[f]===undefined||s.defaults[f]===null||s.defaults[f]==='')).map(f=>`${s.source_sheet}: ${f}`)||[]);
 return <section className="erp-workbook-import">
  <div className="erp-standard-intro"><div><FileSpreadsheet size={24}/><div><h2>One workbook. All your records.</h2><p>Use the Veltech format to import Students, Fees, Marks, Attendance, Reviews and Contacts together.</p></div></div><button type="button" className="erp-quiet" onClick={()=>void download()}><Download size={16}/> Download standard workbook</button></div>
  <ol className="erp-import-steps" aria-label="Workbook import steps"><li className="active">1. Upload workbook</li><li className={inspection?'active':''}>2. Confirm mapping</li><li>3. Review & import</li></ol>
  {error&&<div className="erp-error" role="alert">{error}</div>}
  {!inspection?<div className="erp-upload"><div><strong>Upload the whole workbook</strong><span>Excel .xlsx with multiple sheets · CSV also supported · 15 MB maximum</span></div><label className="erp-file-choice">Choose workbook<input aria-label="Choose workbook" type="file" accept=".xlsx,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);setError('')}}/></label>{isCsv&&<label>CSV data type<select value={csvType} onChange={e=>setCsvType(e.target.value)}>{['Students','Fees','Marks','Attendance Summary','Attendance Today','Academic Review','Academic Contacts'].map(t=><option key={t}>{t}</option>)}</select></label>}<button type="button" className="erp-primary" disabled={!file||busy} onClick={()=>void inspect()}>{busy?'Reading sheets…':'Read workbook'}<ArrowRight size={16}/></button></div>:<>
   <div className="erp-mapping-summary"><div><h2>{file?.name}</h2><p>{inspection.sheets.length} sheets found · {mappedSheets.length} selected for import</p></div><button className="erp-quiet" disabled={busy} onClick={()=>{setInspection(null);setFile(null)}}>Choose another file</button></div>
   <div className="erp-template-choice"><label>Mapping standard<select value={template} onChange={e=>chooseTemplate(e.target.value)}><option value="">Veltech standard / detected columns</option>{inspection.matching_templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p>{template?'A saved standard matches this workbook. Review the summary and preview all sheets together.':'Matching sheet names and columns are mapped automatically. Review the summary or adjust any differences.'}</p></div>
   <div className="erp-sheet-summary"><table><thead><tr><th>Workbook sheet</th><th>ERP records</th><th>Header row</th><th>Rows</th><th>Mapping</th></tr></thead><tbody>{mapping.sheets.map(s=><tr key={s.source_sheet}><td><strong>{s.source_sheet}</strong></td><td><select aria-label={`Data type for ${s.source_sheet}`} value={s.target_sheet||''} onChange={e=>{const type=e.target.value||null;const sourceSheet=inspection.sheets.find(x=>x.name===s.source_sheet)!;const cols=sourceSheet.header_rows.find(r=>r.row===s.header_row)?.columns||[];const fields=inspection.targets.find(x=>x.name===type)?.fields||[];update(s.source_sheet,{target_sheet:type,columns:Object.fromEntries(fields.flatMap(f=>{const c=cols.find(c=>c.label.toLowerCase()===f.toLowerCase());return c?[[f,c.index]]:[]})),defaults:{}})}}><option value="">Ignore this sheet</option>{inspection.targets.map(t=><option key={t.name}>{t.name}</option>)}</select></td><td>{s.header_row}</td><td>{Math.max(0,(inspection.sheets.find(x=>x.name===s.source_sheet)?.data_rows||0)+(inspection.sheets.find(x=>x.name===s.source_sheet)?.suggested_header_row||s.header_row)-s.header_row)}</td><td>{s.target_sheet?<button className="erp-quiet" onClick={()=>{setActive(s.source_sheet);setExpanded(true)}}><Settings2 size={14}/>{Object.keys(s.columns).length} columns · Adjust</button>:<span className="erp-pill">Ignored</span>}</td></tr>)}</tbody></table></div>
   <p className="erp-mapping-note">“Read Me” is ignored by default. Any other ignored sheet is listed explicitly here and in the saved import history.</p>
   {expanded&&selected&&source&&<div className="erp-card"><div className="erp-page-head"><div><h2>Map {selected.source_sheet}</h2><p>Choose its header row, then connect workbook columns to ERP fields.</p></div><button className="erp-quiet" onClick={()=>setExpanded(false)}>Done mapping</button></div><label className="erp-header-choice">Header row<select aria-label={`Header row for ${active}`} value={selected.header_row} onChange={e=>update(active,{header_row:Number(e.target.value),columns:{}})}>{source.header_rows.map(r=><option key={r.row} value={r.row}>Row {r.row} · {r.columns.filter(c=>c.label).slice(0,3).map(c=>c.label).join(' / ')}</option>)}</select></label>{!selected.target_sheet?<p>This sheet is ignored. Select an ERP data type above to map it.</p>:<div className="erp-column-mapping">{target?.fields.map(field=><div className="erp-field-mapping" key={`${active}-${field}`}><label htmlFor={`column-${field}`}>{field}{target.required.includes(field)?' *':''}</label><select id={`column-${field}`} value={selected.columns[field]||''} onChange={e=>{const columns={...selected.columns};if(e.target.value)columns[field]=Number(e.target.value);else delete columns[field];update(active,{columns})}}><option value="">Not in workbook</option>{header?.columns.filter(c=>c.label).map(c=><option key={c.index} value={c.index}>{c.label} · column {c.index}</option>)}</select>{!personal.has(field)&&!selected.columns[field]&&<div className="erp-shared-value">{sharedFields[field]?<form key={`${active}-${field}`} onChange={e=>{const form=e.currentTarget as HTMLFormElement;const value=new FormData(form).get(sharedFields[field]);update(active,{defaults:{...selected.defaults,[field]:value||''}})}}><ErpFields names={[sharedFields[field]]} values={{[sharedFields[field]]:selected.defaults[field]||''}}/></form>:<input aria-label={`Shared ${field} for ${active}`} placeholder="Shared value for this sheet (optional)" value={String(selected.defaults[field]??'')} onChange={e=>update(active,{defaults:{...selected.defaults,[field]:e.target.value}})}/>}</div>}</div>)}</div>}<p className="erp-mapping-note">Shared values apply to empty cells across this sheet—for example Program, Maximum Marks or Assessment Name. Student identifiers, names and emails must be mapped from actual columns.</p></div>}
   {missing.length>0&&<div className="erp-error" role="alert">Required mappings missing: {missing.join(' · ')}</div>}
   <div className="erp-save-standard"><label className="erp-check"><input type="checkbox" checked={saveStandard} onChange={e=>setSaveStandard(e.target.checked)}/> Save this mapping as an institution standard</label><p>Stores sheet names, headers, column mappings and shared settings. Future matching workbooks can reuse it.</p>{saveStandard&&<label>Standard name<input aria-label="Standard name" maxLength={120} placeholder="e.g. Monthly student records" value={standardName} onChange={e=>setStandardName(e.target.value)}/></label>}</div>
   <div className="erp-form-actions"><span>{mappedSheets.length} sheets will be previewed together</span><button className="erp-primary" disabled={busy||!mappedSheets.length||!!missing.length||(saveStandard&&!standardName.trim())} onClick={()=>void preview()}>{busy?'Preparing all sheets…':'Preview all sheets'}<ArrowRight size={16}/></button></div>
   <div className="erp-standard-check"><Check size={16}/> Student records are imported before related fees, marks and attendance.</div>
  </>}
 </section>
}
