import {useEffect,useState} from 'react';
import {collegeApi,collegeError} from '@/api/collegeApi';
import {btn,field,panel} from './interviewAgentTypes';
type Rating=Record<string,number|null>;
type Group={label:string;interviews:number;responses:number;skipped:number;ratings:Rating};
type Row={session_id:string;full_name:string;student_id:string;roll_number:string;graduation_year:number|null;department_code:string;feedback_state:string;comments:string;overall:number|null;ended_at:string};
type Report={questions:{key:string;label:string}[];summary:Group[];by_year:Group[];by_department:Group[];by_student:Group[];items:Row[]};
export default function InterviewFeedback({driveId}:{driveId:string}){
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 const [year,setYear]=useState(''),[department,setDepartment]=useState(''),[student,setStudent]=useState(''),[group,setGroup]=useState<'by_year'|'by_department'|'by_student'>('by_department'),[refresh,setRefresh]=useState(0);
 const [options,setOptions]=useState<Row[]>([]);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');const p=new URLSearchParams();if(year)p.set('graduation_year',year);if(department)p.set('department',department);if(student)p.set('student',student);
 collegeApi.get<Report>(`drives/${driveId}/feedback-report?${p}`,c.signal).then(r=>{if(c.signal.aborted)return;setData(r);if(!year&&!department&&!student)setOptions(r.items);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[driveId,year,department,student,refresh]);
 const summary=data?.summary[0];
 function download(){if(!data)return;const escape=(v:unknown)=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const columns=['Student','Roll number','Batch year','Department','Status','Overall (1–5)','Comments','Interview ended'];const csv=[columns,...data.items.map(r=>[r.full_name,r.roll_number,r.graduation_year,r.department_code,r.feedback_state,r.overall,r.comments,r.ended_at])].map(r=>r.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='interview-feedback.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const years=[...new Set(options.map(r=>r.graduation_year).filter(Boolean))].sort();const departments=[...new Set(options.map(r=>r.department_code))].sort();const students=[...new Map(options.map(r=>[r.student_id,r])).values()];
 return <section className="space-y-5" aria-label="Student interview feedback"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Student feedback</h2><p className="mt-1 text-sm text-slate-500">Optional interview experience ratings. Feedback does not affect interview scores or placement decisions.</p></div><div className="flex gap-2"><button className={btn} disabled={busy} onClick={()=>setRefresh(x=>x+1)}>Refresh feedback</button><button className={btn} disabled={busy||!data?.items.length} onClick={download}>Export feedback</button></div></div>
 <div className={`${panel} flex flex-wrap gap-4`}><label className="text-sm">Batch year<select aria-label="Batch year" className={field} value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{years.map(y=><option key={y!}>{y}</option>)}</select></label><label className="text-sm">Department<select aria-label="Department" className={field} value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All departments</option>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label className="text-sm">Student<select aria-label="Student" className={field} value={student} onChange={e=>setStudent(e.target.value)}><option value="">All students</option>{students.map(s=><option key={s.student_id} value={s.student_id}>{s.full_name} · {s.roll_number}</option>)}</select></label><button className={`${btn} self-end`} onClick={()=>{setYear('');setDepartment('');setStudent('');}}>Clear filters</button></div>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{busy?<p role="status">Loading student feedback…</p>:data&&<><div className="grid gap-3 sm:grid-cols-4">{[['Completed/ended interviews',summary?.interviews||0],['Feedback received',summary?.responses||0],['Skipped',summary?.skipped||0],['Overall experience',summary?.ratings.overall==null?'Not rated':`${summary.ratings.overall}/5`]].map(([label,value])=><div key={String(label)} className={panel}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
 <div className={panel}><h3 className="font-medium">Experience by question</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{data.questions.map(q=><div key={q.key}><p className="text-sm text-slate-500">{q.label}</p><p className="mt-2 font-semibold">{summary?.ratings[q.key]==null?'Not rated':`${summary.ratings[q.key]}/5`}</p></div>)}</div></div>
 <div className={panel}><label className="text-sm">Group feedback by<select aria-label="Group feedback by" className={field} value={group} onChange={e=>setGroup(e.target.value as typeof group)}><option value="by_department">Department</option><option value="by_year">Batch year</option><option value="by_student">Student</option></select></label><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Group','Interviews','Responses','Overall /5'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data[group].map(g=><tr className="border-t" key={g.label}><td className="p-3">{group==='by_student'?students.find(s=>s.student_id===g.label)?.full_name||g.label:g.label}</td><td className="p-3">{g.interviews}</td><td className="p-3">{g.responses}</td><td className="p-3">{g.ratings.overall??'Not rated'}</td></tr>)}</tbody></table></div></div>
 <div className={panel}><h3 className="font-medium">Individual responses</h3>{!data.items.length?<p className="mt-3 text-sm text-slate-500">No ended interviews match these filters yet.</p>:<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Student','Batch year','Department','Feedback','Overall /5','Comments'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(r=><tr className="border-t align-top" key={r.session_id}><td className="p-3">{r.full_name}<p className="text-xs text-slate-500">{r.roll_number}</p></td><td className="p-3">{r.graduation_year??'Not specified'}</td><td className="p-3">{r.department_code}</td><td className="p-3">{r.feedback_state==='submitted'?'Submitted':r.feedback_state==='skipped'?'Skipped':'Not submitted'}</td><td className="p-3">{r.overall??'—'}</td><td className="max-w-sm whitespace-pre-wrap p-3">{r.comments||'—'}</td></tr>)}</tbody></table></div>}</div></>}
 </section>;
}
