import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
import Dialog from './QpgDialog';
import QpgRenderPreview from './QpgRenderPreview';
import type {RenderModel} from './QpgRenderPreview';
import {Result} from './QpgGeneratePanel';
import type {Candidate,CandidateEdit} from './QpgGeneratePanel';
import type {SyllabusItem} from '@/api/qpgApi';
type Job={id:string;status:string;revision:number;results:Candidate[];failure_reason:string};
type Position={item_id:string;label:string;section:string;request:{marks:string;question_type:string;co_id:string;unit_id:string;topic_id:string;bloom_level:string;difficulty:string};job:Job|null};
type Build={id:string;status:string;revision:number;failure_reason:string;stale:boolean;paper_revision:number;positions:Position[];reused_count?:number;total_positions?:number};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgAiBuildPanel({paperId,revision,emptyCount,syllabus,onAssembled,onReview}:{paperId:string;revision:number;emptyCount:number;syllabus:{cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]};onAssembled:()=>Promise<void>;onReview:()=>void}){
 const [build,setBuild]=useState<Build|null>(null),[enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 const [sourceMode,setSourceMode]=useState('SYLLABUS'),[reuseApproved,setReuseApproved]=useState(false);
 const [previewTemplate,setPreviewTemplate]=useState('university');
 const [editPaper,setEditPaper]=useState(false),[editNotice,setEditNotice]=useState('');
 const [actionCandidate,setActionCandidate]=useState('');
 const [bulkNotice,setBulkNotice]=useState(''),[bulkFailures,setBulkFailures]=useState<string[]>([]);
 const [draftPreview,setDraftPreview]=useState<RenderModel|null>(null);
 const [instructions,setInstructions]=useState(''),[formatConfirmed,setFormatConfirmed]=useState(false);
 const path=`papers/${paperId}/ai-build`;
 const active=!!build&&['QUEUED','RUNNING'].includes(build.status);
 async function refresh(){setBuild((await qpgApi.get<{build:Build|null}>(path)).build);}
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');Promise.all([qpgApi.get<{build:Build|null}>(path,c.signal),qpgApi.get<{enabled:boolean}>('questions/generation-config',c.signal)]).then(([r,a])=>{setBuild(r.build);setEnabled(a.enabled);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[path,revision]);
 useEffect(()=>{if(!active)return;const c=new AbortController();const timer=setInterval(()=>{qpgApi.get<{build:Build|null}>(path,c.signal).then(r=>setBuild(r.build)).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});},4000);return()=>{clearInterval(timer);c.abort();};},[active,path]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){const detail=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;setError(detail?.errors?`${detail.message} ${detail.errors.join(' ')}`:collegeError(e));}finally{setBusy(false);}}
 async function saveQuestion(p:Position,r:Candidate,edited:CandidateEdit){setActionCandidate(r.id);setEditNotice('');await qpgApi.save(`questions/generation-jobs/${p.job!.id}/results/${r.id}`,{expected_revision:p.job!.revision,...edited,...(r.question_version?{expected_question_version:r.question_version}:{})},true);setDraftPreview(null);setEditNotice(`Question ${p.label} saved to the AI draft. Faculty review is still required.`);await refresh();}
 async function acceptAll(){
  if(!build)return;
  setActionCandidate('');setBulkNotice('');setBulkFailures([]);
  const targets=build.positions.filter(p=>p.job?.status==='COMPLETED'&&p.job.results.some(r=>r.decision==='PENDING'));
  let accepted=0,processed=0;const failures:string[]=[];
  try{
   for(const p of targets){
    try{
     let job=await qpgApi.get<Job>(`questions/generation-jobs/${p.job!.id}`);
     for(const candidate of job.results.filter(r=>r.decision==='PENDING')){
      try{job=await qpgApi.save<Job>(`questions/generation-jobs/${job.id}/results/${candidate.id}/accept`,{expected_revision:job.revision});accepted++;}
      catch(e){failures.push(`Q${p.label}: ${collegeError(e)}`);}
     }
    }catch(e){failures.push(`Q${p.label}: ${collegeError(e)}`);}
    processed++;setBulkNotice(`Accepting for review: ${processed} / ${targets.length} positions checked · ${accepted} accepted.`);
   }
  }finally{
   setBulkNotice(`${accepted} question${accepted===1?'':'s'} accepted for faculty review. ${failures.length?`${failures.length} position(s) need attention.`:'Faculty approval is the next step.'}`);
   setBulkFailures(failures);setDraftPreview(null);await refresh();
  }
 }
 const pendingCount=build?.positions.reduce((total,p)=>total+(p.job?.status==='COMPLETED'?p.job.results.filter(r=>r.decision==='PENDING').length:0),0)||0;
 const completed=build?.positions.filter(p=>p.job?.status==='COMPLETED').length||0;
 const failed=build?.positions.filter(p=>['FAILED','CANCELLED'].includes(p.job?.status||'')).length||0;
 const approved=build?.positions.filter(p=>p.job?.results.some(r=>r.decision==='ACCEPTED'&&r.review_status==='APPROVED')).length||0;
 
 return <section aria-label="Build paper with AI" className="my-5 rounded-xl border border-indigo-200 bg-indigo-50/40 p-5 dark:border-indigo-900 dark:bg-indigo-950/20"><h3 className="text-lg font-semibold">Build Paper with AI</h3><p className="my-2 text-sm text-slate-600 dark:text-slate-300">Prepare the complete paper from its published syllabus and paper pattern, including every Part, OR alternative and subquestion. Existing selections stay in place.</p><div className="my-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border bg-white p-3 text-sm dark:bg-slate-900"><p className="font-semibold">Whole-paper structure</p><p className="mt-1 text-slate-500">Types, marks and question positions come from your paper pattern.</p></div><div className="rounded-lg border bg-white p-3 text-sm dark:bg-slate-900"><p className="font-semibold">Subject context</p><p className="mt-1 text-slate-500">Use the published syllabus, available reviewed material and approved question references.</p></div><div className="rounded-lg border bg-white p-3 text-sm dark:bg-slate-900"><p className="font-semibold">Complete draft and answers</p><p className="mt-1 text-slate-500">Preview in the university template, then complete faculty review.</p></div></div>
 {error&&<p role="alert" className="my-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {loading?<p role="status">Loading AI paper build…</p>:<>{!enabled&&<p className="my-3 text-sm text-amber-800">AI generation is unavailable. An administrator needs to enable it before preparing new questions.</p>}
 {!active&&(!build||build.stale||build.status==='CANCELLED'||emptyCount>0)&&<><p className="my-3 text-sm">{emptyCount?`${emptyCount} unfilled positions will be prepared automatically.`:'All positions are filled. Review the complete paper before submitting it.'}</p><details className="my-4 rounded-lg border bg-white p-4 dark:bg-slate-900"><summary className="cursor-pointer text-sm font-medium">Paper instructions and generation options</summary><label className="my-4 grid gap-2 text-sm">Instructions for the complete paper (optional)<textarea className={input} maxLength={1500} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="For example: balance theoretical and practical questions, use clear wording, and include worked solutions."/></label><label className="grid gap-2 text-sm">Reference material<select className={input} value={sourceMode} onChange={e=>setSourceMode(e.target.value)}><option value="SYLLABUS">Published syllabus + reviewed material when available</option><option value="REVIEWED_SOURCES">Require reviewed source citations for every new question</option></select></label><p className="my-2 text-xs text-slate-500">Syllabus-based questions can be generated without uploaded notes. Source citations are provided only where supporting material is available.</p><label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={reuseApproved} onChange={e=>setReuseApproved(e.target.checked)}/>Use matching approved questions automatically. Otherwise, generate new questions for every unfilled position.</label><label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={formatConfirmed} onChange={e=>setFormatConfirmed(e.target.checked)}/>I have checked suitability for any Long Answer or Case Study sections.</label></details><p className="mb-3 text-xs text-slate-500">The pattern’s exact requirements take priority. Unspecified Bloom and difficulty settings are suggested per position and require faculty review. New questions are not automatically approved.</p><Button disabled={busy||!enabled||!emptyCount} onClick={()=>setConfirm(true)}>Generate complete paper</Button></>}
 
 {build&&<div className="mt-5 border-t border-indigo-100 pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">{active?'Preparing your draft':build.status==='COMPLETED'?(failed?'Draft needs attention':'AI paper draft'):label(build.status)}</h4><span className="text-sm">{build.reused_count||0} approved questions reused · {completed} / {build.positions.length} new questions generated · {approved} new questions approved</span></div><progress className="my-3 h-2 w-full" aria-label="Question generation progress" max={build.total_positions||build.positions.length||1} value={(build.total_positions||build.positions.length)-build.positions.length+completed}/>{build.failure_reason&&<p role="alert" className="my-3 text-sm text-amber-800">{build.failure_reason}</p>}{build.stale&&<p role="alert" className="my-3 text-sm text-amber-800">The paper was saved or changed after generation. If its syllabus, pattern and selections are unchanged, continue with these generated questions. Structural changes require a new build.</p>}
 {build.stale&&build.status==='COMPLETED'&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{setBuild(await qpgApi.save<Build>(`${path}/${build.id}/rebase`,{expected_revision:build.revision,expected_paper_revision:revision}));})}>Continue with generated questions</Button>}
 {active&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{setBuild(await qpgApi.save<Build>(`${path}/${build.id}/cancel`,{expected_revision:build.revision}));})}>Stop build</Button>}
 {!active&&!build.stale&&['COMPLETED','FAILED'].includes(build.status)&&<div className="my-4 flex flex-wrap gap-2">{build.status==='COMPLETED'&&build.positions.some(p=>p.job?.results.some(r=>['PENDING','ACCEPTED'].includes(r.decision)))&&<Button variant="outline" disabled={busy} onClick={()=>{setEditNotice('');setEditPaper(true);}}>Edit paper draft</Button>}{(failed>0||completed<build.positions.length)&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{setBuild(await qpgApi.save<Build>(`${path}/${build.id}/retry`,{expected_revision:build.revision}));})}>Retry unfinished positions</Button>}<Button type="button" disabled={busy||build.status!=='COMPLETED'||!pendingCount} onClick={()=>void run(acceptAll)}>{busy&&bulkNotice?'Accepting…':`Accept all for review (${pendingCount})`}</Button><Button variant="outline" disabled={busy} onClick={onReview}>Open faculty review</Button><Button disabled={busy||build.status!=='COMPLETED'||approved!==build.positions.length} onClick={()=>void run(async()=>{await qpgApi.save(`${path}/${build.id}/assemble`,{expected_revision:build.revision,expected_paper_revision:revision,format_confirmed:formatConfirmed});await onAssembled();})}>Assemble approved questions</Button></div>}
 {bulkNotice&&<p role="status" className="my-3 rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">{bulkNotice}</p>}{bulkFailures.length>0&&<div role="alert" className="my-3 rounded-lg bg-red-50 p-3 text-sm text-red-700"><p className="font-medium">These questions were not accepted. Edit or regenerate them, then try again.</p><ul className="mt-2 list-disc pl-5">{bulkFailures.map((message,i)=><li key={i}>{message}</li>)}</ul></div>}{!active&&!build.stale&&<><p className="my-3 text-sm text-slate-600 dark:text-slate-300">Accept candidates below, approve them in faculty review, then return here to assemble the approved questions. The complete paper still needs faculty approval before locking.</p><label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={formatConfirmed} onChange={e=>setFormatConfirmed(e.target.checked)}/>I have checked that descriptive questions suit any Long Answer or Case Study sections.</label><Button variant="ghost" disabled={busy} onClick={()=>void run(refresh)}>Refresh review progress</Button></>}
 {!build.stale&&<div className="my-4 flex flex-wrap items-end gap-2"><label className="text-sm">Preview template<select className={input} value={previewTemplate} disabled={busy} onChange={e=>{setPreviewTemplate(e.target.value);setDraftPreview(null);}}><option value="university">University Exam Template</option><option value="default">Institution Template</option></select></label>{(['STUDENT','ANSWER'] as const).map(kind=><Button key={kind} variant="outline" disabled={busy} onClick={()=>void run(async()=>setDraftPreview((await qpgApi.get<{render_model:RenderModel}>(`${path}/${build.id}/preview?document_type=${kind}&template_id=${previewTemplate}`)).render_model))}>{kind==='STUDENT'?'Preview complete draft':'Preview draft answers'}</Button>)}</div>}
 <div className="mt-4 space-y-3">{build.positions.map(p=><details key={p.item_id} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><summary className="cursor-pointer text-sm font-medium">Q{p.label} · {p.section} · {p.request.marks} marks · {p.job?label(p.job.status):'Waiting'}</summary><p className="my-3 text-xs text-slate-500">{label(p.request.question_type)} · {label(p.request.bloom_level)} · {label(p.request.difficulty)} · {syllabus.cos.find(x=>x.id===p.request.co_id)?.code} · {syllabus.topics.find(x=>x.id===p.request.topic_id)?.title}</p>{p.job?.failure_reason&&<p role="alert" className="my-3 text-sm text-red-700">{p.job.failure_reason}</p>}{p.job?.results.map(r=><Result key={p.job!.id+r.id} candidate={r} actionError={actionCandidate===r.id?error:undefined} actionNotice={actionCandidate===r.id?editNotice:undefined} saveDraft={edited=>void run(()=>saveQuestion(p,r,edited))} editable={!active&&!build.stale&&build.status==='COMPLETED'&&['PENDING','ACCEPTED'].includes(r.decision)} busy={busy} decide={(accept,edited)=>void run(async()=>{setActionCandidate(r.id);setEditNotice('');await qpgApi.save(`questions/generation-jobs/${p.job!.id}/results/${r.id}/${accept?'accept':'reject'}`,{expected_revision:p.job!.revision,...(accept?edited:{})});setEditNotice(accept?`Q${p.label} saved to the Question Bank. Faculty approval is the next step.`:`Q${p.label} rejected.`);await refresh();})}/>)}{!active&&!build.stale&&build.status==='COMPLETED'&&!p.job?.results.some(r=>r.decision==='ACCEPTED')&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{setBuild(await qpgApi.save<Build>(`${path}/${build.id}/positions/${p.item_id}/regenerate`,{expected_revision:build.revision}));})}>Regenerate this question</Button>}</details>)}</div></div>}
 </>}
 {editPaper&&build&&<Dialog title="Edit AI paper draft" onClose={()=>setEditPaper(false)}><p className="my-3 text-sm">Edit question wording, answers, MCQ options and marking points. Save each question before closing. The paper pattern controls marks, types and exact mappings. Saved questions are editable here too. Changing a saved question creates a new version and requires faculty approval again.</p>{editNotice&&<p role="status" className="my-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{editNotice}</p>}{error&&<p role="alert" className="my-3 text-sm text-red-700">{error}</p>}{build.positions.map(p=><section key={p.item_id} className="my-4"><h4 className="font-semibold">Q{p.label} · {p.section} · {p.request.marks} marks</h4>{p.job?.results.filter(r=>['PENDING','ACCEPTED'].includes(r.decision)).map(r=><Result key={p.item_id+r.id} candidate={r} actionError={actionCandidate===r.id?error:undefined} actionNotice={actionCandidate===r.id?editNotice:undefined} forceEditing editable={!active&&!build.stale} busy={busy} saveDraft={edited=>void run(()=>saveQuestion(p,r,edited))} decide={(accept,edited)=>void run(async()=>{setActionCandidate(r.id);setEditNotice('');await qpgApi.save(`questions/generation-jobs/${p.job!.id}/results/${r.id}/${accept?'accept':'reject'}`,{expected_revision:p.job!.revision,...(accept?edited:{})});setEditNotice(accept?`Q${p.label} saved to the Question Bank. Faculty approval is the next step.`:`Q${p.label} rejected.`);setDraftPreview(null);await refresh();})}/>)}{!p.job?.results.some(r=>['PENDING','ACCEPTED'].includes(r.decision))&&<p className="my-2 text-sm text-slate-500">No editable candidate is available for this position.</p>}</section>)}<Button variant="outline" disabled={busy} onClick={()=>setEditPaper(false)}>Done editing</Button></Dialog>}
 {draftPreview&&<Dialog title="AI Draft Preview" onClose={()=>setDraftPreview(null)}><p className="my-3 text-sm">Selected paper template. Faculty approval and locking are required before official PDF/DOCX download.</p><QpgRenderPreview model={draftPreview}/></Dialog>}
 {confirm&&<Dialog title="Generate the complete paper?" onClose={()=>setConfirm(false)}><p className="my-3 text-sm">This prepares all {emptyCount} unfilled positions in one build. By default, new questions are generated for every unfilled position using the syllabus, reviewed material and paper pattern. Approved questions are reused only if you enable that option. New generation uses the paid AI service and may take several minutes. You will review the complete draft and answers before approval.</p><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setConfirm(false)}>Cancel</Button><Button disabled={busy} onClick={()=>void run(async()=>{setBuild(await qpgApi.save<Build>(path,{expected_revision:revision,whole_paper:true,reuse_approved:reuseApproved,format_confirmed:formatConfirmed,instructions,conceptual:sourceMode==='SYLLABUS'}));setConfirm(false);await onAssembled();})}>Generate complete paper</Button></div></Dialog>}
 </section>;
}
