import Dialog from './QpgDialog';
import {useEffect,useRef,useState} from 'react';
import QpgHierarchyEditor from './QpgHierarchyEditor';
import type {MainQuestion} from './QpgHierarchyEditor';
import {Button} from '@/components/ui/button';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,questionTypes,blooms,difficulties,label} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
type Amount=number|string;
type Group={id:string;name:string;offered:number;choose:number};
type Section={main_questions?:MainQuestion[];id:string;name:string;order:number;offered:number;attempted:number;marks_each:Amount;question_type:string|null;format:string;mandatory:boolean;choice_groups:Group[];time_minutes:number|null};
type Target={id:string;marks:Amount;unit_id?:string};
type Percent={level:string;percent:Amount};
type Coverage={cos:Target[];units:Target[];topics:Target[];bloom:Percent[];difficulty:Percent[]};
type Config={title:string;total_marks:Amount;duration_minutes:number;sections:Section[];coverage:Coverage};
type Validation={sections?:{id:string;offered_marks:string;attempted_marks:string}[];valid:boolean;errors:string[];offered_marks:string;attempted_marks:string;checks:string[]};
type Blueprint={id:string;family_id:string;version:number;revision:number;status:string;syllabus_version_id:string;config:Config;validation:Validation;created_by:string;published_by:string|null};
type Syllabus={id:string;version:number;status:string;content:{cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]}};
const input='w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
const newSection=(order:number):Section=>({id:crypto.randomUUID(),name:`Section ${order}`,order,offered:1,attempted:1,marks_each:1,question_type:null,format:'STANDARD',mandatory:true,choice_groups:[],time_minutes:null});
const blank=():Config=>({title:'',total_marks:30,duration_minutes:60,sections:[newSection(1)],coverage:{cos:[],units:[],topics:[],bloom:[],difficulty:[]}});
function universityPattern(kind:string):Config {
 const alternative=kind==='two-parts';
 const nested=kind==='six-five';
 const section=(order:number,name:string,count:number,marks:number,type:string):Section=>({...newSection(order),name,offered:count,attempted:count,marks_each:marks,question_type:type});
 const final=section(alternative?2:3,alternative?'Part B':'Part C',alternative?5:6,alternative?16:11,'DESCRIPTIVE');
 final.main_questions=Array.from({length:alternative?5:6},(_,i)=>({id:crypto.randomUUID(),marks:alternative?16:11,choose:1,branches:['a','b'].map((branch)=>({id:crypto.randomUUID(),marks:alternative?16:11,children:(nested&&i===5?[6,5]:alternative&&branch==='b'&&(i===1||i===2)?[8,8]:alternative&&branch==='b'&&i===3?[12,4]:[]).map(marks=>({id:crypto.randomUUID(),marks}))}))}));
 return {title:alternative?'100 marks · Two Parts':nested?'100 marks · Three Parts with 6 + 5':'100 marks · Three Parts',total_marks:100,duration_minutes:180,coverage:{cos:[],units:[],topics:[],bloom:[],difficulty:[]},sections:[section(1,alternative?'Part A':'Part A (MCQ)',10,alternative?2:1,alternative?'SHORT_ANSWER':'MCQ'),...(!alternative?[section(2,'Part B',12,2,'SHORT_ANSWER')]:[]),final]};
}
export default function QpgBlueprintPanel({subject,onSyllabus}:{subject:Subject;onSyllabus?:()=>void}){
 const pinSequence=useRef(0);
 const [pendingPattern,setPendingPattern]=useState<{key:string;title:string}|null>(null);
 const [patternNotice,setPatternNotice]=useState('');
 function applyPattern(key:string,title:string){edit(universityPattern(key));setError('');setErrors([]);setPendingPattern(null);setPatternNotice(`${title} applied. Check the sections, then save the draft.`);}
 const [syllabuses,setSyllabuses]=useState<Syllabus[]>([]);const [rows,setRows]=useState<Blueprint[]>([]);const [history,setHistory]=useState<Blueprint[]>([]);
 const [selected,setSelected]=useState<Blueprint|null>(null);const [pin,setPin]=useState('');const [snapshot,setSnapshot]=useState<Syllabus|null>(null);
 const [config,setConfig]=useState<Config>(blank);const [error,setError]=useState('');const [errors,setErrors]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [canWrite,setCanWrite]=useState(false);const [dirty,setDirty]=useState(true);
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Syllabus[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`,c.signal),qpgApi.get<{can_write:boolean}>('academic-options',c.signal)]).then(([s,b,a])=>{setSyllabuses(s.items);setRows(b.items);setCanWrite(a.can_write);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[subject.id]);
 const editable=canWrite&&(!selected||['DRAFT','VALIDATED'].includes(selected.status));
 async function loadPin(id:string){const sequence=++pinSequence.current;setPin(id);setSnapshot(null);if(id)try{const next=await qpgApi.get<Syllabus>(`subjects/${subject.id}/syllabus/versions/${id}`);if(sequence===pinSequence.current)setSnapshot(next);}catch(e){if(sequence===pinSequence.current)setError(collegeError(e));}}

 function edit(next:Config){setConfig(next);setDirty(true);}
 function section(index:number,patch:Partial<Section>){edit({...config,sections:config.sections.map((s,i)=>i===index?{...s,...patch,...(patch.marks_each!==undefined&&s.main_questions?.length?{main_questions:s.main_questions.map(m=>({...m,marks:patch.marks_each!,branches:m.branches.map(b=>({...b,marks:patch.marks_each!}))}))}:{})}:s)});}
 async function open(id:string){await received(await qpgApi.get<Blueprint>(`blueprints/${id}`));}
 async function received(next:Blueprint){setSelected(next);setConfig(next.config);setDirty(false);await loadPin(next.syllabus_version_id);setHistory((await qpgApi.get<{items:Blueprint[]}>(`blueprints/${next.id}/versions`)).items);setRows((await qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`)).items);}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setErrors([]);try{await work();}catch(e){const detail=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;if(detail?.errors){setError(detail.message||'Blueprint validation failed.');setErrors(detail.errors);}else setError(collegeError(e));}finally{setBusy(false);}}
 async function persist(){const body=selected?{config,expected_revision:selected.revision}:{subject_id:subject.id,syllabus_version_id:pin,config};const next=await qpgApi.save<Blueprint>(selected?`blueprints/${selected.id}`:'blueprints',body,Boolean(selected));await received(next);return next;}
 async function operation(action:string){await run(async()=>{const target=dirty?await persist():selected;if(!target)return;await received(await qpgApi.save<Blueprint>(`blueprints/${target.id}/${action}`,{expected_revision:target.revision}));});}
 function move(index:number,direction:number){const sections=[...config.sections];[sections[index],sections[index+direction]]=[sections[index+direction],sections[index]];edit({...config,sections:sections.map((s,i)=>({...s,order:i+1}))});}
 function coverage(kind:keyof Coverage,values:Target[]|Percent[]){edit({...config,coverage:{...config.coverage,[kind]:values}});}
 return <section className="erp-card" aria-label="Subject blueprint"><h2>Paper Pattern · {subject.code} · {subject.name}</h2><p className="mb-4 text-sm text-slate-500">Choose a starting pattern, then adjust its Parts and marks. Students answer one alternative in each OR pair.</p>
 {error&&<div role="alert" className="my-3 text-red-700"><p>{error}</p><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
 <div className="mb-6 flex flex-wrap gap-2">{canWrite&&<Button variant="outline" disabled={busy} onClick={()=>{pinSequence.current++;setSelected(null);setConfig(blank());setPin('');setSnapshot(null);setHistory([]);setDirty(true);}}>New Paper Pattern</Button>}{rows.map(row=><Button key={row.id} variant="outline" size="sm" disabled={busy} onClick={()=>void run(()=>open(row.id))}>{row.config.title} · v{row.version} · {label(row.status)}</Button>)}</div>
 <div className="mb-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Published syllabus<select aria-label="Published syllabus" className={input} value={pin} disabled={busy||Boolean(selected)||!canWrite} onChange={e=>{void loadPin(e.target.value);edit({...config,coverage:{cos:[],units:[],topics:[],bloom:[],difficulty:[]}});}}><option value="">Select published syllabus</option>{syllabuses.filter(s=>s.status==='PUBLISHED'||s.id===pin).map(s=><option key={s.id} value={s.id}>{subject.name} ({subject.code}) — Version {s.version} · {label(s.status)}</option>)}</select></label><label className="grid gap-2 text-sm">Paper Pattern name<input aria-label="Blueprint name" className={input} value={config.title} disabled={!editable||busy} onChange={e=>edit({...config,title:e.target.value})}/></label><NumberField title="Marks students must answer" value={config.total_marks} disabled={!editable||busy} onChange={v=>edit({...config,total_marks:v})}/><NumberField title="Duration (minutes)" value={config.duration_minutes} disabled={!editable||busy} onChange={v=>edit({...config,duration_minutes:v})}/></div>
 {selected&&<p className="mb-4 text-sm">Blueprint v{selected.version} · {label(selected.status)}{dirty?' · Unsaved changes':''}</p>}
 {!syllabuses.some(s=>s.status==='PUBLISHED')&&!selected&&<div role="status" className="my-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Publish this subject’s syllabus first</p><p className="mt-1">You can explore starting patterns, but saving requires a published syllabus.</p><Button variant="outline" className="mt-3" onClick={onSyllabus} disabled={!onSyllabus}>Open Syllabus Master</Button></div>}
 {patternNotice&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{patternNotice}</p>}
 {!selected&&editable&&<section className="mb-5 rounded-xl bg-indigo-50 p-4 dark:bg-indigo-950"><h3 className="font-semibold">Start with a university pattern</h3><p className="my-2 text-sm">These create an editable draft. Select your syllabus, check the Parts, then save and publish. No questions are added automatically.</p><div className="flex flex-wrap gap-2">{[['three-parts','Three Parts: 10 × 1, 12 × 2, 6 × 11'],['six-five','Three Parts with 6 + 5 subquestions'],['two-parts','Two Parts: 10 × 2, 5 × 16']].map(([key,title])=><Button key={key} variant="outline" disabled={busy} onClick={()=>{if(config.title){setPendingPattern({key,title});return;}applyPattern(key,title);}}>{title}</Button>)}</div><p className="mt-2 text-xs">All patterns: 100 attempted marks, 3 hours. Configure any additional child marks and syllabus coverage below.</p></section>}
 {config.sections.map((s,i)=><section key={s.id} className="mb-4 rounded-xl border border-slate-200 p-4" aria-label={`Blueprint section ${i+1}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{s.name}</h3>{editable&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy||i===0} onClick={()=>move(i,-1)} aria-label={`Move section ${i+1} up`}>↑</Button><Button size="sm" variant="outline" disabled={busy||i===config.sections.length-1} onClick={()=>move(i,1)} aria-label={`Move section ${i+1} down`}>↓</Button><Button size="sm" variant="ghost" disabled={busy||config.sections.length===1} onClick={()=>edit({...config,sections:config.sections.filter((_,j)=>j!==i).map((v,j)=>({...v,order:j+1}))})}>Remove section</Button></div>}</div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="grid gap-2 text-sm">Section name<input aria-label="Section name" className={input} value={s.name} disabled={!editable||busy} onChange={e=>section(i,{name:e.target.value})}/></label><NumberField title={s.main_questions?.length?'Main questions':'Questions offered'} value={s.offered} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={v=>section(i,{offered:v})}/><NumberField title={s.main_questions?.length?'Main questions to answer':'Questions attempted'} value={s.attempted} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={v=>section(i,{attempted:v})}/><NumberField title="Marks each" value={s.marks_each} disabled={!editable||busy} onChange={v=>section(i,{marks_each:v})}/><NumberField title="Time allocation (minutes)" value={s.time_minutes??''} disabled={!editable||busy} onChange={v=>section(i,{time_minutes:v||null})}/><label className="grid gap-2 text-sm">Question type<select aria-label="Blueprint question type" className={input} value={s.format==='STANDARD'?(s.question_type||'ANY'):s.format} disabled={!editable||busy} onChange={e=>{const v=e.target.value;section(i,v==='LONG_ANSWER'||v==='CASE_STUDY'?{question_type:'DESCRIPTIVE',format:v}:{question_type:v==='ANY'?null:v,format:'STANDARD'});}}><option value="ANY">Mixed / Any</option>{questionTypes.map(t=><option key={t} value={t}>{label(t)}</option>)}<option value="LONG_ANSWER">Long Answer</option><option value="CASE_STUDY">Case Study</option></select></label></div>
 {!s.main_questions?.length&&<label className="my-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={s.mandatory} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={e=>section(i,{mandatory:e.target.checked})}/>Students answer all questions in this Part</label>}<p className="text-xs text-slate-500">{s.main_questions?.length?`${s.main_questions.length} compulsory main questions · ${s.main_questions.reduce((n,m)=>n+m.branches.length,0)} offered alternatives. Answer one alternative per main question.`:'Students answer the configured number of questions. Use advanced options only when this Part needs a choice rule.'}</p>
 {selected?.validation?.sections?.find(value=>value.id===s.id)&&<p className="my-3 text-sm">Saved Offered Marks: {selected.validation.sections.find(value=>value.id===s.id)?.offered_marks} · Saved Attempted Marks: {selected.validation.sections.find(value=>value.id===s.id)?.attempted_marks}{dirty?' · Save to update':''}</p>}
 {(!s.main_questions?.length)&&<details className="my-4 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Advanced: add OR alternatives or sub-questions</summary><QpgHierarchyEditor mains={[]} marks={s.marks_each} disabled={!editable||busy} syllabus={snapshot?.content} onChange={mains=>section(i,{main_questions:mains,...(mains.length?{offered:mains.length,attempted:mains.length,mandatory:true,choice_groups:[]}:{})})}/></details>}
 {Boolean(s.main_questions?.length)&&<QpgHierarchyEditor mains={s.main_questions||[]} marks={s.marks_each} disabled={!editable||busy} syllabus={snapshot?.content} onChange={mains=>section(i,{main_questions:mains,...(mains.length?{offered:mains.length,attempted:mains.length,mandatory:true,choice_groups:[]}:{})})}/>}
 {!s.main_questions?.length&&<details className="my-3 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Advanced: answer any N / choice groups</summary><h4 className="my-3 text-sm font-semibold">Internal choice groups</h4>{s.choice_groups.map((g,j)=><div key={g.id} className="mb-3 grid gap-3 sm:grid-cols-4"><label className="grid gap-2 text-sm">Group name<input className={input} value={g.name} disabled={!editable||busy} onChange={e=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,name:e.target.value}:x)})}/></label><NumberField title="Group offered" value={g.offered} disabled={!editable||busy} onChange={v=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,offered:v}:x)})}/><NumberField title="Group choose" value={g.choose} disabled={!editable||busy} onChange={v=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,choose:v}:x)})}/>{editable&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>section(i,{choice_groups:s.choice_groups.filter((_,k)=>k!==j)})}>Remove group</Button>}</div>)}{editable&&<Button variant="outline" size="sm" disabled={busy||Boolean(s.main_questions?.length)} onClick={()=>section(i,{mandatory:false,choice_groups:[...s.choice_groups,{id:crypto.randomUUID(),name:`Group ${s.choice_groups.length+1}`,offered:2,choose:1}]})}>Add choice group</Button>}</details>}
 </section>)}{editable&&<Button variant="outline" className="mb-6" disabled={busy||config.sections.length>=20} onClick={()=>edit({...config,sections:[...config.sections,newSection(config.sections.length+1)]})}>Add section</Button>}
 {snapshot&&<details className="mb-6 rounded-xl border p-4"><summary className="mb-3 cursor-pointer font-semibold">Advanced: syllabus coverage and Bloom targets</summary><section><h3 className="mb-3 font-semibold">Coverage from syllabus v{snapshot.version}</h3><p className="mb-3 text-sm text-slate-500">Each configured CO/Unit distribution totals final attempted marks. Topic targets are optional minimum coverage within Unit budgets. Bloom and Difficulty each total 100% when configured.</p>{(['cos','units','topics'] as const).map(kind=><AcademicCoverage key={kind} kind={kind} values={config.coverage[kind]} items={snapshot.content[kind]} units={snapshot.content.units} disabled={!editable||busy} onChange={values=>coverage(kind,values)}/>)}<PercentageCoverage title="Bloom" levels={blooms} values={config.coverage.bloom} disabled={!editable||busy} onChange={v=>coverage('bloom',v)}/><PercentageCoverage title="Difficulty" levels={difficulties} values={config.coverage.difficulty} disabled={!editable||busy} onChange={v=>coverage('difficulty',v)}/></section></details>}
 <div className="my-4 flex flex-wrap gap-2">{editable&&<><Button disabled={busy||!pin||!config.title.trim()} onClick={()=>void run(async()=>{await persist();})}>Save Draft</Button><Button variant="outline" disabled={busy||!pin||!config.title.trim()} onClick={()=>void operation('validate')}>Check Pattern</Button><Button disabled={busy||dirty||selected?.status!=='VALIDATED'} onClick={()=>void operation('publish')}>Publish Paper Pattern</Button></>}{canWrite&&selected&&['PUBLISHED','ARCHIVED'].includes(selected.status)&&<Button disabled={busy} onClick={()=>void operation('draft')}>Create new draft version</Button>}{canWrite&&selected?.status==='PUBLISHED'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Archive this published blueprint? Its history remains available.'))void operation('archive');}}>Archive Blueprint</Button>}</div>
 {selected?.validation?.offered_marks&&<section role="status" className="my-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><p><strong>Offered Marks: {selected.validation.offered_marks}</strong></p><p><strong>Attempted Marks: {selected.validation.attempted_marks}</strong></p>{dirty?<p>Saved totals shown. Save and validate your changes for updated totals.</p>:<>{selected.validation.checks?.map(c=><p key={c}>✓ {c}</p>)}{selected.validation.errors?.map(e=><p key={e} className="text-red-700">{e}</p>)}</>}</section>}
 {pendingPattern&&<Dialog title="Change starting pattern" onClose={()=>setPendingPattern(null)}><p className="mb-4 text-sm text-slate-600">This will replace the current unsaved sections and coverage settings. Your selected subject and published syllabus stay selected.</p><div className="mb-5 grid gap-3 rounded-xl border bg-slate-50 p-4 text-sm"><p><span className="text-slate-500">Current pattern</span><br/><strong>{config.title}</strong></p><p><span className="text-slate-500">New pattern</span><br/><strong>{pendingPattern.title}</strong></p><p>100 attempted marks · 180 minutes</p></div><div className="flex flex-wrap justify-between gap-3"><Button variant="outline" onClick={()=>setPendingPattern(null)}>Keep current pattern</Button><Button onClick={()=>applyPattern(pendingPattern.key,pendingPattern.title)}>Use selected pattern</Button></div></Dialog>}
 {history.length>0&&<section><h3 className="mb-3 font-semibold">Blueprint versions</h3>{history.map(v=><Button key={v.id} size="sm" variant="outline" className="mr-2 mb-2" disabled={busy} onClick={()=>void run(()=>open(v.id))}>View blueprint v{v.version} · {label(v.status)}</Button>)}</section>}
 </section>;
}
function NumberField({title,value,disabled,onChange}:{title:string;value:Amount;disabled:boolean;onChange:(value:number)=>void}){return <label className="grid gap-2 text-sm">{title}<input aria-label={title} type="number" min={title.toLowerCase().includes('mark')?'0.01':'1'} step={title.toLowerCase().includes('mark')?'0.01':'1'} className={input} value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/></label>;}
function AcademicCoverage({kind,values,items,units,disabled,onChange}:{kind:string;values:Target[];items:SyllabusItem[];units:SyllabusItem[];disabled:boolean;onChange:(values:Target[])=>void}){
 return <fieldset className="mb-4"><legend className="mb-2 text-sm font-semibold">{kind==='cos'?'CO':label(kind)} distribution (marks)</legend>{items.map(item=>{const target=values.find(v=>v.id===item.id);return <div key={item.id} className="mb-2 grid items-center gap-2 sm:grid-cols-2"><p className="text-sm">{item.code} · {item.title}{item.unit_id?` · ${units.find(u=>u.id===item.unit_id)?.code}`:''}</p><input type="number" min="0" step="0.01" aria-label={`${kind} ${item.code} marks`} className={input} disabled={disabled} value={target?.marks??''} placeholder="Unconstrained" onChange={e=>{const remaining=values.filter(v=>v.id!==item.id);onChange(e.target.value?[...remaining,{id:item.id,marks:Number(e.target.value),...(kind==='topics'?{unit_id:item.unit_id}:{})}]:remaining);}}/></div>;})}</fieldset>;
}
function PercentageCoverage({title,levels,values,disabled,onChange}:{title:string;levels:string[];values:Percent[];disabled:boolean;onChange:(values:Percent[])=>void}){return <fieldset className="mb-4"><legend className="mb-2 text-sm font-semibold">{title} distribution (%)</legend><div className="grid gap-3 sm:grid-cols-3">{levels.map(level=><label key={level} className="grid gap-2 text-sm">{label(level)}<input aria-label={`${title} ${level} percent`} type="number" min="0" max="100" step="0.01" className={input} disabled={disabled} value={values.find(v=>v.level===level)?.percent??''} placeholder="Unconstrained" onChange={e=>{const rest=values.filter(v=>v.level!==level);onChange(e.target.value?[...rest,{level,percent:Number(e.target.value)}]:rest);}}/></label>)}</div></fieldset>;}
