import {useEffect,useRef,useState} from 'react';
import QpgHierarchyEditor from './QpgHierarchyEditor';
import type {MainQuestion} from './QpgHierarchyEditor';
import {Button} from '@/components/ui/button';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,questionTypes,blooms,difficulties,label} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
type Amount=number|string;
type Group={id:string;name:string;offered:number;choose:number};
type Section={main_questions?:MainQuestion[];id:string;name:string;order:number;offered:number;attempted:number;marks_each:Amount;question_type:string|null;format:string;mandatory:boolean;choice_groups:Group[];time_minutes:number|null};
type Target={id:string;marks:Amount;unit_id?:string};
type Percent={level:string;percent:Amount};
type Coverage={cos:Target[];units:Target[];topics:Target[];bloom:Percent[];difficulty:Percent[]};
type Config={title:string;total_marks:Amount;duration_minutes:number;sections:Section[];coverage:Coverage};
type Validation={sections?:{id:string;offered_marks:string;attempted_marks:string}[];valid:boolean;errors:string[];offered_marks:string;attempted_marks:string;checks:string[]};
type Blueprint={id:string;family_id:string;version:number;revision:number;status:string;syllabus_version_id:string;config:Config;validation:Validation;created_by:string;published_by:string|null};
type Syllabus={id:string;version:number;status:string;content:{cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]}};
const input='w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
const newSection=(order:number):Section=>({id:crypto.randomUUID(),name:`Section ${order}`,order,offered:1,attempted:1,marks_each:1,question_type:null,format:'STANDARD',mandatory:true,choice_groups:[],time_minutes:null});
const blank=():Config=>({title:'',total_marks:30,duration_minutes:60,sections:[newSection(1)],coverage:{cos:[],units:[],topics:[],bloom:[],difficulty:[]}});
export default function QpgBlueprintPanel({subject}:{subject:Subject}){
 const pinSequence=useRef(0);
 const [syllabuses,setSyllabuses]=useState<Syllabus[]>([]);const [rows,setRows]=useState<Blueprint[]>([]);const [history,setHistory]=useState<Blueprint[]>([]);
 const [selected,setSelected]=useState<Blueprint|null>(null);const [pin,setPin]=useState('');const [snapshot,setSnapshot]=useState<Syllabus|null>(null);
 const [config,setConfig]=useState<Config>(blank);const [error,setError]=useState('');const [errors,setErrors]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [canWrite,setCanWrite]=useState(false);const [dirty,setDirty]=useState(true);
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Syllabus[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`,c.signal),qpgApi.get<{can_write:boolean}>('academic-options',c.signal)]).then(([s,b,a])=>{setSyllabuses(s.items);setRows(b.items);setCanWrite(a.can_write);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[subject.id]);
 const editable=canWrite&&(!selected||['DRAFT','VALIDATED'].includes(selected.status));
 async function loadPin(id:string){const sequence=++pinSequence.current;setPin(id);setSnapshot(null);if(id)try{const next=await qpgApi.get<Syllabus>(`subjects/${subject.id}/syllabus/versions/${id}`);if(sequence===pinSequence.current)setSnapshot(next);}catch(e){if(sequence===pinSequence.current)setError(collegeError(e));}}

 function edit(next:Config){setConfig(next);setDirty(true);}
 function section(index:number,patch:Partial<Section>){edit({...config,sections:config.sections.map((s,i)=>i===index?{...s,...patch,...(patch.marks_each!==undefined&&s.main_questions?.length?{main_questions:s.main_questions.map(m=>({...m,marks:patch.marks_each!,branches:m.branches.map(b=>({...b,marks:patch.marks_each!}))}))}:{})}:s)});}
 async function open(id:string){await received(await qpgApi.get<Blueprint>(`blueprints/${id}`));}
 async function received(next:Blueprint){setSelected(next);setConfig(next.config);setDirty(false);await loadPin(next.syllabus_version_id);setHistory((await qpgApi.get<{items:Blueprint[]}>(`blueprints/${next.id}/versions`)).items);setRows((await qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`)).items);}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setErrors([]);try{await work();}catch(e){const detail=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;if(detail?.errors){setError(detail.message||'Blueprint validation failed.');setErrors(detail.errors);}else setError(collegeError(e));}finally{setBusy(false);}}
 async function persist(){const body=selected?{config,expected_revision:selected.revision}:{subject_id:subject.id,syllabus_version_id:pin,config};const next=await qpgApi.save<Blueprint>(selected?`blueprints/${selected.id}`:'blueprints',body,Boolean(selected));await received(next);return next;}
 async function operation(action:string){await run(async()=>{const target=dirty?await persist():selected;if(!target)return;await received(await qpgApi.save<Blueprint>(`blueprints/${target.id}/${action}`,{expected_revision:target.revision}));});}
 function move(index:number,direction:number){const sections=[...config.sections];[sections[index],sections[index+direction]]=[sections[index+direction],sections[index]];edit({...config,sections:sections.map((s,i)=>({...s,order:i+1}))});}
 function coverage(kind:keyof Coverage,values:Target[]|Percent[]){edit({...config,coverage:{...config.coverage,[kind]:values}});}
 return <section className="erp-card" aria-label="Subject blueprint"><h2>Paper Pattern / Blueprint · {subject.code} · {subject.name}</h2><p className="mb-4 text-sm text-slate-500">Define paper constraints against a published syllabus. Final marks use questions attempted.</p>
 {error&&<div role="alert" className="my-3 text-red-700"><p>{error}</p><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
 <div className="mb-6 flex flex-wrap gap-2">{canWrite&&<Button variant="outline" disabled={busy} onClick={()=>{pinSequence.current++;setSelected(null);setConfig(blank());setPin('');setSnapshot(null);setHistory([]);setDirty(true);}}>New Paper Pattern</Button>}{rows.map(row=><Button key={row.id} variant="outline" size="sm" disabled={busy} onClick={()=>void run(()=>open(row.id))}>{row.config.title} · v{row.version} · {label(row.status)}</Button>)}</div>
 <div className="mb-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Published syllabus<select aria-label="Published syllabus" className={input} value={pin} disabled={busy||Boolean(selected)||!canWrite} onChange={e=>{void loadPin(e.target.value);edit({...config,coverage:{cos:[],units:[],topics:[],bloom:[],difficulty:[]}});}}><option value="">Select published syllabus</option>{syllabuses.filter(s=>s.status==='PUBLISHED'||s.id===pin).map(s=><option key={s.id} value={s.id}>Version {s.version} · {label(s.status)}</option>)}</select></label><label className="grid gap-2 text-sm">Paper Pattern name<input aria-label="Blueprint name" className={input} value={config.title} disabled={!editable||busy} onChange={e=>edit({...config,title:e.target.value})}/></label><NumberField title="Final attempted marks" value={config.total_marks} disabled={!editable||busy} onChange={v=>edit({...config,total_marks:v})}/><NumberField title="Duration (minutes)" value={config.duration_minutes} disabled={!editable||busy} onChange={v=>edit({...config,duration_minutes:v})}/></div>
 {selected&&<p className="mb-4 text-sm">Blueprint v{selected.version} · {label(selected.status)}{dirty?' · Unsaved changes':''}</p>}
 {!syllabuses.some(s=>s.status==='PUBLISHED')&&!selected&&<p className="my-4 text-sm text-slate-500">Publish a subject syllabus before creating a blueprint.</p>}
 {config.sections.map((s,i)=><section key={s.id} className="mb-4 rounded-xl border border-slate-200 p-4" aria-label={`Blueprint section ${i+1}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{s.name}</h3>{editable&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy||i===0} onClick={()=>move(i,-1)} aria-label={`Move section ${i+1} up`}>↑</Button><Button size="sm" variant="outline" disabled={busy||i===config.sections.length-1} onClick={()=>move(i,1)} aria-label={`Move section ${i+1} down`}>↓</Button><Button size="sm" variant="ghost" disabled={busy||config.sections.length===1} onClick={()=>edit({...config,sections:config.sections.filter((_,j)=>j!==i).map((v,j)=>({...v,order:j+1}))})}>Remove section</Button></div>}</div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="grid gap-2 text-sm">Section name<input aria-label="Section name" className={input} value={s.name} disabled={!editable||busy} onChange={e=>section(i,{name:e.target.value})}/></label><NumberField title="Questions offered" value={s.offered} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={v=>section(i,{offered:v})}/><NumberField title="Questions attempted" value={s.attempted} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={v=>section(i,{attempted:v})}/><NumberField title="Marks each" value={s.marks_each} disabled={!editable||busy} onChange={v=>section(i,{marks_each:v})}/><NumberField title="Time allocation (minutes)" value={s.time_minutes??''} disabled={!editable||busy} onChange={v=>section(i,{time_minutes:v||null})}/><label className="grid gap-2 text-sm">Question type<select aria-label="Blueprint question type" className={input} value={s.format==='STANDARD'?(s.question_type||'ANY'):s.format} disabled={!editable||busy} onChange={e=>{const v=e.target.value;section(i,v==='LONG_ANSWER'||v==='CASE_STUDY'?{question_type:'DESCRIPTIVE',format:v}:{question_type:v==='ANY'?null:v,format:'STANDARD'});}}><option value="ANY">Mixed / Any</option>{questionTypes.map(t=><option key={t} value={t}>{label(t)}</option>)}<option value="LONG_ANSWER">Long Answer</option><option value="CASE_STUDY">Case Study</option></select></label></div>
 <label className="my-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={s.mandatory} disabled={!editable||busy||Boolean(s.main_questions?.length)} onChange={e=>section(i,{mandatory:e.target.checked})}/>All offered questions are mandatory</label><p className="text-xs text-slate-500">{s.main_questions?.length?'Every main question is compulsory; students choose one branch of each OR pair.':'Clear this for “any N” attempts or internal choice. Every section still contributes its configured attempted marks.'}</p>
 {selected?.validation?.sections?.find(value=>value.id===s.id)&&<p className="my-3 text-sm">Saved Offered Marks: {selected.validation.sections.find(value=>value.id===s.id)?.offered_marks} · Saved Attempted Marks: {selected.validation.sections.find(value=>value.id===s.id)?.attempted_marks}{dirty?' · Save to update':''}</p>}
 <QpgHierarchyEditor mains={s.main_questions||[]} marks={s.marks_each} disabled={!editable||busy} syllabus={snapshot?.content} onChange={mains=>section(i,{main_questions:mains,...(mains.length?{offered:mains.length,attempted:mains.length,mandatory:true,choice_groups:[]}:{})})}/>
 <h4 className="my-3 text-sm font-semibold">Internal choice groups</h4>{s.choice_groups.map((g,j)=><div key={g.id} className="mb-3 grid gap-3 sm:grid-cols-4"><label className="grid gap-2 text-sm">Group name<input className={input} value={g.name} disabled={!editable||busy} onChange={e=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,name:e.target.value}:x)})}/></label><NumberField title="Group offered" value={g.offered} disabled={!editable||busy} onChange={v=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,offered:v}:x)})}/><NumberField title="Group choose" value={g.choose} disabled={!editable||busy} onChange={v=>section(i,{choice_groups:s.choice_groups.map((x,k)=>k===j?{...x,choose:v}:x)})}/>{editable&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>section(i,{choice_groups:s.choice_groups.filter((_,k)=>k!==j)})}>Remove group</Button>}</div>)}{editable&&<Button variant="outline" size="sm" disabled={busy||Boolean(s.main_questions?.length)} onClick={()=>section(i,{mandatory:false,choice_groups:[...s.choice_groups,{id:crypto.randomUUID(),name:`Group ${s.choice_groups.length+1}`,offered:2,choose:1}]})}>Add choice group</Button>}
 </section>)}{editable&&<Button variant="outline" className="mb-6" disabled={busy||config.sections.length>=20} onClick={()=>edit({...config,sections:[...config.sections,newSection(config.sections.length+1)]})}>Add section</Button>}
 {snapshot&&<section className="mb-6"><h3 className="mb-3 font-semibold">Coverage from syllabus v{snapshot.version}</h3><p className="mb-3 text-sm text-slate-500">Each configured CO/Unit distribution totals final attempted marks. Topic targets are optional minimum coverage within Unit budgets. Bloom and Difficulty each total 100% when configured.</p>{(['cos','units','topics'] as const).map(kind=><AcademicCoverage key={kind} kind={kind} values={config.coverage[kind]} items={snapshot.content[kind]} units={snapshot.content.units} disabled={!editable||busy} onChange={values=>coverage(kind,values)}/>)}<PercentageCoverage title="Bloom" levels={blooms} values={config.coverage.bloom} disabled={!editable||busy} onChange={v=>coverage('bloom',v)}/><PercentageCoverage title="Difficulty" levels={difficulties} values={config.coverage.difficulty} disabled={!editable||busy} onChange={v=>coverage('difficulty',v)}/></section>}
 <div className="my-4 flex flex-wrap gap-2">{editable&&<><Button disabled={busy||!pin||!config.title.trim()} onClick={()=>void run(async()=>{await persist();})}>Save Draft</Button><Button variant="outline" disabled={busy||!pin||!config.title.trim()} onClick={()=>void operation('validate')}>Validate Paper Pattern</Button><Button disabled={busy||dirty||selected?.status!=='VALIDATED'} onClick={()=>void operation('publish')}>Publish Paper Pattern</Button></>}{canWrite&&selected&&['PUBLISHED','ARCHIVED'].includes(selected.status)&&<Button disabled={busy} onClick={()=>void operation('draft')}>Create new draft version</Button>}{canWrite&&selected?.status==='PUBLISHED'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Archive this published blueprint? Its history remains available.'))void operation('archive');}}>Archive Blueprint</Button>}</div>
 {selected?.validation?.offered_marks&&<section role="status" className="my-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><p><strong>Offered Marks: {selected.validation.offered_marks}</strong></p><p><strong>Attempted Marks: {selected.validation.attempted_marks}</strong></p>{dirty?<p>Saved totals shown. Save and validate your changes for updated totals.</p>:<>{selected.validation.checks?.map(c=><p key={c}>✓ {c}</p>)}{selected.validation.errors?.map(e=><p key={e} className="text-red-700">{e}</p>)}</>}</section>}
 {history.length>0&&<section><h3 className="mb-3 font-semibold">Blueprint versions</h3>{history.map(v=><Button key={v.id} size="sm" variant="outline" className="mr-2 mb-2" disabled={busy} onClick={()=>void run(()=>open(v.id))}>View blueprint v{v.version} · {label(v.status)}</Button>)}</section>}
 </section>;
}
function NumberField({title,value,disabled,onChange}:{title:string;value:Amount;disabled:boolean;onChange:(value:number)=>void}){return <label className="grid gap-2 text-sm">{title}<input aria-label={title} type="number" min={title.toLowerCase().includes('mark')?'0.01':'1'} step={title.toLowerCase().includes('mark')?'0.01':'1'} className={input} value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/></label>;}
function AcademicCoverage({kind,values,items,units,disabled,onChange}:{kind:string;values:Target[];items:SyllabusItem[];units:SyllabusItem[];disabled:boolean;onChange:(values:Target[])=>void}){
 return <fieldset className="mb-4"><legend className="mb-2 text-sm font-semibold">{kind==='cos'?'CO':label(kind)} distribution (marks)</legend>{items.map(item=>{const target=values.find(v=>v.id===item.id);return <div key={item.id} className="mb-2 grid items-center gap-2 sm:grid-cols-2"><p className="text-sm">{item.code} · {item.title}{item.unit_id?` · ${units.find(u=>u.id===item.unit_id)?.code}`:''}</p><input type="number" min="0" step="0.01" aria-label={`${kind} ${item.code} marks`} className={input} disabled={disabled} value={target?.marks??''} placeholder="Unconstrained" onChange={e=>{const remaining=values.filter(v=>v.id!==item.id);onChange(e.target.value?[...remaining,{id:item.id,marks:Number(e.target.value),...(kind==='topics'?{unit_id:item.unit_id}:{})}]:remaining);}}/></div>;})}</fieldset>;
}
function PercentageCoverage({title,levels,values,disabled,onChange}:{title:string;levels:string[];values:Percent[];disabled:boolean;onChange:(values:Percent[])=>void}){return <fieldset className="mb-4"><legend className="mb-2 text-sm font-semibold">{title} distribution (%)</legend><div className="grid gap-3 sm:grid-cols-3">{levels.map(level=><label key={level} className="grid gap-2 text-sm">{label(level)}<input aria-label={`${title} ${level} percent`} type="number" min="0" max="100" step="0.01" className={input} disabled={disabled} value={values.find(v=>v.level===level)?.percent??''} placeholder="Unconstrained" onChange={e=>{const rest=values.filter(v=>v.level!==level);onChange(e.target.value?[...rest,{level,percent:Number(e.target.value)}]:rest);}}/></label>)}</div></fieldset>;}
