import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import type {Subject,Question} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
import Dialog from './QpgDialog';
import QpgGeneratePanel from './QpgGeneratePanel';
import type {QpgGenerationRequest} from './QpgGeneratePanel';
type Recommendation={question_id:string;question_version:number;question:Question & {mapping?:Record<string,{code:string;title:string}|null>};match_type:'STRICT'|'ADVISORY';similarity_score:number|null;novelty_score:number|null;usage:{historical_papers:number;topic_usage:number};warnings:string[];explanations:string[];format_confirmation_required:boolean};
type Generation={request:QpgGenerationRequest;labels:Record<string,string>;allowed_blooms:string[];allowed_difficulties:string[];allowed_types:string[];source_scope:{filename:string;location:string}[]};
type Slot={slot_id:string;position:number;status:string;strict_eligible_count:number;advisory_candidate_count:number;requirement:{label?:string;marks:string;question_type:string|null;format:string};recommended_questions:Recommendation[];generation_available:boolean;generation_state:string;generation_options:Generation[];reasons:string[];selected_question:Question|null;recommended_question_id:string|null};
type Analysis={analysis_token:string;blueprint_version:number;paper_revision:number|null;overall_status:string;covered_slots:number;slot_count:number;partially_covered_slots:number;missing_slots:number;offered_marks:string;attempted_marks:string;warnings:string[];slots:Slot[];stale:boolean;truncated:boolean;question_bank_state:string};
export default function QpgBlueprintIntelligencePanel({subject,paperId,blueprintId,revision,canWrite,onUse,onReview}:{subject:Subject;paperId?:string;blueprintId?:string;revision?:number;canWrite:boolean;onUse?:(slotId:string,questionId:string,questionVersion:number,confirmed:boolean)=>Promise<void>;onReview?:()=>void}){
 const [analysis,setAnalysis]=useState<Analysis|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState<Question|null>(null),[dismissed,setDismissed]=useState<string[]>([]),[confirmed,setConfirmed]=useState<string[]>([]),[generation,setGeneration]=useState<{slot:Slot;option:number;bloom?:string;difficulty?:string;kind?:string}|null>(null),[generationRequest,setGenerationRequest]=useState<QpgGenerationRequest|null>(null);
 const path=paperId?`papers/${paperId}/ai-assist`:`blueprints/${blueprintId}/intelligence`;
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function load(){await run(async()=>{setAnalysis(await qpgApi.get<Analysis>(path));setDismissed([]);setGenerationRequest(null);});}
 async function use(slot:Slot,r:Recommendation){await run(async()=>{if(!analysis||!onUse)return;await qpgApi.save(path+'/refresh',{expected_analysis_token:analysis.analysis_token,expected_version:analysis.blueprint_version,...(paperId?{expected_revision:revision}:{})});await onUse(slot.slot_id,r.question_id,r.question_version,confirmed.includes(slot.slot_id));setAnalysis(null);});}
 return <section className="my-5 rounded-xl border p-4" aria-label="AI Blueprint Analysis"><h3 className="font-semibold">AI Blueprint Analysis</h3><p className="my-2 text-sm text-slate-500">Advisory approved-bank and source analysis. Faculty chooses every assignment; existing validation and approval remain required.</p><Button variant="outline" disabled={busy||(!paperId&&!blueprintId)} onClick={()=>void load()}>{analysis?'Refresh Blueprint Analysis':'Analyze Blueprint'}</Button>{busy&&<p role="status" className="my-2">Analyzing blueprint coverage…</p>}{error&&<p role="alert" className="my-2 text-amber-700">{error} Manual assembly remains available.</p>}
 {analysis&&<><h4 className="mt-4 font-semibold">Blueprint Health · {label(analysis.overall_status)}</h4><p className="my-2 text-sm">Covered {analysis.covered_slots} / {analysis.slot_count} · Partial {analysis.partially_covered_slots} · Missing {analysis.missing_slots}</p><p className="text-sm">Offered marks {analysis.offered_marks} · Attempted marks {analysis.attempted_marks}</p>{analysis.stale&&<p className="text-amber-700">Analysis is stale. Refresh before applying recommendations.</p>}{analysis.warnings.map((w,i)=><p className="my-2 text-sm text-amber-700" key={i}>{w}</p>)}
 {analysis.slots.map(slot=><article className="my-3 rounded-xl border p-3" key={slot.slot_id}><h4 className="font-semibold">Q{slot.requirement.label||slot.position} · {slot.status==='COVERED'?'✓':slot.status==='PARTIAL'?'⚠':'✕'} {label(slot.status)}</h4><p className="my-2 text-sm">{slot.requirement.marks} marks · {slot.requirement.question_type?label(slot.requirement.question_type):'Type chosen by faculty'} · {slot.strict_eligible_count} strict candidates · {slot.advisory_candidate_count} advisory candidates</p>{slot.reasons.map((r,i)=><p className="text-sm text-slate-500" key={i}>{r}</p>)}{slot.selected_question&&<p className="my-2 text-sm">Selected: {slot.selected_question.question_text} · Version {slot.selected_question.version}</p>}
 {dismissed.includes(slot.slot_id)?<p className="my-2 text-sm">Left unresolved. The slot still requires faculty attention.</p>:<>{slot.requirement.format!=='STANDARD'&&<label className="my-2 flex gap-2 text-sm"><input type="checkbox" checked={confirmed.includes(slot.slot_id)} onChange={e=>setConfirmed(v=>e.target.checked?[...v,slot.slot_id]:v.filter(x=>x!==slot.slot_id))}/>I confirm the question suits {label(slot.requirement.format)}.</label>}{slot.recommended_questions.map(r=><div className="my-2 rounded-lg border p-3 text-sm" key={r.question_id}><p className="font-medium">{r.question.question_text}</p><p className="text-xs text-slate-500">{Object.values(r.question.mapping||{}).filter(Boolean).map(m=>m?.code+' · '+m?.title).join(' / ')} · {r.question.bloom_level} · {label(r.question.difficulty)}</p><p>{label(r.match_type)} match · Version {r.question_version}{slot.recommended_question_id===r.question_id?' · Suggested unique plan choice':''}</p><p>Similarity {r.similarity_score===null?'Unavailable':r.similarity_score.toFixed(3)} · Novelty {r.novelty_score??'Unavailable'} · Previous papers {r.usage.historical_papers} · Topic uses {r.usage.topic_usage}</p>{r.explanations.map((e,i)=><p className="text-xs text-slate-500" key={i}>{e}</p>)}{r.warnings.map((w,i)=><p className="text-amber-700" key={i}>{w}</p>)}<div className="my-2 flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void run(async()=>{const q=await qpgApi.get<Question>(`questions/${r.question_id}`);if(q.version!==r.question_version)throw new Error('Question changed. Refresh the analysis.');setView(q);})}>View</Button>{onUse&&canWrite&&!slot.selected_question&&<Button size="sm" disabled={busy||analysis.stale||r.match_type!=='STRICT'||(r.format_confirmation_required&&!confirmed.includes(slot.slot_id))} onClick={()=>void use(slot,r)}>Use Question</Button>}</div></div>)}</>}
 <div className="my-2 flex flex-wrap gap-2">{canWrite&&!slot.selected_question&&<Button size="sm" variant="outline" disabled={busy||analysis.stale||!slot.generation_available} onClick={()=>setGeneration({slot,option:0})}>Generate Question</Button>}{!slot.selected_question&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setDismissed(v=>[...v,slot.slot_id])}>Leave Unresolved</Button>}</div>{!slot.generation_available&&slot.status!=='COVERED'&&<p className="text-sm text-amber-700">{label(slot.generation_state)} · Upload/review relevant sources or adjust the blueprint; no filler questions are created.</p>}</article>)}{analysis.truncated&&<p className="text-sm text-amber-700">Analysis limits reached. Recommendations describe the included sample.</p>}</>}
 {view&&<Dialog title="Recommended Question" onClose={()=>setView(null)}><p className="whitespace-pre-wrap">{view.question_text}</p><p className="my-2 text-sm">{label(view.question_type)} · {view.marks} marks · {view.bloom_level} · {label(view.difficulty)} · {label(view.status)} · Version {view.version}</p>{view.options.map((o,i)=><p key={i}>{o}</p>)}<h4 className="my-2 font-semibold">Answer / solution</h4><p className="whitespace-pre-wrap">{view.answer}</p></Dialog>}
 {generation&&<Dialog title={`Generate for Q${generation.slot.requirement.label||generation.slot.position}`} onClose={()=>setGeneration(null)}><p className="my-2 text-sm">Choose a reviewed source scope. Questions enter the existing review workflow and are not assigned automatically.</p><select aria-label="Generation source scope" className="my-3 w-full rounded-xl border p-2" value={generation.option} onChange={e=>setGeneration({slot:generation.slot,option:Number(e.target.value)})}>{generation.slot.generation_options.map((o,i)=><option key={i} value={i}>{Object.values(o.labels).join(' / ')}</option>)}</select>{(['bloom','difficulty','kind'] as const).map(field=>{const option=generation.slot.generation_options[generation.option];const values=field==='bloom'?option.allowed_blooms:field==='difficulty'?option.allowed_difficulties:option.allowed_types;const initial=field==='bloom'?option.request.bloom_level:field==='difficulty'?option.request.difficulty:option.request.question_type;return <label className="my-2 grid gap-1 text-sm" key={field}>{label(field)}<select aria-label={`Slot generation ${field}`} className="rounded-xl border p-2" value={generation[field]||initial} onChange={e=>setGeneration({...generation,[field]:e.target.value})}>{values.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label>;})}{generation.slot.generation_options[generation.option].source_scope.map((s,i)=><p className="text-sm" key={i}>{s.filename} · {s.location}</p>)}<Button className="mt-3" onClick={()=>{const request=generation.slot.generation_options[generation.option].request;setGenerationRequest({...request,bloom_level:generation.bloom||request.bloom_level,difficulty:generation.difficulty||request.difficulty,question_type:generation.kind||request.question_type});setGeneration(null);}}>Open Generation</Button></Dialog>}
 {generationRequest&&<QpgGeneratePanel key={JSON.stringify(generationRequest)} subject={subject} canWrite={canWrite} initialRequest={generationRequest} onAccepted={()=>setAnalysis(null)} onReview={()=>onReview?.()}/>}
 </section>;
}
