import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,label,questionTypes,blooms,difficulties} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
import {Upload,FileText} from 'lucide-react';
type Pin={id:string;version:number;status:string;document_source_id?:string;content:{cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]}};
type Source={source_id:string;filename:string;chunks:number;reviewed:boolean};
type Chunk={id:string;content:string;location:string;warnings:string[];reviewed:boolean};
export type CandidateEdit={question_text:string;answer:string;options:string[];marking_scheme:string};
export type Candidate={question_version?:number;marking_scheme?:string;review_status?:string;question_id?:string|null;similarity?:{semantic_available:boolean;message:string;matches:{classification:string;similarity:number|null;question:{id:string;version:number;question_text:string}}[]};id:string;decision:string;duplicate:boolean;warnings:string[];question:{question_text:string;answer:string;options:string[];marks:number;question_type:string;rationale:string};provenance:{filename:string;location:string;quote:string;retrieval_score:number}[]};
export type QpgGenerationRequest={binding?:{blueprint_id:string;blueprint_version:number;blueprint_revision:number;node_id:string;paper_id?:string;paper_revision?:number};subject_id:string;syllabus_version_id:string;co_id:string;unit_id:string;topic_id:string;question_type:string;marks:number;bloom_level:string;difficulty:string;count:number;instructions:string;conceptual:boolean};
type Request=QpgGenerationRequest;
type Job={id:string;status:string;revision:number;request:Request;results:Candidate[];failure_reason:string|null;created_at:string};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgGeneratePanel({subject,canWrite,onAccepted,onReview,initialRequest}:{subject:Subject;canWrite:boolean;onAccepted:()=>void;onReview:()=>void;initialRequest?:QpgGenerationRequest}){
 const [pins,setPins]=useState<Pin[]>([]),[pin,setPin]=useState<Pin|null>(null),[sources,setSources]=useState<Source[]>([]),[chunks,setChunks]=useState<Chunk[]>([]),[view,setView]=useState<Source|null>(null);
 const [co,setCo]=useState(''),[unit,setUnit]=useState(''),[topic,setTopic]=useState(''),[kind,setKind]=useState('SHORT_ANSWER'),[marks,setMarks]=useState(2),[bloom,setBloom]=useState('K2'),[difficulty,setDifficulty]=useState('MEDIUM'),[count,setCount]=useState(1),[instructions,setInstructions]=useState(''),[conceptual,setConceptual]=useState(false);
 const [job,setJob]=useState<Job|null>(null),[jobs,setJobs]=useState<Job[]>([]),[enabled,setEnabled]=useState(false),[config,setConfig]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[imports,setImports]=useState<{id:string;source_id:string;filename:string}[]>([]),[original,setOriginal]=useState('');
 const base={subject_id:subject.id,syllabus_version_id:pin?.id||''};
 const association={...base,...(co?{co_id:co}:{}),...(unit?{unit_id:unit}:{}),...(topic?{topic_id:topic}:{})};
 const query=`subject_id=${encodeURIComponent(subject.id)}&syllabus_version_id=${encodeURIComponent(pin?.id||'')}`;
 async function run(work:()=>Promise<void>){setError('');setBusy(true);try{await work();}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function refreshSources(){if(pin)setSources((await qpgApi.get<{items:Source[]}>(`sources?${query}`)).items);}
 async function refreshJobs(){setJobs((await qpgApi.get<{items:Job[]}>(`questions/generation-jobs?subject_id=${subject.id}`)).items);}
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Pin[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{enabled:boolean;message:string}>('questions/generation-config',c.signal),qpgApi.get<{items:Job[]}>(`questions/generation-jobs?subject_id=${subject.id}`,c.signal),qpgApi.get<{items:{id:string;source_id:string;filename:string}[]}>(`imports?subject_id=${subject.id}`,c.signal)]).then(async([p,a,j,i])=>{setPins(p.items.filter(x=>x.status==='PUBLISHED'));setEnabled(a.enabled);setConfig(a.message);setJobs(j.items);setImports(i.items);if(initialRequest){const selected=await qpgApi.get<Pin>(`subjects/${subject.id}/syllabus/versions/${initialRequest.syllabus_version_id}`,c.signal);if(c.signal.aborted)return;setPin(selected);setCo(initialRequest.co_id);setUnit(initialRequest.unit_id);setTopic(initialRequest.topic_id);setKind(initialRequest.question_type);setMarks(Number(initialRequest.marks));setBloom(initialRequest.bloom_level);setDifficulty(initialRequest.difficulty);setCount(1);setConceptual(false);setInstructions(initialRequest.instructions);}}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[subject.id,initialRequest]);
 useEffect(()=>{if(!pin)return;const c=new AbortController();qpgApi.get<{items:Source[]}>(`sources?subject_id=${encodeURIComponent(subject.id)}&syllabus_version_id=${encodeURIComponent(pin.id)}`,c.signal).then(s=>setSources(s.items)).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[subject.id,pin]);
 useEffect(()=>{if(!job||!['QUEUED','RUNNING'].includes(job.status))return;const c=new AbortController();const timer=setInterval(()=>{qpgApi.get<Job>(`questions/generation-jobs/${job.id}`,c.signal).then(next=>{setJob(next);if(!['QUEUED','RUNNING'].includes(next.status))setJobs(previous=>[next,...previous.filter(j=>j.id!==next.id)]);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});},1000);return()=>{clearInterval(timer);c.abort();};},[job]);
 async function generate(request:Request){const next=await qpgApi.save<Job>('questions/generate',request);setJob(next);await refreshJobs();}
 return <section className="erp-card max-w-5xl" aria-label="AI question generation"><h2>Generate Questions · {subject.name} ({subject.code})</h2><p className="my-3 text-sm text-slate-500">Generate a focused question set for one topic. Choose a batch size and describe the concepts students should demonstrate.</p>{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{!enabled&&<div role="status" className="my-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950 dark:text-amber-100"><strong>{config?'AI generation is not available yet':'Checking AI availability…'}</strong>{config&&<p className="mt-1">Your administrator needs to enable AI. You can still prepare the settings below.</p>}</div>}
 <section className="my-5 rounded-xl border border-slate-200 p-5 dark:border-slate-700"><h3 className="mb-4 font-semibold">1. Choose what to cover</h3><label className="grid gap-2 text-sm">Published syllabus<select aria-label="Generation syllabus" className={input} value={pin?.id||''} disabled={busy||!!initialRequest} onChange={e=>void run(async()=>{setPin(await qpgApi.get<Pin>(`subjects/${subject.id}/syllabus/versions/${e.target.value}`));setCo('');setUnit('');setTopic('');setSources([]);})}><option value="" disabled>Select published syllabus</option>{pins.map(p=><option key={p.id} value={p.id}>{subject.name} ({subject.code}) — Version {p.version} · Published</option>)}</select></label>
 {pin&&<><div className="my-4 grid gap-3 sm:grid-cols-3"><Select title="Course Outcome (CO)" value={co} disabled={!!initialRequest} change={setCo} values={pin.content.cos.map(x=>[x.id,`${x.code} · ${x.title}`])}/><Select title="Unit" value={unit} disabled={!!initialRequest} change={v=>{setUnit(v);setTopic('');}} values={pin.content.units.map(x=>[x.id,`${x.code} · ${x.title}`])}/><Select title="Topic" value={topic} disabled={!!initialRequest||!unit} change={setTopic} values={pin.content.topics.filter(x=>x.unit_id===unit).map(x=>[x.id,`${x.code} · ${x.title}`])}/></div>
 </> }</section>
 {pin&&<><section className="my-5 rounded-xl border border-slate-200 p-5 dark:border-slate-700"><h3 className="font-semibold">2. Add teaching material</h3><p className="my-2 text-sm text-slate-500">Upload notes for the chosen topic, then review the extracted text before using it.</p>
 {canWrite&&<div className="my-4 rounded-xl border-2 border-dashed border-slate-300 p-4 dark:border-slate-600"><label className="relative flex cursor-pointer flex-col items-center gap-2 py-4 text-center focus-within:ring-2 focus-within:ring-indigo-600"><Upload size={26} className="text-indigo-600" aria-hidden="true"/><span className="text-sm font-medium">Choose notes or a reference document</span><span className="text-xs text-slate-500">PDF, DOCX, Excel, CSV or text · Up to 10 MB</span><input aria-label="Generation source file" type="file" disabled={busy} className="absolute inset-0 h-full w-full cursor-pointer opacity-0" accept=".pdf,.docx,.xlsx,.csv,.txt" onChange={e=>{const selected=e.target.files?.[0]||null;if(selected&&(!selected.size||selected.size>10*1024*1024||!/\.(pdf|docx|xlsx|csv|txt)$/i.test(selected.name))){setError('Choose a supported, non-empty file up to 10 MB.');setFile(null);e.target.value='';return;}setError('');setFile(selected);}}/></label>{file&&<p className="my-2 flex items-center gap-2 break-all text-sm"><FileText size={18} aria-hidden="true"/>{file.name} · {(file.size/1024/1024).toFixed(2)} MB</p>}<div className="flex justify-end"><Button disabled={busy||!file} onClick={()=>void run(async()=>{const data=new FormData();Object.entries(association).forEach(([k,v])=>data.append(k,v));data.append('file',file!);await apiClient.post('/v3/college/question-papers/sources/upload',data,{timeout:125000});await refreshSources();})}>{busy?'Please wait…':'Upload material'}</Button></div></div>}
 {canWrite&&(imports.length>0||pin.document_source_id)&&<details className="my-3"><summary className="cursor-pointer text-sm font-medium">Use a previously uploaded document</summary><div className="mt-3 flex flex-wrap gap-2"><Select title="Existing source" value={original} change={setOriginal} values={[...imports.map(x=>[x.source_id,x.filename]),...(pin.document_source_id?[[pin.document_source_id,'Official syllabus document']]:[])]}/><Button variant="outline" disabled={busy||!original} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${original}/index`,association);await refreshSources();})}>Use this document</Button></div></details>}
 <div className="space-y-2">{!sources.some(s=>s.reviewed)&&!conceptual&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-950 dark:text-amber-200">Review relevant teaching material before generating. To work without uploaded notes, select “Generate without uploaded sources” under Advanced options.</p>}{sources.map(s=><div key={s.source_id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><span>{s.filename} · {s.chunks} text sections · {s.reviewed?'Ready to use':'Review required'}</span><Button variant="outline" onClick={()=>void run(async()=>{setChunks((await qpgApi.get<{items:Chunk[]}>(`sources/${s.source_id}/chunks?${query}`)).items);setView(s);})}>Review source</Button></div>)}</div>
 </section><section className="my-5 rounded-xl border border-slate-200 p-5 dark:border-slate-700"><h3 className="font-semibold">3. Set your question set</h3>{!initialRequest&&<div className="my-3 flex flex-wrap items-center gap-2"><span className="mr-2 text-sm text-slate-500">Batch size</span>{[1,5,10].map(n=><Button key={n} size="sm" variant={count===n?"default":"outline"} disabled={busy} onClick={()=>setCount(n)}>{n===1?"Single question":`${n} questions`}</Button>)}</div>}<div className="my-3 grid gap-3 sm:grid-cols-3"><Select title="Question type" value={kind} disabled={!!initialRequest} change={setKind} values={questionTypes.map(x=>[x,label(x)])}/><NumberField title="Marks per question" value={marks} disabled={!!initialRequest} change={setMarks} max={1000}/><NumberField title="Number of questions" value={count} disabled={!!initialRequest} change={setCount} max={10}/><Select title="Bloom level" value={bloom} disabled={!!initialRequest} change={setBloom} values={blooms.map(x=>[x,label(x)])}/><Select title="Difficulty" value={difficulty} disabled={!!initialRequest} change={setDifficulty} values={difficulties.map(x=>[x,label(x)])}/></div>
 <label className="my-4 grid gap-2 text-sm">Question focus (optional)<textarea aria-label="Generation instructions" className={input} rows={3} maxLength={2000} placeholder="Example: Compare the algorithms in the selected topic, analyze their trade-offs, and provide marks-based answer points." value={instructions} onChange={e=>setInstructions(e.target.value)}/><span className="text-xs text-slate-500">Name the specific concepts or algorithms to cover when the selected topic is broad. Each question must fit the selected marks and Bloom level.</span></label><details className="my-4 rounded-lg bg-slate-50 p-3 dark:bg-slate-900"><summary className="cursor-pointer text-sm font-medium">Generation mode</summary><div className="mt-3"><label className="my-3 flex flex-row items-start gap-2 text-sm"><input type="checkbox" checked={conceptual} disabled={!!initialRequest} onChange={e=>setConceptual(e.target.checked)}/>Generate without uploaded sources (conceptual questions)</label><p className="text-xs text-slate-500">Questions in this mode have no supporting source citations. Faculty review is still required.</p></div></details>
 <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-xs text-slate-500">Generated questions need faculty approval before use in a paper.</p>{canWrite&&<Button disabled={busy||!enabled||!co||!unit||!topic||!!job&&['QUEUED','RUNNING'].includes(job.status)} onClick={()=>void run(()=>generate({...base,...(initialRequest?.binding?{binding:initialRequest.binding}:{}),co_id:co,unit_id:unit,topic_id:topic,question_type:kind,marks,bloom_level:bloom,difficulty,count,instructions,conceptual}))}>{`Generate ${count} question${count===1?"":"s"}`}</Button>}</div></section></>}
 <details className="my-5"><summary className="cursor-pointer text-sm font-medium">Previous generation requests ({jobs.length})</summary><div className="mt-3 flex flex-wrap gap-2">{jobs.map(j=><Button variant="outline" size="sm" key={j.id} onClick={()=>void run(async()=>setJob(await qpgApi.get<Job>(`questions/generation-jobs/${j.id}`)))}>{label(j.status)} · {new Date(j.created_at).toLocaleString()}</Button>)}</div></details>
 {job&&<section aria-label="Generation results"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-semibold">Generated questions</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-sm dark:bg-slate-800">{label(job.status)}</span></div><p className="my-2 text-sm text-slate-500">{label(job.request.question_type)} · {job.request.marks} marks · {job.request.bloom_level} · {label(job.request.difficulty)} · {job.request.count} requested · {job.request.conceptual?'Conceptual mode':'Source grounded'}</p>{job.failure_reason&&<p role="alert">{job.failure_reason}</p>}{['QUEUED','RUNNING'].includes(job.status)&&<><p role="status">Generating and validating questions…</p>{canWrite&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>setJob(await qpgApi.save<Job>(`questions/generation-jobs/${job.id}/cancel`,{expected_revision:job.revision})))}>Cancel generation</Button>}</>}
 {canWrite&&!['QUEUED','RUNNING'].includes(job.status)&&<Button className="my-3" variant="outline" disabled={busy||!enabled} onClick={()=>void run(()=>generate(job.request))}>Regenerate with same settings</Button>}
 {job.results.map(r=><Result key={job.id+r.id} candidate={r} editable={canWrite&&r.decision==='PENDING'} busy={busy} decide={(accept,edited)=>void run(async()=>{const next=await qpgApi.save<Job>(`questions/generation-jobs/${job.id}/results/${r.id}/${accept?'accept':'reject'}`,{expected_revision:job.revision,...(accept?edited:{})});setJob(next);await refreshJobs();if(accept)onAccepted();})}/>)}<Button className="mt-3" variant="outline" onClick={onReview}>Open Review Queue</Button></section>}
 {view&&<Dialog title={`Review source · ${view.filename}`} onClose={()=>setView(null)}><p className="mb-3">Confirm extracted text is readable and preserves notation. Flagged boundaries, tables and formulas need particular care.</p><div className="max-h-96 space-y-3 overflow-auto">{chunks.map(c=><article className="rounded-xl border p-3" key={c.id}><h4>{c.location}</h4><pre className="whitespace-pre-wrap text-sm">{c.content}</pre>{c.warnings.map((w,i)=><p className="text-amber-700" key={i}>{w}</p>)}</article>)}</div>{canWrite&&<div className="mt-4 flex gap-2"><Button disabled={busy} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${view.source_id}/review`,{...base,expected_chunks:chunks.length,reviewed:true});await refreshSources();setView(null);})}>Confirm extraction for retrieval</Button><Button variant="outline" disabled={busy||!view.reviewed} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${view.source_id}/review`,{...base,expected_chunks:chunks.length,reviewed:false});await refreshSources();setView(null);})}>Revoke review</Button></div>}</Dialog>}
 </section>;
}
function Select({title,value,change,values,disabled}:{title:string;value:string;change:(v:string)=>void;values:string[][];disabled?:boolean}){return <label className="grid gap-2 text-sm">{title}<select aria-label={title} className={input} value={value} disabled={disabled} onChange={e=>change(e.target.value)}><option value="" disabled>Select</option>{values.map(([id,name],i)=><option key={id+i} value={id}>{name}</option>)}</select></label>;}
function NumberField({title,value,change,max,disabled}:{title:string;value:number;change:(v:number)=>void;max:number;disabled?:boolean}){return <label className="grid gap-2 text-sm">{title}<input aria-label={title} type="number" min={title==='Marks per question'?0.01:1} step={title==='Marks per question'?0.01:1} max={max} disabled={disabled} className={input} value={value} onChange={e=>change(Number(e.target.value))}/></label>;}
export function Result({candidate:r,editable,busy,decide,saveDraft,forceEditing=false,actionError='',actionNotice=''}:{candidate:Candidate;editable:boolean;busy:boolean;decide:(accept:boolean,edited?:CandidateEdit)=>void;saveDraft?:(edited:CandidateEdit)=>void;forceEditing?:boolean;actionError?:string;actionNotice?:string}){
 const [text,setText]=useState(r.question.question_text),[answer,setAnswer]=useState(r.question.answer),[options,setOptions]=useState(r.question.options.join('\n')),[editing,setEditing]=useState(forceEditing),[scheme,setScheme]=useState(r.marking_scheme||'');
 const optionValues=r.question.options.join('\n');
 useEffect(()=>{setText(r.question.question_text);setAnswer(r.question.answer);setOptions(r.question.options.join('\n'));setScheme(r.marking_scheme||'');},[r.question.question_text,r.question.answer,optionValues,r.marking_scheme]);
 const changes:CandidateEdit={question_text:text,answer,options:r.question.question_type==='MCQ'?options.split('\n').filter(x=>x.trim()):[],marking_scheme:scheme};
 return <article className="my-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="text-sm font-medium text-slate-500">{label(r.question.question_type)} · {r.question.marks} marks</h4><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium dark:bg-slate-800">{r.decision==='ACCEPTED'?(r.review_status==='APPROVED'?'Faculty approved':'Saved for faculty review'):label(r.decision)}</span></div>{editing?<><label>Candidate question<textarea aria-label="Candidate question" maxLength={20000} disabled={busy} className={input} value={text} onChange={e=>setText(e.target.value)}/></label><label>Candidate answer<textarea aria-label="Candidate answer" maxLength={20000} disabled={busy} className={input} value={answer} onChange={e=>setAnswer(e.target.value)}/></label>{r.question.question_type==='MCQ'&&<label>Options, one per line<textarea aria-label="Candidate options" disabled={busy} className={input} value={options} onChange={e=>setOptions(e.target.value)}/></label>}<label className="mt-3 block">Marking guidance / points<textarea aria-label="Candidate marking guidance" className={input} maxLength={20000} value={scheme} disabled={busy} onChange={e=>setScheme(e.target.value)}/></label></>:<><p className="my-3 whitespace-pre-wrap">{r.question.question_text}</p>{r.question.options.map((o,i)=><p key={i}>{String.fromCharCode(65+i)}. {o}</p>)}<details className="my-4 rounded-lg bg-slate-50 p-4 dark:bg-slate-800"><summary className="cursor-pointer text-sm font-medium">View answer and explanation</summary><p className="mt-3 whitespace-pre-wrap text-sm">{r.question.answer}</p><p className="mt-3 text-sm text-slate-500">{r.question.rationale}</p>{r.marking_scheme&&<p className="mt-3 whitespace-pre-wrap text-sm">Marking guidance: {r.marking_scheme}</p>}</details></>}
 <section className="my-4 rounded-lg border border-amber-200 bg-amber-50/50 p-4 dark:bg-amber-950/20"><h5 className="mb-2 text-sm font-semibold">Faculty review notes</h5>{r.duplicate&&<p className="text-amber-700">Exact duplicate detected. Edit or reject before acceptance.</p>}{r.similarity&&<section className="my-3 rounded-lg border border-amber-200 p-3 text-sm" aria-label="Generated question similarity"><p>{r.similarity.message}</p>{r.similarity.matches?.length>0&&<h5 className="font-semibold">Potentially similar question</h5>}{(r.similarity.matches||[]).map(m=><p key={m.question.id} className="my-2">{label(m.classification)}{m.similarity!==null?` · Cosine ${m.similarity.toFixed(3)}`:''} · Version {m.question.version}: {m.question.question_text}</p>)}</section>}{r.warnings.map((w,i)=><p className="my-2 text-sm text-amber-700" key={i}>{w}</p>)}</section><details className="my-4 border-t border-slate-100 pt-3 dark:border-slate-700"><summary className="cursor-pointer text-sm font-medium">Sources and supporting evidence ({r.provenance.length})</summary>{r.provenance.length?r.provenance.map((p,i)=><blockquote className="my-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-900" key={i}><p>{p.filename} · {p.location} · relevance {p.retrieval_score.toFixed(2)}</p><p className="whitespace-pre-wrap">{p.quote}</p></blockquote>):<p className="mt-3 text-sm text-slate-500">Generated without uploaded material. No source citations are available.</p>}</details>
 {actionError&&<p role="alert" className="my-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{actionError}</p>}{actionNotice&&<p role="status" className="my-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{actionNotice}</p>}{editable&&<div className="mt-3 flex flex-wrap gap-2">{r.decision==='PENDING'&&<Button disabled={busy} type="button" onClick={()=>decide(true,editing?changes:undefined)}>{busy?'Please wait…':'Accept for review'}</Button>}{editing&&saveDraft&&<Button variant="outline" disabled={busy||!text.trim()||!answer.trim()} onClick={()=>saveDraft(changes)}>Save question draft</Button>}<Button variant="outline" disabled={busy} onClick={()=>{if(editing){setText(r.question.question_text);setAnswer(r.question.answer);setOptions(r.question.options.join('\n'));setScheme(r.marking_scheme||'');}setEditing(!editing);}}>{editing?'Cancel edit':'Edit question'}</Button>{r.decision==='PENDING'&&<Button variant="outline" disabled={busy} onClick={()=>decide(false)}>Reject candidate</Button>}</div>}{r.decision==='ACCEPTED'&&<div className="mt-4 rounded-lg bg-indigo-50 p-3 text-sm dark:bg-indigo-950/40"><p className="font-medium">Saved to Question Bank</p><p className="mt-1 text-slate-600 dark:text-slate-300">Next: open the review queue. Faculty approval is required before this question can be used in a paper.</p></div>}</article>;
}
