import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,label,questionTypes,blooms,difficulties} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
type Pin={id:string;version:number;status:string;document_source_id?:string;content:{cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]}};
type Source={source_id:string;filename:string;chunks:number;reviewed:boolean};
type Chunk={id:string;content:string;location:string;warnings:string[];reviewed:boolean};
type Candidate={similarity?:{semantic_available:boolean;message:string;matches:{classification:string;similarity:number|null;question:{id:string;version:number;question_text:string}}[]};id:string;decision:string;duplicate:boolean;warnings:string[];question:{question_text:string;answer:string;options:string[];marks:number;question_type:string;rationale:string};provenance:{filename:string;location:string;quote:string;retrieval_score:number}[]};
export type QpgGenerationRequest={binding?:{blueprint_id:string;blueprint_version:number;blueprint_revision:number;node_id:string;paper_id?:string;paper_revision?:number};subject_id:string;syllabus_version_id:string;co_id:string;unit_id:string;topic_id:string;question_type:string;marks:number;bloom_level:string;difficulty:string;count:number;instructions:string;conceptual:boolean};
type Request=QpgGenerationRequest;
type Job={id:string;status:string;revision:number;request:Request;results:Candidate[];failure_reason:string|null;created_at:string};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgGeneratePanel({subject,canWrite,onAccepted,onReview,initialRequest}:{subject:Subject;canWrite:boolean;onAccepted:()=>void;onReview:()=>void;initialRequest?:QpgGenerationRequest}){
 const [pins,setPins]=useState<Pin[]>([]),[pin,setPin]=useState<Pin|null>(null),[sources,setSources]=useState<Source[]>([]),[chunks,setChunks]=useState<Chunk[]>([]),[view,setView]=useState<Source|null>(null);
 const [co,setCo]=useState(''),[unit,setUnit]=useState(''),[topic,setTopic]=useState(''),[kind,setKind]=useState('SHORT_ANSWER'),[marks,setMarks]=useState(2),[bloom,setBloom]=useState('K2'),[difficulty,setDifficulty]=useState('MEDIUM'),[count,setCount]=useState(1),[instructions,setInstructions]=useState(''),[conceptual,setConceptual]=useState(false);
 const [job,setJob]=useState<Job|null>(null),[jobs,setJobs]=useState<Job[]>([]),[enabled,setEnabled]=useState(false),[config,setConfig]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[imports,setImports]=useState<{id:string;source_id:string;filename:string}[]>([]),[original,setOriginal]=useState('');
 const base={subject_id:subject.id,syllabus_version_id:pin?.id||''};
 const association={...base,...(co?{co_id:co}:{}),...(unit?{unit_id:unit}:{}),...(topic?{topic_id:topic}:{})};
 const query=`subject_id=${encodeURIComponent(subject.id)}&syllabus_version_id=${encodeURIComponent(pin?.id||'')}`;
 async function run(work:()=>Promise<void>){setError('');setBusy(true);try{await work();}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function refreshSources(){if(pin)setSources((await qpgApi.get<{items:Source[]}>(`sources?${query}`)).items);}
 async function refreshJobs(){setJobs((await qpgApi.get<{items:Job[]}>(`questions/generation-jobs?subject_id=${subject.id}`)).items);}
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Pin[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{enabled:boolean;message:string}>('questions/generation-config',c.signal),qpgApi.get<{items:Job[]}>(`questions/generation-jobs?subject_id=${subject.id}`,c.signal),qpgApi.get<{items:{id:string;source_id:string;filename:string}[]}>(`imports?subject_id=${subject.id}`,c.signal)]).then(async([p,a,j,i])=>{setPins(p.items.filter(x=>x.status==='PUBLISHED'));setEnabled(a.enabled);setConfig(a.message);setJobs(j.items);setImports(i.items);if(initialRequest){const selected=await qpgApi.get<Pin>(`subjects/${subject.id}/syllabus/versions/${initialRequest.syllabus_version_id}`,c.signal);if(c.signal.aborted)return;setPin(selected);setCo(initialRequest.co_id);setUnit(initialRequest.unit_id);setTopic(initialRequest.topic_id);setKind(initialRequest.question_type);setMarks(Number(initialRequest.marks));setBloom(initialRequest.bloom_level);setDifficulty(initialRequest.difficulty);setCount(1);setConceptual(false);setInstructions(initialRequest.instructions);}}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[subject.id,initialRequest]);
 useEffect(()=>{if(!pin)return;const c=new AbortController();qpgApi.get<{items:Source[]}>(`sources?subject_id=${encodeURIComponent(subject.id)}&syllabus_version_id=${encodeURIComponent(pin.id)}`,c.signal).then(s=>setSources(s.items)).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[subject.id,pin]);
 useEffect(()=>{if(!job||!['QUEUED','RUNNING'].includes(job.status))return;const c=new AbortController();const timer=setInterval(()=>{qpgApi.get<Job>(`questions/generation-jobs/${job.id}`,c.signal).then(next=>{setJob(next);if(!['QUEUED','RUNNING'].includes(next.status))setJobs(previous=>[next,...previous.filter(j=>j.id!==next.id)]);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});},1000);return()=>{clearInterval(timer);c.abort();};},[job]);
 async function generate(request:Request){const next=await qpgApi.save<Job>('questions/generate',request);setJob(next);await refreshJobs();}
 return <section className="erp-card" aria-label="AI question generation"><h2>Generate Questions · {subject.code}</h2><p className="my-3 text-sm text-slate-500">Use reviewed source material and a published syllabus. Accepted questions need faculty approval before paper assembly.</p>{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{!enabled&&<p role="status" className="my-3">{config||'Checking AI configuration…'}</p>}
 <label>Generation syllabus<select aria-label="Generation syllabus" className={input} value={pin?.id||''} disabled={busy||!!initialRequest} onChange={e=>void run(async()=>{setPin(await qpgApi.get<Pin>(`subjects/${subject.id}/syllabus/versions/${e.target.value}`));setCo('');setUnit('');setTopic('');setSources([]);})}><option value="" disabled>Select published syllabus</option>{pins.map(p=><option key={p.id} value={p.id}>Published syllabus v{p.version}</option>)}</select></label>
 {pin&&<><div className="my-4 grid gap-3 sm:grid-cols-3"><Select title="Generation CO" value={co} disabled={!!initialRequest} change={setCo} values={pin.content.cos.map(x=>[x.id,`${x.code} · ${x.title}`])}/><Select title="Generation Unit" value={unit} disabled={!!initialRequest} change={v=>{setUnit(v);setTopic('');}} values={pin.content.units.map(x=>[x.id,`${x.code} · ${x.title}`])}/><Select title="Generation Topic" value={topic} disabled={!!initialRequest} change={setTopic} values={pin.content.topics.filter(x=>x.unit_id===unit).map(x=>[x.id,`${x.code} · ${x.title}`])}/></div>
 <h3 className="font-semibold">Source material</h3><p className="my-2 text-sm text-slate-500">Upload PDF, DOCX, Excel, CSV or UTF-8 text. Inspect the extracted text, notation and warnings before enabling retrieval. Selected CO, Unit and Topic restrict this upload.</p>
 {canWrite&&<div className="my-3 flex flex-wrap items-center gap-3"><input aria-label="Generation source file" type="file" accept=".pdf,.docx,.xlsx,.csv,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/><Button variant="outline" disabled={busy||!file} onClick={()=>void run(async()=>{const data=new FormData();Object.entries(association).forEach(([k,v])=>data.append(k,v));data.append('file',file!);await apiClient.post('/v3/college/question-papers/sources/upload',data,{headers:{'Content-Type':'multipart/form-data'},timeout:125000});await refreshSources();})}>Upload source</Button></div>}
 {canWrite&&(imports.length>0||pin.document_source_id)&&<div className="my-3 flex gap-2"><Select title="Existing source" value={original} change={setOriginal} values={[...imports.map(x=>[x.source_id,x.filename]),...(pin.document_source_id?[[pin.document_source_id,'Official syllabus document']]:[])]}/><Button variant="outline" disabled={busy||!original} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${original}/index`,association);await refreshSources();})}>Index existing source</Button></div>}
 <div className="space-y-2">{sources.map(s=><div key={s.source_id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><span>{s.filename} · {s.chunks} chunks · {s.reviewed?'Ready for retrieval':'Extraction review required'}</span><Button variant="outline" onClick={()=>void run(async()=>{setChunks((await qpgApi.get<{items:Chunk[]}>(`sources/${s.source_id}/chunks?${query}`)).items);setView(s);})}>Review source</Button></div>)}</div>
 <h3 className="mt-6 font-semibold">Generation settings</h3><div className="my-3 grid gap-3 sm:grid-cols-3"><Select title="Generation type" value={kind} disabled={!!initialRequest} change={setKind} values={questionTypes.map(x=>[x,label(x)])}/><NumberField title="Generation marks" value={marks} disabled={!!initialRequest} change={setMarks} max={1000}/><NumberField title="Question count" value={count} disabled={!!initialRequest} change={setCount} max={10}/><Select title="Generation Bloom level" value={bloom} disabled={!!initialRequest} change={setBloom} values={blooms.map(x=>[x,x])}/><Select title="Generation difficulty" value={difficulty} disabled={!!initialRequest} change={setDifficulty} values={difficulties.map(x=>[x,label(x)])}/></div>
 <label>Additional instructions<textarea aria-label="Generation instructions" className={input} maxLength={2000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label><label className="my-3 flex items-center gap-2"><input type="checkbox" checked={conceptual} disabled={!!initialRequest} onChange={e=>setConceptual(e.target.checked)}/>Explicit conceptual generation: permit questions without source grounding</label>
 {canWrite&&<Button disabled={busy||!enabled||!co||!unit||!topic||!!job&&['QUEUED','RUNNING'].includes(job.status)} onClick={()=>void run(()=>generate({...base,...(initialRequest?.binding?{binding:initialRequest.binding}:{}),co_id:co,unit_id:unit,topic_id:topic,question_type:kind,marks,bloom_level:bloom,difficulty,count,instructions,conceptual}))}>Generate questions</Button>}</>}
 <div className="my-5 flex flex-wrap gap-2">{jobs.map(j=><Button variant="outline" size="sm" key={j.id} onClick={()=>void run(async()=>setJob(await qpgApi.get<Job>(`questions/generation-jobs/${j.id}`)))}>{label(j.status)} · {new Date(j.created_at).toLocaleString()}</Button>)}</div>
 {job&&<section aria-label="Generation results"><h3 className="font-semibold">{label(job.status)}</h3><p className="my-2 text-sm text-slate-500">{label(job.request.question_type)} · {job.request.marks} marks · {job.request.bloom_level} · {label(job.request.difficulty)} · {job.request.count} requested · {job.request.conceptual?'Conceptual mode':'Source grounded'}</p>{job.failure_reason&&<p role="alert">{job.failure_reason}</p>}{['QUEUED','RUNNING'].includes(job.status)&&<><p role="status">Generating and validating questions…</p>{canWrite&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>setJob(await qpgApi.save<Job>(`questions/generation-jobs/${job.id}/cancel`,{expected_revision:job.revision})))}>Cancel generation</Button>}</>}
 {canWrite&&!['QUEUED','RUNNING'].includes(job.status)&&<Button className="my-3" variant="outline" disabled={busy||!enabled} onClick={()=>void run(()=>generate(job.request))}>Regenerate with same settings</Button>}
 {job.results.map(r=><Result key={job.id+r.id} candidate={r} editable={canWrite&&r.decision==='PENDING'} busy={busy} decide={(accept,edited)=>void run(async()=>{const next=await qpgApi.save<Job>(`questions/generation-jobs/${job.id}/results/${r.id}/${accept?'accept':'reject'}`,{expected_revision:job.revision,...(accept?edited:{})});setJob(next);await refreshJobs();if(accept)onAccepted();})}/>)}<Button className="mt-3" variant="outline" onClick={onReview}>Open Review Queue</Button></section>}
 {view&&<Dialog title={`Review source · ${view.filename}`} onClose={()=>setView(null)}><p className="mb-3">Confirm extracted text is readable and preserves notation. Flagged boundaries, tables and formulas need particular care.</p><div className="max-h-96 space-y-3 overflow-auto">{chunks.map(c=><article className="rounded-xl border p-3" key={c.id}><h4>{c.location}</h4><pre className="whitespace-pre-wrap text-sm">{c.content}</pre>{c.warnings.map((w,i)=><p className="text-amber-700" key={i}>{w}</p>)}</article>)}</div>{canWrite&&<div className="mt-4 flex gap-2"><Button disabled={busy} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${view.source_id}/review`,{...base,expected_chunks:chunks.length,reviewed:true});await refreshSources();setView(null);})}>Confirm extraction for retrieval</Button><Button variant="outline" disabled={busy||!view.reviewed} onClick={()=>void run(async()=>{await qpgApi.save(`sources/${view.source_id}/review`,{...base,expected_chunks:chunks.length,reviewed:false});await refreshSources();setView(null);})}>Revoke review</Button></div>}</Dialog>}
 </section>;
}
function Select({title,value,change,values,disabled}:{title:string;value:string;change:(v:string)=>void;values:string[][];disabled?:boolean}){return <label>{title}<select aria-label={title} className={input} value={value} disabled={disabled} onChange={e=>change(e.target.value)}><option value="" disabled>Select</option>{values.map(([id,name],i)=><option key={id+i} value={id}>{name}</option>)}</select></label>;}
function NumberField({title,value,change,max,disabled}:{title:string;value:number;change:(v:number)=>void;max:number;disabled?:boolean}){return <label>{title}<input aria-label={title} type="number" min={title==='Generation marks'?0.01:1} step={title==='Generation marks'?0.01:1} max={max} disabled={disabled} className={input} value={value} onChange={e=>change(Number(e.target.value))}/></label>;}
function Result({candidate:r,editable,busy,decide}:{candidate:Candidate;editable:boolean;busy:boolean;decide:(accept:boolean,edited?:{question_text:string;answer:string;options:string[]})=>void}){
 const [text,setText]=useState(r.question.question_text),[answer,setAnswer]=useState(r.question.answer),[options,setOptions]=useState(r.question.options.join('\n')),[editing,setEditing]=useState(false);
 return <article className="my-4 rounded-xl border p-4"><h4 className="font-semibold">{label(r.question.question_type)} · {r.question.marks} marks · {label(r.decision)}</h4>{editing?<><label>Candidate question<textarea aria-label="Candidate question" className={input} value={text} onChange={e=>setText(e.target.value)}/></label><label>Candidate answer<textarea aria-label="Candidate answer" className={input} value={answer} onChange={e=>setAnswer(e.target.value)}/></label>{r.question.question_type==='MCQ'&&<label>Options, one per line<textarea aria-label="Candidate options" className={input} value={options} onChange={e=>setOptions(e.target.value)}/></label>}</>:<><p className="my-3 whitespace-pre-wrap">{r.question.question_text}</p>{r.question.options.map((o,i)=><p key={i}>{String.fromCharCode(65+i)}. {o}</p>)}<p className="my-2 whitespace-pre-wrap">Answer: {r.question.answer}</p></>}
 <p className="text-sm">Rationale: {r.question.rationale}</p>{r.duplicate&&<p className="text-amber-700">Exact duplicate detected. Edit or reject before acceptance.</p>}{r.similarity&&<section className="my-3 rounded-lg border border-amber-200 p-3 text-sm" aria-label="Generated question similarity"><p>{r.similarity.message}</p>{r.similarity.matches?.length>0&&<h5 className="font-semibold">Potentially similar question</h5>}{(r.similarity.matches||[]).map(m=><p key={m.question.id} className="my-2">{label(m.classification)}{m.similarity!==null?` · Cosine ${m.similarity.toFixed(3)}`:''} · Version {m.question.version}: {m.question.question_text}</p>)}</section>}{r.warnings.map((w,i)=><p className="my-2 text-sm text-amber-700" key={i}>{w}</p>)}<h5 className="mt-3 font-semibold">Source evidence</h5>{r.provenance.length?r.provenance.map((p,i)=><blockquote className="my-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-900" key={i}><p>{p.filename} · {p.location} · relevance {p.retrieval_score.toFixed(2)}</p><p className="whitespace-pre-wrap">{p.quote}</p></blockquote>):<p>No source grounding; conceptual mode.</p>}
 {editable&&<div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>decide(true,editing?{question_text:text,answer,options:r.question.question_type==='MCQ'?options.split('\n').filter(x=>x.trim()):[]}:undefined)}>Accept for review</Button><Button variant="outline" disabled={busy} onClick={()=>setEditing(!editing)}>{editing?'Cancel edit':'Edit candidate'}</Button><Button variant="outline" disabled={busy} onClick={()=>decide(false)}>Reject candidate</Button></div>}{r.decision==='ACCEPTED'&&<p className="mt-3 text-sm">Saved to Question Bank · Needs Review</p>}</article>;
}
