import {Button} from '@/components/ui/button';
import {blooms,difficulties,questionTypes,label} from '@/api/qpgApi';
import type {SyllabusItem} from '@/api/qpgApi';
type Constraints={co_id?:string|null;unit_id?:string|null;topic_id?:string|null;bloom_level?:string|null;difficulty?:string|null;question_type?:string|null};
type Child=Constraints & {id:string;marks:number|string};
type Branch=Child & {children:Child[]};
export type MainQuestion={id:string;marks:number|string;branches:Branch[];choose:1};
type Syllabus={cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]};
const input='rounded-lg border p-2 text-sm dark:bg-slate-900';
const branch=(marks:number|string):Branch=>({id:crypto.randomUUID(),marks,children:[]});
export default function QpgHierarchyEditor({mains,marks,disabled,syllabus,onChange}:{mains:MainQuestion[];marks:number|string;disabled:boolean;syllabus?:Syllabus;onChange:(value:MainQuestion[])=>void}){
 const update=(index:number,value:MainQuestion)=>onChange(mains.map((m,i)=>i===index?value:m));
 return <fieldset className="my-4 grid gap-3"><legend className="font-semibold">Main questions, OR branches and sub-questions</legend><p className="text-sm text-slate-500">Students must answer each main question and choose one OR alternative. Open a main question to set its sub-questions and requirements. Sub-question marks must add up to the alternative’s marks.</p>
 {mains.map((main,mi)=><details className="rounded-xl border p-3" key={main.id}><summary className="cursor-pointer text-sm font-semibold">Main question {mi+1} · {main.marks} marks · {main.branches.length} alternatives{main.branches.some(b=>b.children.length)?` · sub-question marks: ${main.branches.map(b=>b.children.length?b.children.map(c=>c.marks).join(" + "):b.marks).join(" OR ")}`:""}</summary>{main.branches.map((b,bi)=><section className="my-3 rounded-lg border p-3" key={b.id}><h5>Branch {String.fromCharCode(97+bi)} · {b.marks} marks</h5>{b.children.length?b.children.map((child,ci)=><div className="my-2 grid gap-2" key={child.id}><label>Child {['i','ii','iii','iv','v','vi','vii','viii','ix','x'][ci]} marks <input className={input} type="number" min="0.01" step="0.01" disabled={disabled} value={child.marks} onChange={e=>update(mi,{...main,branches:main.branches.map((v,j)=>j===bi?{...b,children:b.children.map((c,k)=>k===ci?{...c,marks:e.target.value}:c)}:v)})}/></label><NodeControls value={child} syllabus={syllabus} disabled={disabled} onChange={patch=>update(mi,{...main,branches:main.branches.map((v,j)=>j===bi?{...b,children:b.children.map((c,k)=>k===ci?{...c,...patch}:c)}:v)})}/><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>update(mi,{...main,branches:main.branches.map((v,j)=>j===bi?{...b,children:b.children.filter((_,k)=>k!==ci)}:v)})}>Remove child</Button></div>):<NodeControls value={b} syllabus={syllabus} disabled={disabled} onChange={patch=>update(mi,{...main,branches:main.branches.map((v,j)=>j===bi?{...b,...patch}:v)})}/>}<Button size="sm" variant="outline" disabled={disabled||b.children.length>=10} onClick={()=>update(mi,{...main,branches:main.branches.map((v,j)=>j===bi?{...b,children:[...b.children,{id:crypto.randomUUID(),marks:1}]}:v)})}>Add sub-question</Button><Button size="sm" variant="ghost" disabled={disabled||main.branches.length===1} onClick={()=>update(mi,{...main,branches:main.branches.filter((_,j)=>j!==bi)})}>Remove branch</Button></section>)}<Button size="sm" variant="outline" disabled={disabled||main.branches.length===2} onClick={()=>update(mi,{...main,branches:[...main.branches,branch(main.marks)]})}>Add OR branch</Button><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>onChange(mains.filter((_,i)=>i!==mi))}>Remove main question</Button></details>)}
 <Button size="sm" variant="outline" disabled={disabled||mains.length>=50} onClick={()=>onChange([...mains,{id:crypto.randomUUID(),marks,choose:1,branches:[branch(marks),branch(marks)]}])}>Add compulsory main question</Button>
 </fieldset>;
}
function NodeControls({value,syllabus,disabled,onChange}:{value:Constraints;syllabus?:Syllabus;disabled:boolean;onChange:(patch:Constraints)=>void}){
 const options:{key:keyof Constraints;title:string;values:{id:string;name:string}[]}[]=[...(['cos','units','topics'] as const).map((kind,i)=>({key:(['co_id','unit_id','topic_id'] as const)[i],title:['CO','Unit','Topic'][i],values:(syllabus?.[kind]||[]).filter(x=>kind!=='topics'||!value.unit_id||x.unit_id===value.unit_id).map(x=>({id:x.id,name:x.code+' · '+x.title}))})),{key:'bloom_level',title:'Bloom level',values:blooms.map(x=>({id:x,name:label(x)}))},{key:'difficulty',title:'Difficulty',values:difficulties.map(x=>({id:x,name:label(x)}))},{key:'question_type',title:'Question type',values:questionTypes.map(x=>({id:x,name:label(x)}))}];
 return <div className="grid gap-2 sm:grid-cols-3">{options.map(o=><label key={o.key} className="grid gap-1 text-sm">{o.title}<select aria-label={o.title} className={input} disabled={disabled} value={value[o.key]||''} onChange={e=>onChange({[o.key]:e.target.value||null,...(o.key==='unit_id'?{topic_id:null}:{})})}><option value="">Any / no restriction</option>{o.values.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}</div>;
}
