import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,questionTypes,blooms,difficulties,label} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
const input='w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
const fields=['question_text','question_type','marks','co','unit','topic','bloom_level','difficulty','answer','options','source','source_reference'];
type Content=Record<string,string|string[]>;
type ImportRow={id:string;row_number:number;location:string;content:Content;raw_values:Record<string,unknown>;errors:string[];warnings:string[];selected:boolean;removed:boolean;faculty_confirmed:boolean};
type Preview={id:string;filename:string;status:string;revision:number;columns:string[];mapping:Record<string,string>;rows:ImportRow[];processing_error:string;summary:Record<string,number>};
type Previous={id:string;filename:string;status:string};
export default function QpgImportPanel({subject,cos,units,topics,onClose}:{subject:Subject;cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[];onClose:()=>void}){
 const [preview,setPreview]=useState<Preview|null>(null);const [previous,setPrevious]=useState<Previous[]>([]);
 const [mapping,setMapping]=useState<Record<string,string>>({});const [editing,setEditing]=useState<ImportRow|null>(null);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reviewed,setReviewed]=useState(false);const [offset,setOffset]=useState(0);
 const [summary,setSummary]=useState<Record<string,number>|null>(null);
 useEffect(()=>{const c=new AbortController();qpgApi.get<{items:Previous[]}>(`imports?subject_id=${encodeURIComponent(subject.id)}`,c.signal).then(r=>setPrevious(r.items)).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[subject.id]);
 function received(next:Preview){setPreview(next);setMapping(next.mapping);setReviewed(false);if(next.status==='IMPORTED')setSummary(next.summary);}
 async function action(task:()=>Promise<void>){setBusy(true);setError('');try{await task();}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const file=data.get('file') as File;await action(async()=>{if(file.size>10*1024*1024)throw new Error('Files must be 10 MB or smaller.');received(await qpgApi.upload<Preview>(subject.id,file));setOffset(0);setSummary(null);});}
 async function saveRow(row:ImportRow,changes:Partial<ImportRow>){if(!preview)return;await action(async()=>{received(await qpgApi.save<Preview>(`imports/${preview.id}/rows/${row.id}`,{expected_revision:preview.revision,content:row.content,selected:row.selected,removed:row.removed,faculty_confirmed:row.faculty_confirmed,...changes},true));setEditing(null);});}
 const locked=preview&&['IMPORTED','FAILED','UPLOADED','PROCESSING'].includes(preview.status);
 return <Dialog title="Import Questions" onClose={onClose}>
  <p className="mb-4 text-sm text-slate-500">{subject.code} · {subject.name}. This subject applies to every imported question.</p>
  {error&&<p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}
  {!preview&&<><form onSubmit={upload} className="grid gap-4"><label className="grid gap-2 text-sm">Question document<input name="file" type="file" accept=".xlsx,.csv,.pdf,.docx" required className={input}/></label><p className="text-sm text-slate-500">Excel (.xlsx), UTF-8 CSV, text PDF or DOCX · up to 10 MB and 500 questions. You will review everything before importing.</p><Button type="submit" disabled={busy}>{busy?'Saving and extracting…':'Upload and preview'}</Button></form>{previous.length>0&&<section className="mt-6"><h3 className="font-semibold">Previous uploads for this subject</h3>{previous.map(item=><div className="mt-3 flex items-center justify-between gap-3" key={item.id}><p className="break-all text-sm">{item.filename} · {label(item.status)}</p><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(async()=>received(await qpgApi.get<Preview>(`imports/${item.id}/preview`)))}>Open</Button></div>)}</section>}</>}
  {preview&&<>
   <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="break-all text-sm"><strong>{preview.filename}</strong> · {label(preview.status)}</p><Button variant="outline" disabled={busy} onClick={()=>{setPreview(null);setSummary(null);setOffset(0);}}>Upload another file</Button></div>
   <Button variant="outline" size="sm" disabled={busy} onClick={()=>void action(async()=>{const {url}=await qpgApi.get<{url:string}>(`imports/${preview.id}/original`);window.open(url,'_blank','noopener,noreferrer');})}>View original document</Button>
   {preview.processing_error&&<p role="alert" className="my-4 text-red-700">{preview.processing_error}</p>}
   {preview.columns.length>0&&!locked&&<details className="my-4 rounded-xl border p-4" open><summary className="cursor-pointer font-semibold">Map uploaded columns</summary><p className="my-3 text-sm text-slate-500">Required: Question Text, Question Type and Marks. Applying a mapping resets row corrections and selections.</p><div className="grid gap-3 sm:grid-cols-2">{fields.map(field=><label className="grid gap-2 text-sm" key={field}>{label(field)}{['question_text','question_type','marks'].includes(field)?' *':''}<select aria-label={`Map ${label(field)}`} className={input} value={mapping[field]||''} onChange={e=>{const next={...mapping};if(e.target.value)next[field]=e.target.value;else delete next[field];setMapping(next);}}><option value="">Not mapped</option>{preview.columns.map(c=><option key={c} value={c}>{c}</option>)}</select></label>)}</div><Button className="mt-4" disabled={busy} onClick={()=>void action(async()=>received(await qpgApi.save<Preview>(`imports/${preview.id}/mapping`,{mapping,expected_revision:preview.revision},true)))}>Apply mapping</Button></details>}
   {!locked&&<div className="my-4 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void action(async()=>received(await qpgApi.save<Preview>(`imports/${preview.id}/selection`,{expected_revision:preview.revision,select_all_valid:true})))}>Select all valid</Button><Button variant="outline" disabled={busy} onClick={()=>void action(async()=>received(await qpgApi.save<Preview>(`imports/${preview.id}/validate`,{expected_revision:preview.revision})))}>Validate</Button></div>}
   {preview.rows.length>0&&<><p className="my-3 text-sm text-slate-500">{preview.rows.length} rows · {preview.summary.valid||0} valid · {preview.summary.errors||0} errors. Missing Bloom/difficulty use visible review defaults; document type suggestions need faculty review.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Select','Row','Question','Type','Marks','CO','Unit','Topic','Bloom','Difficulty','Answer','Status','Errors','Warnings','Actions'].map(h=><th className="whitespace-nowrap border-b p-2" key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.slice(offset,offset+25).map(row=><tr key={row.id} className={`border-b ${row.removed?'opacity-50':''}`}><td className="p-2"><input type="checkbox" aria-label={`Select row ${row.row_number}`} disabled={Boolean(locked)||busy||row.removed||row.errors.length>0} checked={row.selected} onChange={e=>void saveRow(row,{selected:e.target.checked})}/></td><td className="min-w-32 p-2">{row.row_number}<p className="text-xs text-slate-500">{row.location}</p></td>{['question_text','question_type','marks','co','unit','topic','bloom_level','difficulty','answer'].map(f=><td key={f} className="min-w-24 max-w-64 whitespace-pre-wrap break-words p-2">{String(row.content[f]||'—')}</td>)}<td className="p-2">{row.removed?'Skipped':row.errors.length?'Invalid':row.warnings.length?'Needs review':'Valid'}</td><td className="min-w-56 whitespace-pre-wrap p-2 text-red-700">{row.errors.join('\n')}</td><td className="min-w-56 whitespace-pre-wrap p-2 text-amber-700">{row.warnings.join('\n')}</td><td className="p-2">{!locked&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setEditing(row)}>Edit row {row.row_number}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void saveRow(row,{removed:!row.removed,selected:false})}>{row.removed?'Restore':'Remove'}</Button></div>}<details className="mt-2"><summary>Uploaded values</summary>{Object.entries(row.raw_values).filter(([k])=>!k.startsWith('__')).map(([k,v])=><p key={k}>{k}: {String(v)}</p>)}</details></td></tr>)}</tbody></table></div><div className="my-4 flex gap-2"><Button variant="outline" disabled={offset===0||busy} onClick={()=>setOffset(v=>Math.max(0,v-25))}>Previous rows</Button><Button variant="outline" disabled={offset+25>=preview.rows.length||busy} onClick={()=>setOffset(v=>v+25)}>Next rows</Button></div></>}
   {!locked&&<><label className="my-4 flex items-start gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I have reviewed the extracted questions, metadata and duplicate warnings.</label><Button disabled={busy||!reviewed||!preview.rows.some(r=>r.selected&&!r.removed)||preview.rows.some(r=>r.selected&&!r.removed&&r.errors.length>0)} onClick={()=>void action(async()=>{const result=await qpgApi.save<Record<string,number>>(`imports/${preview.id}/confirm`,{expected_revision:preview.revision,reviewed_warnings:reviewed});setSummary(result);received(await qpgApi.get<Preview>(`imports/${preview.id}/preview`));})}>{busy?'Working…':'Confirm import'}</Button></>}
   {summary&&<section role="status" className="my-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><h3 className="font-semibold">Import summary</h3><p>Imported: {summary.imported||0} · Needs Review: {summary.needs_review||0} · Skipped: {summary.skipped||0} · Errors: {summary.errors||0}</p><p>Questions were saved as Draft or Needs Review.</p><Button className="mt-3" onClick={onClose}>Back to Question Bank</Button></section>}
  </>}
  {editing&&<RowEditor key={editing.id} row={editing} cos={cos} units={units} topics={topics} busy={busy} onCancel={()=>setEditing(null)} onSave={content=>void saveRow(editing,{content,faculty_confirmed:true,selected:false})}/>}
 </Dialog>;
}
function RowEditor({row,cos,units,topics,busy,onCancel,onSave}:{row:ImportRow;cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[];busy:boolean;onCancel:()=>void;onSave:(content:Content)=>void}){
 const [content,setContent]=useState<Content>({...row.content});
 const editor=useRef<HTMLElement>(null);
 useEffect(()=>{editor.current?.querySelector<HTMLElement>('textarea,input,select')?.focus();},[]);
 function value(key:string){const v=content[key];return Array.isArray(v)?v.join('\n'):v||'';}
 function update(key:string,v:string){setContent(c=>({...c,[key]:v,...(key==='unit'?{topic:''}:{})}));}
 const unit=units.find(u=>u.code===value('unit')||u.id===value('unit')||u.title===value('unit'));
 return <section ref={editor} role="region" aria-label={`Correct row ${row.row_number}`} className="mt-6 rounded-xl border p-4"><h3 className="mb-4 font-semibold">Correct row {row.row_number}</h3><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();onSave(content);}}>{['question_text','marks','answer','source_reference','options'].map(f=><label key={f} className="grid gap-2 text-sm">{label(f)}{['question_text','answer','options'].includes(f)?<textarea className={input} aria-label={`Row ${label(f)}`} value={value(f)} onChange={e=>update(f,e.target.value)}/>:<input className={input} aria-label={`Row ${label(f)}`} value={value(f)} onChange={e=>update(f,e.target.value)}/>}</label>)}{[['question_type',questionTypes],['bloom_level',blooms],['difficulty',difficulties],['co',cos.map(c=>c.code)],['unit',units.map(u=>u.code)],['topic',topics.filter(t=>t.unit_id===unit?.id).map(t=>t.code)]].map(([field,values])=><label key={String(field)} className="grid gap-2 text-sm">{label(String(field))}<select className={input} aria-label={`Row ${label(String(field))}`} value={value(String(field))} onChange={e=>update(String(field),e.target.value)}><option value="">Not supplied</option>{(values as string[]).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}<p className="text-sm text-slate-500 sm:col-span-2">Saving confirms your corrections. Extraction and duplicate warnings remain visible for review.</p><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={busy}>Save correction</Button><Button type="button" variant="outline" disabled={busy} onClick={onCancel}>Cancel correction</Button></div></form></section>;
}
