import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {collegeError} from '@/api/collegeApi';
import {apiClient} from '@/api/apiClient';
import {qpgApi,label,questionTypes,blooms,difficulties} from '@/api/qpgApi';
import type {Subject,Question,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
type Section={id:string;name:string;offered:number;attempted:number;marks_each:string;question_type:string|null;format:string;choice_groups:{id:string;name:string;offered:number;choose:number}[]};
type Blueprint={id:string;version:number;status:string;syllabus_version_id:string;config:{title:string;duration_minutes:number;sections:Section[]}};
type Syllabus={id:string;version:number;status:string};
type Structure={cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]};
type Item={id:string;section_id:string;position:number;choice_group:string|null;snapshot:Question|null;question_version:number|null};
type Report={valid:boolean;errors:string[];checks:string[];coverage?:{kind:string;name:string;target_marks:string;minimum_marks:string;maximum_marks:string;valid:boolean}[]};
type Paper={id:string;title:string;version:number;revision:number;status:string;syllabus_version_id:string;blueprint_version:number;duration_minutes:number;blueprint_snapshot:Blueprint['config'];syllabus_snapshot:Structure;items:Item[];validation:Report;totals:{offered_marks:string;attempted_marks:string}};
type PaperSummary=Pick<Paper,'id'|'title'|'version'|'status'>;
type Availability={section_id:string;name:string;counts:Record<string,number>;available_distinct:number;required:number;sufficient:boolean};
type PickerResult={items:Question[];total:number;available_distinct:number;required:number;sufficient:boolean;counts:Record<string,number>};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgPaperPanel({subject}:{subject:Subject}){
 const [syllabuses,setSyllabuses]=useState<Syllabus[]>([]);const [blueprints,setBlueprints]=useState<Blueprint[]>([]);const [papers,setPapers]=useState<PaperSummary[]>([]);
 const [syllabus,setSyllabus]=useState('');const [blueprint,setBlueprint]=useState('');const [paper,setPaper]=useState<Paper|null>(null);const [title,setTitle]=useState('');const [slot,setSlot]=useState<Item|null>(null);
 const [availability,setAvailability]=useState<Availability[]>([]);const [canWrite,setCanWrite]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [preview,setPreview]=useState(false);
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Syllabus[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`,c.signal),qpgApi.get<{items:PaperSummary[]}>(`papers?subject_id=${subject.id}`,c.signal),qpgApi.get<{can_write:boolean}>('academic-options',c.signal)]).then(([s,b,p,a])=>{setSyllabuses(s.items);setBlueprints(b.items);setPapers(p.items);setCanWrite(a.can_write);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[subject.id]);
 async function received(next:Paper){setPaper(next);setTitle(next.title);setSlot(null);setPapers((await qpgApi.get<{items:PaperSummary[]}>(`papers?subject_id=${subject.id}`)).items);setAvailability((await qpgApi.get<{sections:Availability[]}>(`papers/${next.id}/availability`)).sections);}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){const d=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;setError(d?.errors?`${d.message} ${d.errors.join(' ')}`:collegeError(e));}finally{setBusy(false);}}
 async function save(){if(!paper)return null;const next=await qpgApi.save<Paper>(`papers/${paper.id}`,{title,expected_revision:paper.revision},true);await received(next);return next;}
 async function operation(action:string){await run(async()=>{if(!paper)return;const target=title!==paper.title?await save():paper;if(target)await received(await qpgApi.save<Paper>(`papers/${target.id}/${action}`,{expected_revision:target.revision}));});}
 return <section className="erp-card" aria-label="Paper assembly"><h2>Paper Assembly · {subject.code}</h2><p className="mb-4 text-sm text-slate-500">Choose approved questions for a published blueprint. Every allowed choice must satisfy its coverage targets.</p>
 {error&&<p role="alert" className="my-3 text-red-700">{error}</p>}
 <div className="mb-5 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>{setPaper(null);setSlot(null);setTitle('');setAvailability([]);setPreview(false);}}>New Paper</Button>{papers.map(p=><Button key={p.id} variant="outline" size="sm" disabled={busy} onClick={()=>void run(async()=>{await received(await qpgApi.get<Paper>(`papers/${p.id}`));})}>{p.title} · {label(p.status)}</Button>)}</div>
 {!paper?<><div className="grid gap-4 sm:grid-cols-2"><Select title="Paper syllabus" value={syllabus} onChange={v=>{setSyllabus(v);setBlueprint('');}} options={syllabuses.filter(s=>s.status==='PUBLISHED').map(s=>({value:s.id,name:`Syllabus v${s.version} · Published`}))}/><Select title="Published blueprint" value={blueprint} onChange={setBlueprint} options={blueprints.filter(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus).map(b=>({value:b.id,name:`${b.config.title} · v${b.version}`}))}/></div><p className="my-4 text-sm text-slate-500">Publish a syllabus and blueprint first. Draft and Needs Review questions cannot be used. Question approval is not available in this phase.</p>{canWrite&&<Button disabled={busy||!blueprint} onClick={()=>void run(async()=>{await received(await qpgApi.save<Paper>('papers',{subject_id:subject.id,syllabus_version_id:syllabus,blueprint_id:blueprint}));})}>Create Paper</Button>}</>:<>
 <div className="my-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Paper title<input aria-label="Paper title" className={input} value={title} disabled={busy||!canWrite} onChange={e=>setTitle(e.target.value)}/></label><p className="text-sm">Syllabus v{syllabuses.find(s=>s.id===paper.syllabus_version_id)?.version??'—'} · Blueprint v{paper.blueprint_version} · Paper v{paper.version}<br/>{label(paper.status)} · {paper.duration_minutes} minutes<br/><strong>Offered Marks: {paper.totals.offered_marks} · Attempted Marks: {paper.totals.attempted_marks}</strong></p></div>
 <div className="my-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setPreview(v=>!v)}>{preview?'Edit selections':'Paper Preview'}</Button>{canWrite&&<><Button disabled={busy||!title.trim()} onClick={()=>void run(async()=>{await save();})}>Save Draft</Button><Button variant="outline" disabled={busy} onClick={()=>void operation('validate')}>Validate Paper</Button><Button variant="outline" disabled={busy||paper.status!=='VALIDATED'} onClick={()=>void operation('review')}>Send for Faculty Review</Button></>}</div>
 {availability.map(a=><p key={a.section_id} className={`mb-2 text-sm ${a.sufficient?'text-slate-600':'text-amber-700'}`}>{a.name}: {a.counts.APPROVED} Approved · {a.counts.NEEDS_REVIEW} Needs Review · {a.counts.DRAFT} Draft · {a.counts.ARCHIVED} Archived. {a.available_distinct} distinct available for {a.required} remaining slots{!a.sufficient?' — Insufficient question availability':''}.</p>)}<p className="mb-4 text-xs text-slate-500">Counts are per section; overlapping candidates and combined coverage require validation.</p>
 {paper.blueprint_snapshot.sections.map(s=><section key={s.id} aria-label={s.name} className="mb-4 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">{s.name}</h3><p className="mb-3 text-sm text-slate-500">{s.offered} offered · Attempt {s.attempted} · {s.marks_each} marks each · {s.question_type?label(s.question_type):'Mixed / Any'}{s.format!=='STANDARD'?` · ${label(s.format)}`:''}</p>{paper.items.filter(i=>i.section_id===s.id).map((i,index,rows)=>{const group=s.choice_groups.find(g=>g.id===i.choice_group);return <div key={i.id} className="mb-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900">{group&&(index===0||rows[index-1].choice_group!==i.choice_group)&&<p className="mb-2 text-sm font-semibold">{group.name} · Choose {group.choose} of {group.offered}</p>}{group?.choose===1&&index>0&&rows[index-1].choice_group===i.choice_group&&<p className="mb-2 text-sm font-semibold">OR</p>}<div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">Q{i.position} · {s.marks_each} marks</p>{!preview&&canWrite&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setSlot(i)}>{i.snapshot?'Replace Question':group?'Select Alternative':'Select Question'}</Button>{i.snapshot&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(async()=>{const next=(await apiClient.delete<Paper>(`/v3/college/question-papers/papers/${paper.id}/items/${i.id}`,{data:{expected_revision:paper.revision}})).data;await received(next);})}>Remove</Button>}</div>}</div>{i.snapshot?<><p className="my-2 whitespace-pre-wrap text-sm">{i.snapshot.question_text}</p>{i.snapshot.options.map((v,j)=><p key={j} className="text-sm">{String.fromCharCode(65+j)}. {v}</p>)}<Metadata question={i.snapshot} structure={paper.syllabus_snapshot}/><p className="mt-1 text-xs text-slate-500">Selected question v{i.question_version} · {label(i.snapshot.status)}</p></>:<p className="mt-2 text-sm text-slate-500">No question selected.</p>}</div>;})}</section>)}
 {paper.validation?.errors&&<section aria-label="Paper coverage" className="my-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><h3 className="font-semibold">Coverage validation</h3>{paper.validation.errors.map(e=><p key={e} className="my-1 text-red-700">{e}</p>)}{paper.validation.checks.map(c=><p key={c}>✓ {c}</p>)}{paper.validation.coverage?.map((c,i)=><p key={i}>{c.valid?'✓':'✕'} {label(c.kind)} {c.name}: {c.minimum_marks}–{c.maximum_marks} attempted marks · target {c.target_marks}</p>)}</section>}
 {slot&&<QuestionPicker paper={paper} slot={slot} busy={busy} assignmentError={error} onClose={()=>setSlot(null)} onSelect={(question,confirmed)=>void run(async()=>{await received(await qpgApi.save<Paper>(`papers/${paper.id}/items/${slot.id}`,{question_id:question.id,expected_question_version:question.version,expected_revision:paper.revision,format_confirmed:confirmed},true));})}/>}
 </>}
 </section>;
}
function Select({title,value,onChange,options}:{title:string;value:string;onChange:(value:string)=>void;options:{value:string;name:string}[]}){return <label className="grid gap-2 text-sm">{title}<select aria-label={title} className={input} value={value} onChange={e=>onChange(e.target.value)}><option value="">All / Select</option>{options.map(o=><option key={o.value} value={o.value}>{o.name}</option>)}</select></label>;}
function Metadata({question:q,structure:s}:{question:Question;structure:Structure}){const names=[s.cos.find(x=>x.id===q.co_id),s.units.find(x=>x.id===q.unit_id),s.topics.find(x=>x.id===q.topic_id)].filter(Boolean).map(x=>x?.code+' · '+x?.title);return <p className="text-xs text-slate-500">{q.marks} marks · {label(q.question_type)} · {names.join(' / ')} · {q.bloom_level} · {label(q.difficulty)} · {q.answer?'Answer available':'No answer'} · {label(q.source_type)}{q.source_reference?` · ${q.source_reference}`:''}</p>;}
export function QuestionPicker({paper,slot,busy,assignmentError,onClose,onSelect}:{paper:Paper;slot:Item;busy:boolean;assignmentError:string;onClose:()=>void;onSelect:(q:Question,confirmed:boolean)=>void}){
 const section=paper.blueprint_snapshot.sections.find(s=>s.id===slot.section_id)!;
 const [filters,setFilters]=useState({q:'',question_type:section.question_type||'',co_id:'',unit_id:'',topic_id:'',bloom_level:'',difficulty:'',marks:String(section.marks_each)});const [offset,setOffset]=useState(0);
 const [result,setResult]=useState<PickerResult|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [confirmed,setConfirmed]=useState(false);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');const params=new URLSearchParams({item_id:slot.id,limit:'20',offset:String(offset)});Object.entries(filters).forEach(([k,v])=>{if(v)params.set(k,v);});qpgApi.get<PickerResult>(`papers/${paper.id}/eligible?${params}`,controller.signal).then(setResult).catch(e=>{if(!controller.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return ()=>{clearTimeout(timer);controller.abort();};},[filters,offset,paper.id,slot.id]);
 function change(key:keyof typeof filters,value:string){setResult(null);setLoading(true);setOffset(0);setFilters({...filters,[key]:value,...(key==='unit_id'?{topic_id:''}:{})});}
 const simple=(values:string[])=>values.map(v=>({value:v,name:label(v)}));
 return <Dialog title={`Select question · Q${slot.position}`} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">Search questions<input className={input} value={filters.q} onChange={e=>change('q',e.target.value)}/></label><Select title="Picker question type" value={filters.question_type} onChange={v=>change('question_type',v)} options={simple(questionTypes)}/>{(['cos','units','topics'] as const).map((kind,index)=>{const key=(['co_id','unit_id','topic_id'] as const)[index];return <Select key={kind} title={`Picker ${kind==='cos'?'CO':label(kind)}`} value={filters[key]} onChange={v=>change(key,v)} options={paper.syllabus_snapshot[kind].filter(x=>kind!=='topics'||!filters.unit_id||x.unit_id===filters.unit_id).map(x=>({value:x.id,name:x.code+' · '+x.title}))}/>;})}<Select title="Picker Bloom" value={filters.bloom_level} onChange={v=>change('bloom_level',v)} options={simple(blooms)}/><Select title="Picker Difficulty" value={filters.difficulty} onChange={v=>change('difficulty',v)} options={simple(difficulties)}/><label className="grid gap-2 text-sm">Picker Marks<input type="number" min="0.01" step="0.01" className={input} value={filters.marks} onChange={e=>change('marks',e.target.value)}/></label></div>
 {section.format!=='STANDARD'&&<label className="my-4 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this question is suitable for {label(section.format)}.</label>}
 {assignmentError&&<p role="alert" className="my-3 text-red-700">{assignmentError}</p>}{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{loading&&<p role="status">Loading eligible questions…</p>}{result&&!loading&&<><p className="my-4 text-sm">{result.counts.APPROVED} Approved · {result.counts.NEEDS_REVIEW} Needs Review · {result.counts.DRAFT} Draft · {result.counts.ARCHIVED} Archived</p>{!result.sufficient&&<p className="mb-3 text-sm text-amber-700">Insufficient question availability for this section with these filters: required {result.required}, available {result.available_distinct} distinct Approved questions.</p>}{result.items.map(q=><div key={q.id} className="mb-3 rounded-xl border border-slate-200 p-3"><p className="mb-2 whitespace-pre-wrap text-sm">{q.question_text}</p><Metadata question={q} structure={paper.syllabus_snapshot}/><p className="my-2 text-xs">Approved · v{q.version}</p>{q.options.map((v,i)=><p key={i} className="text-sm">{String.fromCharCode(65+i)}. {v}</p>)}<Button size="sm" disabled={busy||(section.format!=='STANDARD'&&!confirmed)} onClick={()=>onSelect(q,confirmed)}>Use Question</Button></div>)}{!result.items.length&&<p className="my-4">No eligible questions match. Add approved questions or adjust filters. No questions are automatically approved.</p>}<div className="flex gap-2"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-20))}>Previous</Button><Button variant="outline" disabled={offset+20>=result.total} onClick={()=>setOffset(v=>v+20)}>Next</Button></div></>}
 </Dialog>;
}
