import QpgAiBuildPanel from './QpgAiBuildPanel';
import QpgValidationPanel from './QpgValidationPanel';
import QpgExportPanel from './QpgExportPanel';
import QpgBlueprintIntelligencePanel from './QpgBlueprintIntelligencePanel';
import QpgPaperIntelligencePanel from './QpgPaperIntelligencePanel';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {collegeError} from '@/api/collegeApi';
import {apiClient} from '@/api/apiClient';
import {qpgApi,label,questionTypes,blooms,difficulties} from '@/api/qpgApi';
import type {Subject,Question,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
type Section={id:string;name:string;offered:number;attempted:number;marks_each:string;question_type:string|null;format:string;choice_groups:{id:string;name:string;offered:number;choose:number}[]};
type Blueprint={id:string;version:number;status:string;syllabus_version_id:string;config:{title:string;duration_minutes:number;sections:Section[]}};
type Syllabus={id:string;version:number;status:string};
type Structure={cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[]};
type Item={id:string;section_id:string;position:number;choice_group:string|null;snapshot:Question|null;question_version:number|null};
type Report={valid:boolean;errors:string[];checks:string[];coverage?:{kind:string;name:string;target_marks:string;minimum_marks:string;maximum_marks:string;valid:boolean}[]};
type History={id:string;revision:number;action:string;actor:string;comment:string;created_at:string;has_snapshot:boolean};
type Paper={structure?:{position:number;label:string;marks:string;branch_id:string;branch_label:string;child_label:string;constraints:Record<string,string|null>}[];metadata?:{instructions?:string;examination_session?:string;subject_name?:string;subject_code?:string};id:string;title:string;version:number;revision:number;status:string;syllabus_version_id:string;blueprint_version:number;duration_minutes:number;blueprint_snapshot:Blueprint['config'];syllabus_snapshot:Structure;items:Item[];validation:Report;totals:{offered_marks:string;attempted_marks:string}};
type PaperSummary=Pick<Paper,'id'|'title'|'version'|'status'>;
type Availability={section_id:string;name:string;counts:Record<string,number>;available_distinct:number;required:number;sufficient:boolean|null};
type PickerResult={items:Question[];total:number;available_distinct:number;required:number;sufficient:boolean;counts:Record<string,number>};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgPaperPanel({subject,onReview,onCreate,onPatterns,view='create'}:{subject:Subject;onReview?:()=>void;onCreate?:()=>void;onPatterns?:()=>void;view?:'create'|'drafts'|'review'|'final'}){
 const [syllabuses,setSyllabuses]=useState<Syllabus[]>([]);const [blueprints,setBlueprints]=useState<Blueprint[]>([]);const [papers,setPapers]=useState<PaperSummary[]>([]);
 const [syllabus,setSyllabus]=useState('');const [blueprint,setBlueprint]=useState('');const [paper,setPaper]=useState<Paper|null>(null);const [title,setTitle]=useState('');const [slot,setSlot]=useState<Item|null>(null);
 const [examinationSession,setExaminationSession]=useState('');const [instructions,setInstructions]=useState('');const [comment,setComment]=useState('');const [history,setHistory]=useState<History[]>([]);const [historical,setHistorical]=useState(false);
 function canEdit(){return canWrite&&!historical&&!!paper&&!['APPROVED','LOCKED'].includes(paper.status);}
 const [availability,setAvailability]=useState<Availability[]>([]);const [canWrite,setCanWrite]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [preview,setPreview]=useState(false);
 const editable=canEdit();
 const visiblePapers=papers.filter(p=>view==='create'||(view==='drafts'?['DRAFT','VALIDATED','CHANGES_REQUESTED','REJECTED']:view==='review'?['FACULTY_REVIEW']:['APPROVED','LOCKED']).includes(p.status));
 useEffect(()=>{const c=new AbortController();Promise.all([qpgApi.get<{items:Syllabus[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal),qpgApi.get<{items:Blueprint[]}>(`blueprints?subject_id=${subject.id}`,c.signal),qpgApi.get<{items:PaperSummary[]}>(`papers?subject_id=${subject.id}`,c.signal),qpgApi.get<{can_write:boolean}>('academic-options',c.signal)]).then(([s,b,p,a])=>{setSyllabuses(s.items);setBlueprints(b.items);setPapers(p.items);setCanWrite(a.can_write);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[subject.id]);
 async function received(next:Paper){setHistorical(false);setComment('');setPaper(next);setTitle(next.title);setInstructions(next.metadata?.instructions||'');setExaminationSession(next.metadata?.examination_session||'');setHistory((await qpgApi.get<{items:History[]}>(`papers/${next.id}/history`)).items||[]);setSlot(null);setPapers((await qpgApi.get<{items:PaperSummary[]}>(`papers?subject_id=${subject.id}`)).items);setAvailability((await qpgApi.get<{sections:Availability[]}>(`papers/${next.id}/availability`)).sections);}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){const response=(e as {response?:{data?:unknown}}).response;if(response?.data instanceof Blob){try{response.data=JSON.parse(await response.data.text());}catch{/* Keep the existing generic error message for non-JSON responses. */}}const d=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;setError(d?.errors?`${d.message} ${d.errors.join(' ')}`:collegeError(e));}finally{setBusy(false);}}
 async function save(){if(!paper)return null;const next=await qpgApi.save<Paper>(`papers/${paper.id}`,{title,instructions,examination_session:examinationSession,expected_revision:paper.revision},true);await received(next);return next;}
 async function operation(action:string){await run(async()=>{if(!paper)return;const target=(title!==paper.title||instructions!==(paper.metadata?.instructions||'')||examinationSession!==(paper.metadata?.examination_session||''))?await save():paper;if(target)await received(await qpgApi.save<Paper>(`papers/${target.id}/${action}`,{expected_revision:target.revision,...(['approve','request-changes','reject','comments'].includes(action)?{comment}:{})}));});}
 return <section className="erp-card" aria-label="Paper assembly"><h2>Question Papers · {subject.name} ({subject.code})</h2><p className="mb-4 text-sm text-slate-500">Choose your syllabus and paper pattern, fill each question space, then check the paper and send it for review.</p>
 {error&&<p role="alert" className="my-3 text-red-700">{error}</p>}
 <div className="mb-5 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>{onCreate?.();setPaper(null);setSlot(null);setTitle('');setAvailability([]);setPreview(false);}}>New Paper</Button>{visiblePapers.map(p=><Button key={p.id} variant="outline" size="sm" disabled={busy} onClick={()=>void run(async()=>{await received(await qpgApi.get<Paper>(`papers/${p.id}`));})}>{p.title} · {label(p.status)}</Button>)}</div>
 {!paper&&view!=='create'?<div className="rounded-xl border border-dashed border-slate-200 p-8 text-center"><h3 className="font-semibold">{visiblePapers.length?'Choose a paper to continue':view==='drafts'?'No draft papers yet':view==='review'?'No papers awaiting review':'No final papers yet'}</h3><p className="mt-2 text-sm text-slate-500">{visiblePapers.length?'Select a paper from the list above.':view==='drafts'?'Create a paper and save your progress here.':view==='review'?'Complete your paper, check it, then send it for faculty review.':'Approved and locked papers will appear here.'}</p></div>:!paper?<><div className="grid gap-4 sm:grid-cols-2"><Select title="Paper syllabus" value={syllabus} onChange={v=>{setSyllabus(v);setBlueprint('');}} options={syllabuses.filter(s=>s.status==='PUBLISHED').map(s=>({value:s.id,name:`${subject.name} (${subject.code}) — Version ${s.version} · Published`}))}/><Select title="Published paper pattern" disabled={!syllabus||!blueprints.some(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus)} placeholder={!syllabus?'Select a syllabus first':!blueprints.some(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus)?'No published pattern available':'Select a paper pattern'} value={blueprint} onChange={setBlueprint} options={blueprints.filter(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus).map(b=>({value:b.id,name:`${b.config.title} · v${b.version}`}))}/></div><p className="my-4 text-sm text-slate-500">{!syllabuses.some(s=>s.status==='PUBLISHED')?'Publish your syllabus in Syllabus Master first.':syllabus&&!blueprints.some(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus)?'No published pattern matches this syllabus. Create and publish one in Paper Patterns.':'Select a published syllabus and a matching paper pattern.'}  Only approved questions can be added to your paper.</p>{syllabus&&!blueprints.some(b=>b.status==='PUBLISHED'&&b.syllabus_version_id===syllabus)&&onPatterns&&<div className="mb-4 rounded-xl border border-indigo-200 bg-indigo-50 p-4 dark:bg-indigo-950"><p className="mb-3 text-sm">Choose a university starting pattern, select this published syllabus, then save and publish the pattern.</p><Button variant="outline" onClick={onPatterns}>Open Paper Patterns</Button></div>}{canWrite&&<Button disabled={busy||!blueprint} onClick={()=>void run(async()=>{await received(await qpgApi.save<Paper>('papers',{subject_id:subject.id,syllabus_version_id:syllabus,blueprint_id:blueprint}));})}>Create Paper</Button>}{blueprint&&<QpgBlueprintIntelligencePanel key={blueprint} subject={subject} blueprintId={blueprint} canWrite={canWrite} onReview={onReview}/>}</>:<>
 <section aria-label="Paper progress" className="my-4 rounded-xl bg-indigo-50 p-4 dark:bg-indigo-950"><h3 className="font-semibold">Your next step</h3><p className="mt-2 text-sm">{historical?'You are viewing a saved historical paper.':paper.status==='LOCKED'?'Your paper is finalized. Download the student paper and answer key below.':paper.status==='APPROVED'?'Finalize and lock this approved paper to enable official downloads.':paper.status==='FACULTY_REVIEW'?'The paper is ready for a faculty decision. Review it, then approve or request changes.':paper.items.some(i=>!i.snapshot)?`Add approved questions to the ${paper.items.filter(i=>!i.snapshot).length} empty question spaces below.`:paper.status==='VALIDATED'?'Checks passed. Send the paper for faculty review.':'All question spaces are filled. Save your draft and select Check Paper.'}</p></section>
 {editable&&!historical&&<QpgAiBuildPanel key={paper.id} paperId={paper.id} revision={paper.revision} emptyCount={paper.items.filter(i=>!i.snapshot).length} syllabus={paper.syllabus_snapshot} onReview={()=>onReview?.()} onAssembled={async()=>{await received(await qpgApi.get<Paper>(`papers/${paper.id}`));}}/>}
 <div className="my-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Paper title<input aria-label="Paper title" className={input} value={title} disabled={busy||!editable} onChange={e=>setTitle(e.target.value)}/></label><p className="text-sm">{paper.metadata?.subject_name||subject.name} · {paper.metadata?.subject_code||subject.code}<br/>Syllabus v{syllabuses.find(s=>s.id===paper.syllabus_version_id)?.version??'—'} · Paper Pattern v{paper.blueprint_version} · Paper v{paper.version}<br/>{label(paper.status)} · {paper.duration_minutes} minutes<br/><strong>Offered Marks: {paper.totals.offered_marks} · Attempted Marks: {paper.totals.attempted_marks}</strong></p></div>
 <div className="my-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setPreview(v=>!v)}>{preview?(editable?'Back to questions':'Back to paper'):'Paper Preview'}</Button>{editable&&<><Button variant="outline" disabled={busy||!title.trim()} onClick={()=>void run(async()=>{await save();})}>Save Draft</Button><Button variant={paper.status==='VALIDATED'?'outline':'default'} disabled={busy} onClick={()=>void operation('validate')}>Check Paper</Button><Button variant={paper.status==='VALIDATED'?'default':'outline'} disabled={busy||paper.status!=='VALIDATED'} onClick={()=>void operation('review')}>Send for Faculty Review</Button></>}</div>
 <div className="my-4 grid gap-3"><label className="grid gap-2 text-sm">Examination session<input aria-label="Examination session" className={input} maxLength={120} value={examinationSession} disabled={busy||!editable} onChange={e=>setExaminationSession(e.target.value)}/></label><label className="grid gap-2 text-sm">Paper instructions<textarea aria-label="Paper instructions" className={input} value={instructions} disabled={busy||!editable} onChange={e=>setInstructions(e.target.value)}/></label><Button variant="outline" onClick={()=>setPreview(true)}>Final Review</Button>
 {editable&&<label className="grid gap-2 text-sm">Review comment<textarea aria-label="Review comment" className={input} value={comment} onChange={e=>setComment(e.target.value)}/></label>}
 <div className="flex flex-wrap gap-2">{editable&&paper.status==='FACULTY_REVIEW'&&<><Button disabled={busy} onClick={()=>void operation('approve')}>Approve Paper</Button><Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>void operation('request-changes')}>Request Changes</Button><Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>void operation('reject')}>Reject Paper</Button></>}{editable&&<Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>void operation('comments')}>Save Comment</Button>}
 {canWrite&&!historical&&paper.status==='APPROVED'&&<Button disabled={busy} onClick={()=>void operation('lock')}>Finalize and Lock</Button>}
 {canWrite&&!historical&&['APPROVED','LOCKED'].includes(paper.status)&&<Button variant="outline" disabled={busy} onClick={()=>void operation('new-version')}>Create New Version</Button>}
 {paper.status==='LOCKED'&&<Button disabled={busy} onClick={()=>void run(async()=>{const result=await apiClient.get<Blob>(`/v3/college/question-papers/papers/${paper.id}/export?revision=${paper.revision}`,{responseType:'blob'});const url=URL.createObjectURL(result.data);const a=document.createElement('a');a.href=url;a.download=`question-paper-v${paper.version}-r${paper.revision}.pdf`;a.click();URL.revokeObjectURL(url);setHistory((await qpgApi.get<{items:History[]}>(`papers/${paper.id}/history`)).items);})}>Export PDF</Button>}</div>
 {['APPROVED','LOCKED'].includes(paper.status)&&<p className="text-sm text-slate-500">{label(paper.status)} · This version is read-only. Create a new version to make changes.</p>}
 <details><summary className="cursor-pointer font-semibold">Revision History</summary>{historical&&<Button variant="outline" onClick={()=>void run(async()=>{await received(await qpgApi.get<Paper>(`papers/${paper.id}`));})}>Return to Current Revision</Button>}{history.map(h=><div key={h.id} className="my-2 rounded-xl border border-slate-200 p-3 text-sm"><p>{label(h.action)} · Revision {h.revision} · {h.actor} · {new Date(h.created_at).toLocaleString()}</p>{h.comment&&<p>{h.comment}</p>}{h.has_snapshot&&<Button variant="outline" size="sm" onClick={()=>void run(async()=>{const old=await qpgApi.get<Paper>(`papers/${paper.id}/revisions/${h.revision}`);setPaper(old);setTitle(old.title);setInstructions(old.metadata?.instructions||'');setHistorical(true);setPreview(true);setSlot(null);})}>View Revision {h.revision}</Button>}</div>)}</details>{historical&&<p className="text-sm font-semibold">Historical revision · Read-only</p>}
 </div>
 {!historical&&availability.map(a=><p key={a.section_id} className={`mb-2 text-sm ${a.sufficient?'text-slate-600':'text-amber-700'}`}>{a.name}: {a.counts.APPROVED} Approved · {a.counts.NEEDS_REVIEW} Needs Review · {a.counts.DRAFT} Draft · {a.counts.ARCHIVED} Archived. {a.available_distinct} distinct available for {a.required} remaining slots{a.sufficient===null?' — Check each leaf contract or Blueprint Analysis':!a.sufficient?' — Insufficient question availability':''}.</p>)}<p className="mb-4 text-xs text-slate-500">Counts are per section; overlapping candidates and combined coverage require validation.</p>
 {paper.blueprint_snapshot.sections.map(s=><section key={s.id} aria-label={s.name} className="mb-4 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">{s.name}</h3>{paper.structure?.some(n=>paper.items.some(i=>i.section_id===s.id&&i.position===n.position))&&<p className="my-2 text-sm">Answer ALL questions. Choose ONE alternative from each OR pair.</p>}<p className="mb-3 text-sm text-slate-500">{s.offered} offered · Attempt {s.attempted} · {s.marks_each} marks each · {s.question_type?label(s.question_type):'Mixed / Any'}{s.format!=='STANDARD'?` · ${label(s.format)}`:''}</p>{paper.items.filter(i=>i.section_id===s.id).map((i,index,rows)=>{const group=s.choice_groups.find(g=>g.id===i.choice_group);const node=paper.structure?.find(n=>n.position===i.position);const prior=index?paper.structure?.find(n=>n.position===rows[index-1].position):null;return <div key={i.id} className="mb-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900">{group&&(index===0||rows[index-1].choice_group!==i.choice_group)&&<p className="mb-2 text-sm font-semibold">{group.name} · Choose {group.choose} of {group.offered}</p>}{group?.choose===1&&index>0&&rows[index-1].choice_group===i.choice_group&&<p className="mb-2 text-sm font-semibold">OR</p>}{node?.branch_label==='b'&&node.branch_id!==prior?.branch_id&&<p className="my-2 font-semibold">OR</p>}<div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">Q{paper.structure?.find(n=>n.position===i.position)?.label||i.position} · {paper.structure?.find(n=>n.position===i.position)?.marks||s.marks_each} marks</p>{!preview&&editable&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setSlot(i)}>{i.snapshot?'Replace Question':group?'Select Alternative':'Select Question'}</Button>{i.snapshot&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(async()=>{const next=(await apiClient.delete<Paper>(`/v3/college/question-papers/papers/${paper.id}/items/${i.id}`,{data:{expected_revision:paper.revision}})).data;await received(next);})}>Remove</Button>}</div>}</div>{i.snapshot?<><p className="my-2 whitespace-pre-wrap text-sm">{i.snapshot.question_text}</p>{i.snapshot.options.map((v,j)=><p key={j} className="text-sm">{String.fromCharCode(65+j)}. {v}</p>)}<Metadata question={i.snapshot} structure={paper.syllabus_snapshot}/><p className="mt-1 text-xs text-slate-500">Selected question v{i.question_version} · {label(i.snapshot.status)}</p>{node&&!preview&&<LeafValidation question={i.snapshot} version={i.question_version||i.snapshot.version} canWrite={canWrite} historical={historical}/>}</>:<p className="mt-2 text-sm text-slate-500">No question selected.</p>}</div>;})}</section>)}
 {paper.status==='LOCKED'&&<QpgExportPanel key={paper.id+':'+paper.revision} paper={paper} canWrite={canWrite}/>}
 {!historical&&<QpgBlueprintIntelligencePanel key={paper.id+':'+paper.revision} subject={subject} paperId={paper.id} revision={paper.revision} canWrite={editable} onReview={onReview} onUse={editable?async(slotId,questionId,questionVersion,confirmed)=>{await received(await qpgApi.save<Paper>(`papers/${paper.id}/items/${slotId}`,{question_id:questionId,expected_question_version:questionVersion,expected_revision:paper.revision,format_confirmed:confirmed},true));}:undefined}/>}
 {!historical&&<details className="my-4 rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Advanced: similarity with other papers</summary><QpgPaperIntelligencePanel paperId={paper.id} revision={paper.revision}/></details>}
 {paper.validation?.errors&&<section aria-label="Paper coverage" className="my-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><h3 className="font-semibold">Coverage validation</h3>{paper.validation.errors.map(e=><p key={e} className="my-1 text-red-700">{e}</p>)}{paper.validation.checks.map(c=><p key={c}>✓ {c}</p>)}{paper.validation.coverage?.map((c,i)=><p key={i}>{c.valid?'✓':'✕'} {label(c.kind)} {c.name}: {c.minimum_marks}–{c.maximum_marks} attempted marks · target {c.target_marks}</p>)}</section>}
 {slot&&<QuestionPicker paper={paper} slot={slot} busy={busy} assignmentError={error} onClose={()=>setSlot(null)} onSelect={(question,confirmed)=>void run(async()=>{await received(await qpgApi.save<Paper>(`papers/${paper.id}/items/${slot.id}`,{question_id:question.id,expected_question_version:question.version,expected_revision:paper.revision,format_confirmed:confirmed},true));})}/>}
 </>}
 </section>;
}
function Select({title,value,onChange,options,disabled=false,placeholder="Select"}:{title:string;value:string;onChange:(value:string)=>void;options:{value:string;name:string}[];disabled?:boolean;placeholder?:string}){return <label className="grid gap-2 text-sm">{title}<select aria-label={title} disabled={disabled} className={input} value={value} onChange={e=>onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(o=><option key={o.value} value={o.value}>{o.name}</option>)}</select></label>;}
function Metadata({question:q,structure:s}:{question:Question;structure:Structure}){const names=[s.cos.find(x=>x.id===q.co_id),s.units.find(x=>x.id===q.unit_id),s.topics.find(x=>x.id===q.topic_id)].filter(Boolean).map(x=>x?.code+' · '+x?.title);return <p className="text-xs text-slate-500">{q.marks} marks · {label(q.question_type)} · {names.join(' / ')} · {q.bloom_level} · {label(q.difficulty)} · {q.answer?'Answer available':'No answer'} · {label(q.source_type)}{q.source_reference?` · ${q.source_reference}`:''}</p>;}
export function QuestionPicker({paper,slot,busy,assignmentError,onClose,onSelect}:{paper:Paper;slot:Item;busy:boolean;assignmentError:string;onClose:()=>void;onSelect:(q:Question,confirmed:boolean)=>void}){
 const section=paper.blueprint_snapshot.sections.find(s=>s.id===slot.section_id)!;
 const [filters,setFilters]=useState({q:'',question_type:section.question_type||'',co_id:'',unit_id:'',topic_id:'',bloom_level:'',difficulty:'',marks:String(paper.structure?.find(n=>n.position===slot.position)?.marks||section.marks_each)});const [offset,setOffset]=useState(0);
 const [result,setResult]=useState<PickerResult|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [confirmed,setConfirmed]=useState(false);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');const params=new URLSearchParams({item_id:slot.id,limit:'20',offset:String(offset)});Object.entries(filters).forEach(([k,v])=>{if(v)params.set(k,v);});qpgApi.get<PickerResult>(`papers/${paper.id}/eligible?${params}`,controller.signal).then(setResult).catch(e=>{if(!controller.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return ()=>{clearTimeout(timer);controller.abort();};},[filters,offset,paper.id,slot.id]);
 function change(key:keyof typeof filters,value:string){setResult(null);setLoading(true);setOffset(0);setFilters({...filters,[key]:value,...(key==='unit_id'?{topic_id:''}:{})});}
 const simple=(values:string[])=>values.map(v=>({value:v,name:label(v)}));
 return <Dialog title={`Select question · Q${paper.structure?.find(n=>n.position===slot.position)?.label||slot.position}`} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">Search questions<input className={input} value={filters.q} onChange={e=>change('q',e.target.value)}/></label><Select title="Picker question type" value={filters.question_type} onChange={v=>change('question_type',v)} options={simple(questionTypes)}/>{(['cos','units','topics'] as const).map((kind,index)=>{const key=(['co_id','unit_id','topic_id'] as const)[index];return <Select key={kind} title={`Picker ${kind==='cos'?'CO':label(kind)}`} value={filters[key]} onChange={v=>change(key,v)} options={paper.syllabus_snapshot[kind].filter(x=>kind!=='topics'||!filters.unit_id||x.unit_id===filters.unit_id).map(x=>({value:x.id,name:x.code+' · '+x.title}))}/>;})}<Select title="Picker Bloom" value={filters.bloom_level} onChange={v=>change('bloom_level',v)} options={simple(blooms)}/><Select title="Picker Difficulty" value={filters.difficulty} onChange={v=>change('difficulty',v)} options={simple(difficulties)}/><label className="grid gap-2 text-sm">Picker Marks<input type="number" min="0.01" step="0.01" className={input} value={filters.marks} onChange={e=>change('marks',e.target.value)}/></label></div>
 {section.format!=='STANDARD'&&<label className="my-4 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this question is suitable for {label(section.format)}.</label>}
 {assignmentError&&<p role="alert" className="my-3 text-red-700">{assignmentError}</p>}{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{loading&&<p role="status">Loading eligible questions…</p>}{result&&!loading&&<><p className="my-4 text-sm">{result.counts.APPROVED} Approved · {result.counts.NEEDS_REVIEW} Needs Review · {result.counts.DRAFT} Draft · {result.counts.ARCHIVED} Archived</p>{!result.sufficient&&<p className="mb-3 text-sm text-amber-700">Insufficient question availability for this section with these filters: required {result.required}, available {result.available_distinct} distinct Approved questions.</p>}{result.items.map(q=><div key={q.id} className="mb-3 rounded-xl border border-slate-200 p-3"><p className="mb-2 whitespace-pre-wrap text-sm">{q.question_text}</p><Metadata question={q} structure={paper.syllabus_snapshot}/><p className="my-2 text-xs">Approved · v{q.version}</p>{q.options.map((v,i)=><p key={i} className="text-sm">{String.fromCharCode(65+i)}. {v}</p>)}<Button size="sm" disabled={busy||(section.format!=='STANDARD'&&!confirmed)} onClick={()=>onSelect(q,confirmed)}>Use Question</Button></div>)}{!result.items.length&&<p className="my-4">No eligible questions match. Add approved questions or adjust filters. No questions are automatically approved.</p>}<div className="flex gap-2"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-20))}>Previous</Button><Button variant="outline" disabled={offset+20>=result.total} onClick={()=>setOffset(v=>v+20)}>Next</Button></div></>}
 </Dialog>;
}

function LeafValidation({question,version,canWrite,historical}:{question:Question;version:number;canWrite:boolean;historical:boolean}){const [open,setOpen]=useState(false);return <div className="my-2"><Button variant="outline" size="sm" onClick={()=>setOpen(v=>!v)}>{open?'Hide leaf validation':'View leaf validation'}</Button>{open&&<QpgValidationPanel questionId={question.id} version={version} canWrite={canWrite} archived={historical||question.status==='ARCHIVED'}/>}</div>;}
