import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
type Match={position:number;matched_position?:number;classification:string;similarity:number|null;question_version:number;matched_question_version:number;matched_question_text:string;previous_paper_title?:string;previous_paper_version?:number;previous_paper_revision?:number};
type Analysis={matches:Match[];topic_warnings?:{topic:string;count:number;message:string}[];repeated_topics?:{topic:string;previous_uses:number}[];semantic_available:boolean;truncated:boolean;revision:number};
export default function QpgPaperIntelligencePanel({paperId,revision}:{paperId:string;revision:number}){
 const [current,setCurrent]=useState<Analysis|null>(null),[previous,setPrevious]=useState<Analysis|null>(null),[broad,setBroad]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const c=new AbortController();void Promise.resolve().then(async()=>{if(c.signal.aborted)return;setCurrent(null);setPrevious(null);setError('');setBusy(true);await Promise.all([qpgApi.get<Analysis>(`papers/${paperId}/similarity`,c.signal),qpgApi.get<Analysis>(`papers/${paperId}/previous-paper-similarity?same_syllabus=${!broad}`,c.signal)]).then(([a,b])=>{if(a.revision!==revision||b.revision!==revision){setError('Paper changed during comparison. Refresh to inspect the current revision.');return;}setCurrent(a);setPrevious(b);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});});return()=>c.abort();},[paperId,revision,broad,refresh]);
 function rows(result:Analysis|null){return (result?.matches||[]).map((m,i)=><article className="my-2 rounded-lg border border-amber-200 p-3 text-sm" key={i}><p className="font-medium">Q{m.position} · {label(m.classification)}{m.similarity!==null?` · Cosine ${m.similarity.toFixed(3)}`:''}</p><p>{m.matched_question_text}</p><p className="text-xs text-slate-500">Question v{m.question_version} compared with v{m.matched_question_version}{m.previous_paper_title?` · ${m.previous_paper_title} · Paper v${m.previous_paper_version} / revision ${m.previous_paper_revision}`:` · Q${m.matched_position}`}</p></article>);}
 return <section aria-label="Advisory paper repetition" className="my-4 rounded-xl border border-amber-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Advisory Repetition Warnings</h3><Button variant="outline" disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Check Repetition</Button></div><p className="my-2 text-sm text-slate-500">Warnings inform faculty decisions. They do not block validation, approval or locking.</p><label className="my-2 flex gap-2 text-sm"><input type="checkbox" checked={broad} onChange={e=>setBroad(e.target.checked)}/>Include previous syllabus versions in this subject</label>{busy&&<p role="status" className="text-sm">Comparing selected question snapshots…</p>}{error&&<p className="text-sm text-amber-700">Comparison unavailable: {error} Existing paper actions remain available.</p>}{current&&<><h4 className="mt-3 font-semibold">This Paper</h4>{!current.semantic_available&&<p className="text-sm text-amber-700">Semantic comparison unavailable or incomplete; exact checks remain available.</p>}{rows(current)}{!(current.matches||[]).length&&<p className="text-sm">{current.semantic_available?'No matching questions in the compared selections.':'No exact matches found. Semantic comparison is incomplete.'}</p>}{(current.topic_warnings||[]).map((t,i)=><p className="my-2 text-sm text-amber-700" key={i}>{t.topic} · {t.count} selections · {t.message}</p>)}</>}{previous&&<><h4 className="mt-3 font-semibold">Previous Paper Similarity</h4>{rows(previous)}{!(previous.matches||[]).length&&<p className="text-sm">{previous.semantic_available?'No matching questions in the compared finalized papers.':'No exact matches found. Semantic comparison is incomplete.'}</p>}{(previous.repeated_topics||[]).map((t,i)=><p className="my-2 text-sm" key={i}>{t.topic} · {t.previous_uses} previous offered selections</p>)}</>}{(current?.truncated||previous?.truncated)&&<p className="mt-2 text-sm text-amber-700">Comparison reached its limit. Results describe the compared sample.</p>}</section>;
}
