import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import type {Question} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
type Match={classification:string;similarity:number|null;query_version:number;question:Pick<Question,'id'|'question_text'|'question_type'|'marks'|'bloom_level'|'difficulty'|'status'|'version'|'source_type'|'source_reference'|'created_at'>&{mapping?:Record<string,{code:string;title:string}|null>}};
type Similarity={matches:Match[];message:string;complete:boolean;missing_embeddings:number;truncated:boolean;counts:Record<string,number>;threshold_note?:string;novelty?:{score:number|null;label:string;formula:string}};
type Usage={times_used:number;number_of_papers:number;number_of_paper_revisions:number;first_used_date:string|null;last_used_date:string|null;history:{paper_title:string;paper_version:number;question_version:number;revision:number;used_at:string}[]};
type Index={question_version:number;status:string;stale:boolean;failure_reason:string;model:string;model_revision:string;dimension:number|null};
const input='rounded-xl border bg-white p-2 text-sm dark:bg-slate-900';
export default function QpgQuestionIntelligencePanel({question,canWrite}:{question:Question;canWrite:boolean}){
 const [comparison,setComparison]=useState('TOPIC'),[sameType,setSameType]=useState(false),[sameMarks,setSameMarks]=useState(false),[approved,setApproved]=useState(false);
 const [similar,setSimilar]=useState<Similarity|null>(null),[usage,setUsage]=useState<Usage|null>(null),[history,setHistory]=useState<Index[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[poll,setPoll]=useState(false);
 const params=new URLSearchParams({comparison_scope:comparison,same_type:String(sameType),same_marks:String(sameMarks),approved_only:String(approved)}).toString();
 useEffect(()=>{setSimilar(null);setUsage(null);setHistory([]);setError('');setPoll(false);},[question.id,question.version,params]);
 useEffect(()=>{if(!poll)return;const c=new AbortController();const timer=setInterval(()=>{void qpgApi.get<{items:Index[]}>(`questions/${question.id}/embedding-history`,c.signal).then(r=>{setHistory(r.items||[]);if(!(r.items||[]).some(i=>!i.stale&&['QUEUED','RUNNING'].includes(i.status))){setPoll(false);return qpgApi.get<Similarity>(`questions/${question.id}/similar?${params}`,c.signal).then(setSimilar);}}).catch(e=>{if(!c.signal.aborted){setError(collegeError(e));setPoll(false);}});},1000);return()=>{clearInterval(timer);c.abort();};},[poll,question.id,params]);
 async function find(){setBusy(true);setError('');try{setSimilar(await qpgApi.get<Similarity>(`questions/${question.id}/similar?${params}`));setHistory((await qpgApi.get<{items:Index[]}>(`questions/${question.id}/embedding-history`)).items||[]);}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function index(){setBusy(true);setError('');try{await qpgApi.save(`questions/${question.id}/similarity-check`,{expected_version:question.version,comparison_scope:comparison,same_type:sameType,same_marks:sameMarks,approved_only:approved});setPoll(true);}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function loadUsage(){setBusy(true);setError('');try{const r=await qpgApi.get<{items:Usage[]}>(`questions/usage?${new URLSearchParams({subject_id:question.subject_id,question_id:question.id})}`);setUsage(r.items?.[0]||null);}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 return <section aria-label="Duplicate / Similarity Analysis" className="my-5 rounded-xl border p-4"><h3 className="font-semibold">Duplicate / Similarity Analysis</h3><p className="my-2 text-sm text-slate-500">Advisory comparisons. Similarity does not prove duplication or change faculty decisions.</p><div className="my-3 flex flex-wrap gap-3"><label className="grid gap-1 text-sm">Similarity scope<select aria-label="Similarity scope" className={input} disabled={busy||poll} value={comparison} onChange={e=>setComparison(e.target.value)}>{[['TOPIC','Same Topic'],['UNIT','Same Unit'],['CO','Same CO'],['SYLLABUS','Same Published Syllabus'],['SUBJECT','Broader Subject']].map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={busy||poll} checked={sameType} onChange={e=>setSameType(e.target.checked)}/>Same question type</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={busy||poll} checked={sameMarks} onChange={e=>setSameMarks(e.target.checked)}/>Same marks</label><label className="grid gap-1 text-sm">Similarity status<select aria-label="Similarity status" className={input} disabled={busy||poll} value={approved?'approved':'all'} onChange={e=>setApproved(e.target.value==='approved')}><option value="all">All non-archived</option><option value="approved">Approved only</option></select></label></div>
 <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void find()}>Find Similar Questions</Button>{canWrite&&question.status!=='ARCHIVED'&&<Button variant="outline" disabled={busy||poll} onClick={()=>void index()}>Index / Refresh Similarity</Button>}<Button variant="outline" disabled={busy} onClick={()=>void loadUsage()}>View Usage</Button></div>{poll&&<p role="status" className="my-2 text-sm">Semantic indexing in progress…</p>}{error&&<p className="my-2 text-sm text-amber-700">{error} Faculty review remains available.</p>}
 {similar&&<><p className="my-3 text-sm">{similar.message}</p>{similar.threshold_note&&<p className="text-xs text-slate-500">{similar.threshold_note}</p>}{!similar.complete&&<p className="text-sm text-amber-700">Partial comparison: {similar.missing_embeddings||0} missing or stale embeddings{similar.truncated?' · candidate limit reached':''}.</p>}<p className="my-2 text-sm">Exact duplicates: {similar.counts?.EXACT_DUPLICATE||0} · Highly similar: {(similar.counts?.NEAR_DUPLICATE||0)+(similar.counts?.HIGHLY_SIMILAR||0)} · Related: {similar.counts?.RELATED||0}</p>{similar.novelty&&<details className="my-2 text-sm"><summary>Advisory novelty: {similar.novelty.score??'Unavailable'} · {similar.novelty.label}</summary><p>{similar.novelty.formula}</p></details>}{(similar.matches||[]).map(m=><article key={m.question.id} className="my-3 rounded-lg border p-3 text-sm"><p className="font-medium">{label(m.classification)} · {m.similarity===null?'Exact text signal':`Cosine ${m.similarity.toFixed(3)}`}</p><p className="my-2 whitespace-pre-wrap">{m.question.question_text}</p><details><summary>Inspect matching question</summary><p>{label(m.question.question_type)} · {m.question.marks} marks · {m.question.bloom_level} · {label(m.question.difficulty)} · {label(m.question.status)} · Version {m.question.version}</p><p>{Object.values(m.question.mapping||{}).filter(Boolean).map(x=>`${x?.code} · ${x?.title}`).join(' / ')}</p><p>{label(m.question.source_type)} · {m.question.source_reference||'No source reference'} · {m.question.created_at?new Date(m.question.created_at).toLocaleDateString():'Date unavailable'}</p><p>Compared query version {m.query_version}; no question is merged or changed.</p></details></article>)}</>}
 {usage&&<section className="my-3 text-sm" aria-label="Question usage"><h4 className="font-semibold">Usage</h4><p>Times used: {usage.times_used} · Papers: {usage.number_of_papers} · Finalized revisions: {usage.number_of_paper_revisions||0}</p><p>First used: {usage.first_used_date?new Date(usage.first_used_date).toLocaleString():'Never'} · Last used: {usage.last_used_date?new Date(usage.last_used_date).toLocaleString():'Never'}</p>{(usage.history||[]).map((h,i)=><p className="my-2" key={i}>{h.paper_title} · Paper v{h.paper_version} / revision {h.revision} · Question v{h.question_version}</p>)}<p className="text-xs text-slate-500">Derived from immutable Approved/Locked paper snapshots; offered alternatives included. Semester history is unavailable.</p></section>}
 {history.length>0&&<details className="my-3 text-sm"><summary>Embedding history</summary>{history.map((h,i)=><p className="my-2" key={i}>Version {h.question_version} · {label(h.status)}{h.stale?' · Stale':''} · {h.dimension||'—'} dimensions · {h.model} · {h.failure_reason}</p>)}</details>}
 </section>;
}
