import QpgQuestionIntelligencePanel from './QpgQuestionIntelligencePanel';
import QpgValidationPanel from './QpgValidationPanel';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label,statuses,questionTypes,sourceTypes,blooms,difficulties} from '@/api/qpgApi';
import type {Subject,Question,SyllabusItem} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
import Dialog from './QpgDialog';
type Event={id:string;version:number;actor:string;created_at:string;change_reason:string;status:string;previous_status:string|null;event:{action:string;comment:string;reviewed_version:number}|null};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgReviewPanel({subject,cos,units,topics,canWrite,onEdit}:{subject:Subject;cos:SyllabusItem[];units:SyllabusItem[];topics:SyllabusItem[];canWrite:boolean;onEdit:(question:Question)=>void}){
 const [filters,setFilters]=useState({q:'',status:'NEEDS_REVIEW',co_id:'',unit_id:'',topic_id:'',bloom_level:'',difficulty:'',question_type:'',marks:'',source_type:'',created_by:''});const [offset,setOffset]=useState(0);const [rows,setRows]=useState<Question[]>([]);const [total,setTotal]=useState(0);const [refresh,setRefresh]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const [selected,setSelected]=useState<Question|null>(null);const [history,setHistory]=useState<Event[]>([]);const [comment,setComment]=useState('');const [busy,setBusy]=useState(false);const [detailReady,setDetailReady]=useState(false);
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>{setLoading(true);const params=new URLSearchParams({subject_id:subject.id,limit:'50',offset:String(offset),status:filters.status});Object.entries(filters).forEach(([k,v])=>{if(v)params.set(k,v);});qpgApi.get<{items:Question[];total:number}>(`questions/review-queue?${params}`,c.signal).then(r=>{setRows(r.items);setTotal(r.total);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},200);return ()=>{c.abort();clearTimeout(timer);};},[subject.id,filters,offset,refresh]);
 useEffect(()=>{if(!selected?.id)return;const c=new AbortController();setDetailReady(false);qpgApi.get<{question:Question;history:Event[]}>(`questions/${selected.id}/review`,c.signal).then(r=>{setSelected(r.question);setHistory(r.history);setDetailReady(true);}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return ()=>c.abort();},[selected?.id]);
 function change(key:keyof typeof filters,value:string){setFilters({...filters,[key]:value,...(key==='unit_id'?{topic_id:''}:{})});setOffset(0);setError('');}
 async function action(name:string){if(!selected)return;setBusy(true);setError('');try{const next=await qpgApi.save<Question>(`questions/${selected.id}/${name}`,{expected_version:selected.version,comment});setSelected(next);setHistory((await qpgApi.get<{items:Event[]}>(`questions/${next.id}/review-history`)).items);setComment('');setRefresh(v=>v+1);}catch(e){const d=(e as {response?:{data?:{detail?:{message?:string;errors?:string[]}}}}).response?.data?.detail;setError(d?.errors?`${d.message} ${d.errors.join(' ')}`:collegeError(e));}finally{setBusy(false);}}
 const choices=(values:string[])=>values.map(v=>({value:v,title:label(v)}));const mapped=(items:SyllabusItem[])=>items.map(x=>({value:x.id,title:x.code+' · '+x.title}));
 return <section className="erp-card" aria-label="Question review queue"><h2>Review Queue · {total}</h2><p className="my-3 text-sm text-slate-500">Review individually before approving. Approved edits create a new version that requires review again.</p>{error&&!selected&&<p role="alert" className="text-red-700">{error}</p>}
 <div className="my-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-2 text-sm">Search review questions<input className={input} value={filters.q} onChange={e=>change('q',e.target.value)}/></label><Select title="Review status" value={filters.status} onChange={v=>change('status',v)} items={choices(statuses)}/><Select title="Review CO" value={filters.co_id} onChange={v=>change('co_id',v)} items={mapped(cos)}/><Select title="Review Unit" value={filters.unit_id} onChange={v=>change('unit_id',v)} items={mapped(units)}/><Select title="Review Topic" value={filters.topic_id} onChange={v=>change('topic_id',v)} items={mapped(topics.filter(t=>!filters.unit_id||t.unit_id===filters.unit_id))}/><Select title="Review Bloom" value={filters.bloom_level} onChange={v=>change('bloom_level',v)} items={choices(blooms)}/><Select title="Review Difficulty" value={filters.difficulty} onChange={v=>change('difficulty',v)} items={choices(difficulties)}/><Select title="Review Type" value={filters.question_type} onChange={v=>change('question_type',v)} items={choices(questionTypes)}/><Select title="Review Source" value={filters.source_type} onChange={v=>change('source_type',v)} items={choices(sourceTypes)}/><label className="grid gap-2 text-sm">Review Marks<input type="number" min="0.01" step="0.01" className={input} value={filters.marks} onChange={e=>change('marks',e.target.value)}/></label><label className="grid gap-2 text-sm">Created by<input className={input} value={filters.created_by} onChange={e=>change('created_by',e.target.value)} placeholder="Faculty account ID"/></label></div>
 {loading?<p role="status">Loading review queue…</p>:<><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Question','Mapping / metadata','Status','Version','Created by','Updated','Action'].map(x=><th key={x} className="border-b p-3">{x}</th>)}</tr></thead><tbody>{rows.map(q=><tr key={q.id} className="border-b"><td className="min-w-60 p-3">{q.question_text}</td><td className="min-w-48 p-3">{label(q.question_type)} · {q.marks} marks<br/>{cos.find(x=>x.id===q.co_id)?.code||'No CO'} · {units.find(x=>x.id===q.unit_id)?.code||'No Unit'} · {topics.find(x=>x.id===q.topic_id)?.code||'No Topic'}<br/>{q.bloom_level} · {label(q.difficulty)} · {label(q.source_type)}</td><td className="p-3">{label(q.status)}</td><td className="p-3">{q.version}</td><td className="p-3">{q.created_by}</td><td className="p-3">{new Date(q.updated_at).toLocaleDateString()}</td><td className="p-3"><Button size="sm" variant="outline" onClick={()=>{setError('');setComment('');setHistory([]);setSelected(q);}}>Review</Button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="my-5">No questions match this review queue.</p>}<div className="my-4 flex gap-2"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Previous</Button><Button variant="outline" disabled={offset+50>=total} onClick={()=>setOffset(v=>v+50)}>Next</Button></div></>}
 {selected&&<Dialog title="Review Question" onClose={()=>{if(!busy)setSelected(null);}}>{error&&<p role="alert" className="mb-3 text-red-700">{error}</p>}<p className="mb-4 whitespace-pre-wrap font-medium">{selected.question_text}</p><dl className="grid gap-3 text-sm sm:grid-cols-2">{Object.entries({Type:label(selected.question_type),Marks:selected.marks,CO:cos.find(x=>x.id===selected.co_id)?.title||'Not assigned',Unit:units.find(x=>x.id===selected.unit_id)?.title||'Not assigned',Topic:topics.find(x=>x.id===selected.topic_id)?.title||'Not assigned',Bloom:selected.bloom_level,Difficulty:label(selected.difficulty),Status:label(selected.status),Version:selected.version,Source:label(selected.source_type),'Source reference':selected.source_reference||'—','Created by':selected.created_by,'Created date':new Date(selected.created_at).toLocaleString()}).map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl>{selected.options.map((x,i)=><p key={i} className="mt-2 text-sm">{String.fromCharCode(65+i)}. {x}</p>)}<h3 className="mt-4 font-semibold">Answer / Solution</h3><p className="my-2 whitespace-pre-wrap text-sm">{canWrite?(selected.answer||'Not provided'):'Answer access requires academic write permission.'}</p><p className="my-2 text-xs text-slate-500">Approval requires published CO, Unit and Topic mappings and an answer. MCQ answer: full option text or one letter, e.g. A.</p>
 <QpgQuestionIntelligencePanel key={selected.id+selected.version} question={selected} canWrite={canWrite}/>
 <QpgValidationPanel key={selected.id} questionId={selected.id} version={selected.version} canWrite={canWrite} archived={selected.status==='ARCHIVED'}/>
 {canWrite&&selected.status!=='ARCHIVED'&&<><label className="my-4 grid gap-2 text-sm">Reviewer comment<textarea aria-label="Reviewer comment" className={input} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Required for Request Changes and Reject"/></label><div className="my-3 flex flex-wrap gap-2">{['DRAFT','NEEDS_REVIEW'].includes(selected.status)&&<Button disabled={busy||!detailReady} onClick={()=>void action('submit-review')}>{selected.status==='DRAFT'?'Submit for Review':'Resubmit for Review'}</Button>}{selected.status==='NEEDS_REVIEW'&&<><Button disabled={busy||!detailReady} onClick={()=>void action('approve')}>Approve</Button><Button variant="outline" disabled={busy||!detailReady||!comment.trim()} onClick={()=>void action('request-changes')}>Request Changes</Button><Button variant="outline" disabled={busy||!detailReady||!comment.trim()} onClick={()=>void action('reject')}>Reject</Button></>}<Button variant="outline" disabled={busy||!detailReady||!comment.trim()} onClick={()=>void action('comments')}>Save Comment</Button><Button variant="outline" disabled={busy||!detailReady} onClick={()=>{setSelected(null);onEdit(selected);}}>Edit</Button></div></>}
 <h3 className="mt-5 font-semibold">Review History</h3>{history.map(h=><div key={h.id} className="my-3 rounded-xl border p-3 text-sm"><p>Version {h.version} · {label(h.event?.action||'saved')} · {label(h.status)}</p><p className="text-xs text-slate-500">{h.actor} · {new Date(h.created_at).toLocaleString()} · {h.previous_status?`${label(h.previous_status)} → ${label(h.status)}`:'Created'}</p><p className="mt-1 whitespace-pre-wrap">{canWrite?(h.event?.comment||h.change_reason||'Question saved'):'Question saved'}</p></div>)}</Dialog>}
 </section>;
}
function Select({title,value,onChange,items}:{title:string;value:string;onChange:(v:string)=>void;items:{value:string;title:string}[]}){return <label className="grid gap-2 text-sm">{title}<select aria-label={title} className={input} value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{items.map(x=><option key={x.value} value={x.value}>{x.title}</option>)}</select></label>;}
