import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
import type {Subject} from '@/api/qpgApi';
type Report={question_count:number;counts:Record<string,Record<string,number>>;labels?:Record<string,Record<string,string>>;topics:{id:string;code:string;title:string;question_count:number;times_used:number;category:string}[];usage:{question_id:string;number_of_papers:number;times_used:number}[];truncated:boolean;basis:string};
type Pin={id:string;version:number;status:string};
export default function QpgRepetitionPanel({subject}:{subject:Subject}){
 const [pins,setPins]=useState<Pin[]>([]),[pin,setPin]=useState(''),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();qpgApi.get<{items:Pin[]}>(`subjects/${subject.id}/syllabus/versions`,c.signal).then(r=>setPins((r.items||[]).filter(p=>p.status!=='DRAFT'))).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[subject.id]);
 async function load(){setBusy(true);setError('');try{const params=new URLSearchParams({subject_id:subject.id});if(pin)params.set('syllabus_version_id',pin);setReport(await qpgApi.get<Report>(`questions/repetition-analysis?${params}`));}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 return <section className="erp-card" aria-label="Question Bank repetition"><h2>Question Bank Intelligence</h2><p className="my-2 text-sm text-slate-500">Question distribution and historical usage for {subject.name}. Faculty decides whether any repetition is appropriate.</p><div className="my-4 flex flex-wrap gap-3"><label className="grid gap-2 text-sm">Analysis syllabus<select aria-label="Analysis syllabus" className="rounded-xl border p-2 dark:bg-slate-900" value={pin} disabled={busy} onChange={e=>{setPin(e.target.value);setReport(null);}}><option value="">Current published syllabus</option>{pins.map(p=><option value={p.id} key={p.id}>Version {p.version} · {label(p.status)}</option>)}</select></label><Button variant="outline" disabled={busy} onClick={()=>void load()}>View Repetition Analysis</Button></div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{busy&&<p role="status">Loading Question Bank usage…</p>}{report&&<><p className="my-2 text-sm">{report.question_count} non-archived questions · {report.basis}</p>{report.truncated&&<p className="my-2 text-sm text-amber-700">Sample limits reached. These counts describe the included records.</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Topic','Questions','Times used','Usage indicator'].map(x=><th key={x} className="border-b p-3">{x}</th>)}</tr></thead><tbody>{report.topics.map(t=><tr key={t.id} className="border-b"><td className="p-3">{t.code} · {t.title}</td><td className="p-3">{t.question_count}</td><td className="p-3">{t.times_used}</td><td className="p-3">{label(t.category)}</td></tr>)}</tbody></table></div><div className="my-4 grid gap-3 sm:grid-cols-2">{Object.entries(report.counts).map(([kind,counts])=><details className="rounded-xl border p-3 text-sm" key={kind}><summary>{label(kind)} distribution</summary>{Object.entries(counts).map(([value,count])=><p key={value}>{report.labels?.[kind]?.[value]||report.topics.find(t=>t.id===value)?.title||(['cos','units','topics'].includes(kind)?'Mapping unavailable':label(value))}: {count}</p>)}</details>)}</div><p className="text-sm">{report.usage.length} questions used in finalized papers. Open a question and choose View Usage to inspect its paper history.</p></>}</section>;
}
