import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,label} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
import {Upload,FileText,X} from 'lucide-react';
type Kind='cos'|'units'|'topics';
type Item=SyllabusItem&{position:number};
type Structure={cos:Item[];units:Item[];topics:Item[]};
type Version={id:string;version:number;revision:number;status:string;content:Structure;created_by:string;created_at:string;published_at:string|null;document_filename:string|null;document_uploaded_by:string|null;document_uploaded_at:string|null};
type Syllabus={current:Version|null;published_id:string|null;structure:Structure;can_write:boolean};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgSyllabusPanel({subject,onChange}:{subject:Subject;onChange:()=>void}){
 const [data,setData]=useState<Syllabus|null>(null);const [versions,setVersions]=useState<Version[]>([]);const [history,setHistory]=useState<Version|null>(null);
 const [error,setError]=useState('');const [errors,setErrors]=useState<string[]>([]);const [busy,setBusy]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null);
 const [uploadFile,setUploadFile]=useState<File|null>(null);
 const [uploadProgress,setUploadProgress]=useState<number|null>(null);
 const [fileError,setFileError]=useState('');
 function chooseFile(file:File|null){setFileError('');setUploadProgress(null);setUploadFile(null);if(!file)return;if(!/\.(pdf|docx)$/i.test(file.name)||!file.size||file.size>10*1024*1024){setFileError('Choose a non-empty PDF or DOCX file up to 10 MB.');if(fileInput.current)fileInput.current.value='';return;}setUploadFile(file);}
 const [reviewPublish,setReviewPublish]=useState(false);
 const [notice,setNotice]=useState('');
 const [entryMode,setEntryMode]=useState<'manual'|'upload'>('manual');
 const [form,setForm]=useState<{kind:Kind;unit?:string;item?:Item}|null>(null);
 const root=`subjects/${subject.id}/syllabus`;
 useEffect(()=>{const controller=new AbortController();Promise.all([qpgApi.get<Syllabus>(root,controller.signal),qpgApi.get<{items:Version[]}>(`${root}/versions`,controller.signal)]).then(([s,v])=>{setData(s);setVersions(v.items);}).catch(e=>{if(!controller.signal.aborted)setError(collegeError(e));});return ()=>controller.abort();},[root]);
 async function run(work:()=>Promise<Syllabus>){setBusy(true);setError('');setErrors([]);setNotice('');try{const next=await work();setData(next);setHistory(null);try{setVersions((await qpgApi.get<{items:Version[]}>(`${root}/versions`)).items);}catch{setNotice('Your change was saved. Version history could not refresh; reload to update it.');}onChange();return true;}catch(e){const detail=(e as {response?:{data?:{detail?:{errors?:string[];message?:string}}}}).response?.data?.detail;if(detail?.errors){setError(detail.message||'Cannot publish syllabus.');setErrors(detail.errors);}else setError(collegeError(e));return false;}finally{setBusy(false);}}
 const current=data?.current;const view=history||current;const structure=history?history.content:data?.structure;
 const editable=Boolean(data?.can_write&&!history&&(!current||current.status==='DRAFT'));
 const revision=current?.revision||1;
 const publishIssues=structure?[...(!structure.cos.length?['Add at least one Course Outcome.']:[]),...(!structure.units.length?['Add at least one Unit.']:[]),...structure.units.filter(u=>!structure.topics.some(t=>t.unit_id===u.id)).map(u=>`Add at least one Topic to ${u.code}.`)]:[];
 async function saveItem(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!form)return;const fields=new FormData(e.currentTarget);const success=await run(async()=>{if(form.item)return qpgApi.save<Syllabus>(`${root}/${form.kind}/${form.item.id}`,{code:fields.get('code'),title:fields.get('title'),expected_revision:revision},true);const path=form.kind==='topics'?`units/${form.unit}/topics`:`subjects/${subject.id}/${form.kind}`;await qpgApi.save(path,{code:fields.get('code'),title:fields.get('title'),...(current?{expected_revision:revision}:{})});return qpgApi.get<Syllabus>(root);});if(success)setForm(null);}
 function move(kind:Kind,items:Item[],index:number,direction:number,unit?:string){const ids=items.map(i=>i.id);[ids[index],ids[index+direction]]=[ids[index+direction],ids[index]];void run(()=>qpgApi.save<Syllabus>(`${root}/reorder`,{kind,unit_id:unit||null,ids,expected_revision:revision}));}
 function archive(kind:Kind,item:Item){if(!window.confirm(`Archive ${item.code}? Items referenced by questions must be retained.`))return;void run(async()=>{return (await apiClient.delete<Syllabus>(`/v3/college/question-papers/${root}/${kind}/${item.id}`,{data:{expected_revision:revision}})).data;});}
 function controls(kind:Kind,item:Item,items:Item[],index:number,unit?:string){return editable&&<div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind,item,unit})}>Edit {item.code}</Button><details className="relative"><summary className="cursor-pointer px-3 py-2 text-sm">More options</summary><div className="flex flex-wrap gap-1 rounded-lg border p-2"><Button size="sm" variant="ghost" disabled={busy} onClick={()=>archive(kind,item)}>Archive {item.code}</Button><Button size="sm" variant="outline" aria-label={`Move ${item.code} up`} disabled={busy||index===0} onClick={()=>move(kind,items,index,-1,unit)}>↑</Button><Button size="sm" variant="outline" aria-label={`Move ${item.code} down`} disabled={busy||index===items.length-1} onClick={()=>move(kind,items,index,1,unit)}>↓</Button></div></details></div>;}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!uploadFile||busy)return;const body=new FormData();body.append('file',uploadFile);body.append('expected_revision',String(revision));setUploadProgress(0);const success=await run(async()=>(await apiClient.post<Syllabus>(`/v3/college/question-papers/${root}/document`,body,{headers:{'Content-Type':'multipart/form-data'},timeout:125000,onUploadProgress:event=>setUploadProgress(event.total?Math.round(100*event.loaded/event.total):null)})).data);setUploadProgress(null);if(success){setUploadFile(null);if(fileInput.current)fileInput.current.value='';setNotice('Syllabus document uploaded successfully.');}}
 return <section className="erp-card" aria-label="Syllabus Master"><header className="mb-4"><h2>Syllabus Master · {subject.code} · {subject.name}</h2><p className="text-sm text-slate-500">{view?`Version ${view.version} · ${label(view.status)}`:'Draft · not saved yet'}</p></header>
 {notice&&<p role="status" className="my-3 text-sm text-emerald-700 dark:text-emerald-300">{notice}</p>}
 {error&&<div role="alert" className="my-4 text-sm text-red-700"><p>{error}</p>{errors.length>0&&<ul className="mt-2 list-inside list-disc">{errors.map(message=><li key={message}>{message}</li>)}</ul>}</div>}
 {!data&&!error&&<p role="status">Loading syllabus…</p>}
 {data&&structure&&<>
  {!history&&<div className="mb-5 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{current?.status==='PUBLISHED'?'Published syllabus':'Saved syllabus draft'}</p><p className="mt-1 text-sm text-slate-500">{current?.status==='PUBLISHED'?'Ready for AI questions and paper patterns. Start a new draft to make changes.':'1. Check the Course Outcomes, Units and Topics below. 2. Select Review & Publish. 3. In the review window, click Publish syllabus. AI generation becomes available after publishing.'}</p></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full border bg-white px-3 py-1 dark:bg-slate-800">{structure.cos.length} outcomes</span><span className="rounded-full border bg-white px-3 py-1 dark:bg-slate-800">{structure.units.length} units</span><span className="rounded-full border bg-white px-3 py-1 dark:bg-slate-800">{structure.topics.length} topics</span></div></div></div>}
  {history&&<Button variant="outline" onClick={()=>setHistory(null)}>Back to current syllabus</Button>}
  {data.can_write&&!history&&<div aria-label="Syllabus actions" className="my-4 flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-4 dark:border-slate-700">
   {editable?<><Button variant="outline" disabled={busy} onClick={()=>void (async()=>{const saved=await run(()=>current?qpgApi.save<Syllabus>(root,{expected_revision:revision},true):qpgApi.save<Syllabus>(`${root}/draft`,{}));if(saved)setNotice('Draft saved. Check the syllabus content, select Review & Publish, then click Publish syllabus in the review window.');})()}>{busy?'Please wait…':'Save Draft'}</Button><div className="ml-auto text-right"><Button disabled={busy||!current} onClick={()=>setReviewPublish(true)}>Review &amp; Publish</Button><p className="mt-1 text-xs text-slate-500">Next step: enable AI questions and paper patterns.</p></div></>:<><Button disabled={busy} onClick={()=>void run(()=>qpgApi.save<Syllabus>(`${root}/draft`,{}))}>Start new draft</Button>{current?.status==='PUBLISHED'&&<details className="ml-auto"><summary className="cursor-pointer text-sm">More actions</summary><Button variant="outline" className="mt-2" disabled={busy} onClick={()=>{if(window.confirm('Archive this published syllabus? Its history will remain available.'))void run(()=>qpgApi.save<Syllabus>(`${root}/archive`,{expected_revision:revision}));}}>Archive syllabus</Button></details>}</>}
  </div>}
  <nav aria-label="Syllabus entry method" className="my-5 flex gap-5 border-b border-slate-200 dark:border-slate-700">{(['manual','upload'] as const).map(mode=><button key={mode} type="button" aria-pressed={entryMode===mode} onClick={()=>setEntryMode(mode)} className={`border-b-2 px-1 py-3 text-sm font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${entryMode===mode?'border-indigo-600 text-indigo-700 dark:text-indigo-300':'border-transparent text-slate-600 hover:text-slate-900 dark:text-slate-300'}`}>{mode==='manual'?'Syllabus content':'Reference document'}</button>)}</nav>
  {entryMode==='manual'&&<div aria-label="Manual syllabus entry">
  <section className="mb-6"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold">Course Outcomes</h3>{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'cos'})}>Add CO</Button>}</div>{structure.cos.map((co,i)=><div key={co.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-3"><p><strong>{co.code}</strong> — {co.title}</p>{controls('cos',co,structure.cos,i)}</div>)}{!structure.cos.length&&<p className="text-sm text-slate-500">No course outcomes added yet.</p>}</section>
  <section><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold">Units and Topics</h3>{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'units'})}>Add Unit</Button>}</div>{structure.units.map((unit,i)=>{const topics=structure.topics.filter(t=>t.unit_id===unit.id);return <details key={unit.id} className="mb-3 rounded-xl border border-slate-200 p-4" open><summary className="cursor-pointer font-medium">{unit.code} — {unit.title}</summary><div className="my-3 flex flex-wrap items-center justify-between gap-2">{controls('units',unit,structure.units,i)}{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'topics',unit:unit.id})}>Add Topic to {unit.code}</Button>}</div>{topics.map((topic,j)=><div key={topic.id} className="ml-3 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 py-3"><p className="text-sm"><strong>{topic.code}</strong> — {topic.title}</p>{controls('topics',topic,topics,j,unit.id)}</div>)}{!topics.length&&<p className="text-sm text-slate-500">No topics added to this unit yet.</p>}</details>;})}{!structure.units.length&&<p className="text-sm text-slate-500">No units added yet.</p>}</section>
  </div>}
  {entryMode==='upload'&&<section className="my-5 max-w-3xl" aria-label="Upload syllabus document"><h3 className="font-semibold">Attach original document</h3><p className="mb-4 mt-1 text-sm text-slate-500">Keep a copy of your official syllabus with this version.</p>
   {view?.document_filename&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900"><div className="flex min-w-0 items-center gap-3"><FileText className="shrink-0 text-indigo-600" size={22} aria-hidden="true"/><div className="min-w-0"><p className="break-all text-sm font-medium">{view.document_filename}</p><p className="text-xs text-slate-500">Attached to version {view.version}</p></div></div><Button size="sm" variant="outline" onClick={()=>{setError('');void qpgApi.get<{url:string}>(`${root}/versions/${view.id}/document`).then(r=>window.open(r.url,'_blank','noopener,noreferrer')).catch(e=>setError(collegeError(e)));}}>View document</Button></div>}
   {editable&&current?<form onSubmit={upload} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900">
    <label className={`relative flex flex-col items-center gap-2 rounded-xl border-2 border-dashed border-slate-300 px-4 py-6 text-center focus-within:ring-2 focus-within:ring-indigo-600 ${busy?'opacity-60':'cursor-pointer hover:border-indigo-500 hover:bg-indigo-50 dark:hover:bg-indigo-950'}`}><Upload size={28} className="text-indigo-600" aria-hidden="true"/><span className="text-sm font-medium">{uploadFile?'Choose a different file':'Choose your syllabus file'}</span><span id="syllabus-file-help" className="text-xs text-slate-500">PDF or DOCX · Maximum 10 MB</span><input ref={fileInput} aria-label="Choose syllabus document" aria-describedby="syllabus-file-help" aria-invalid={Boolean(fileError)} name="file" type="file" accept=".pdf,.docx" disabled={busy} className="absolute inset-0 h-full w-full cursor-pointer opacity-0" onChange={e=>chooseFile(e.target.files?.[0]||null)}/></label>
    {fileError&&<p role="alert" className="mt-3 text-sm text-red-700">{fileError}</p>}
    {uploadFile&&<div className="mt-4 flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><div className="min-w-0"><p className="break-all text-sm font-medium">{uploadFile.name}</p><p className="text-xs text-slate-500">{(uploadFile.size/1024/1024).toFixed(2)} MB</p></div><Button type="button" size="sm" variant="ghost" aria-label="Remove selected file" disabled={busy} onClick={()=>{setUploadFile(null);if(fileInput.current)fileInput.current.value='';}}><X size={18} aria-hidden="true"/></Button></div>}
    {busy&&uploadProgress!==null&&<div className="mt-4"><progress aria-label="Document upload progress" max={100} value={uploadProgress} className="h-2 w-full"/><p role="status" className="mt-1 text-xs text-slate-500">{uploadProgress===100?'Upload sent. Saving document…':`Uploading… ${uploadProgress}%`}</p></div>}
    <div className="mt-4 flex justify-end"><Button type="submit" disabled={busy||!uploadFile}>{busy?'Uploading…':view?.document_filename?'Replace document':'Upload document'}</Button></div>
   </form>:<p className="rounded-xl border border-slate-200 p-4 text-sm text-slate-500">{!view?.document_filename?'No document attached. ':''}{editable?'Save Draft to enable upload.':history?'This is a previous version. Return to the current syllabus to make changes.':data?.can_write?'Start a new draft to attach or replace a document.':'Document upload requires editing access.'}</p>}
   <p className="mt-3 text-xs text-slate-500">Attaching retains the original for reference. Use Extract & review above to create editable syllabus items.</p>
  </section>}
  <details className="mt-6 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Previous versions</summary>{versions.map(v=><div className="mb-2 flex flex-wrap items-center justify-between gap-3" key={v.id}><p className="text-sm">Version {v.version} · {label(v.status)} · Created {new Date(v.created_at).toLocaleDateString()} by {v.created_by}{v.published_at?` · Published ${new Date(v.published_at).toLocaleDateString()}`:''}</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void qpgApi.get<Version>(`${root}/versions/${v.id}`).then(setHistory).catch(e=>setError(collegeError(e)))}>View version {v.version}</Button></div>)}</details>
 </>}
 {reviewPublish&&current&&structure&&<Dialog title="Review syllabus before publishing" onClose={()=>{if(!busy)setReviewPublish(false);}}><p className="mb-4 text-sm">Publishing makes version {current.version} available for AI question generation and new paper patterns. To edit a published syllabus, you will create a new draft.</p><dl className="mb-5 grid grid-cols-2 gap-3 text-sm"><dt>Course Outcomes</dt><dd>{structure.cos.length}</dd><dt>Units</dt><dd>{structure.units.length}</dd><dt>Topics</dt><dd>{structure.topics.length}</dd><dt>Document</dt><dd className="break-words">{current.document_filename||'Not attached'}</dd></dl>{publishIssues.length>0&&<div role="alert" className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Not ready to publish</p><ul className="mt-2 list-disc pl-5">{publishIssues.map(issue=><li key={issue}>{issue}</li>)}</ul><p className="mt-2">Your draft is saved. Continue editing to complete its structure.</p></div>}{error&&<div role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700"><p>{error}</p><ul className="list-disc pl-5">{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}<div className="flex justify-between gap-3"><Button variant="outline" disabled={busy} onClick={()=>{setReviewPublish(false);setEntryMode('manual');setError('');setErrors([]);}}>Continue editing</Button><Button disabled={busy||publishIssues.length>0} onClick={()=>void (async()=>{const published=await run(()=>qpgApi.save<Syllabus>(`${root}/publish`,{expected_revision:revision}));if(published){setReviewPublish(false);setNotice(`Version ${current.version} published successfully. Next: open Question Papers → Generate with AI to create questions, or Prepare Paper → Paper Patterns to set up your paper.`);window.scrollTo({top:0,behavior:'smooth'});}})()}>{busy?'Publishing…':'Publish syllabus'}</Button></div></Dialog>}
 {form&&<Dialog title={`${form.item?'Edit':'Add'} ${form.kind==='cos'?'CO':form.kind==='units'?'Unit':'Topic'}`} onClose={()=>setForm(null)}><form className="grid gap-4" onSubmit={saveItem}>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<label className="grid gap-2 text-sm">Code<input name="code" className={input} required maxLength={80} defaultValue={form.item?.code}/></label><label className="grid gap-2 text-sm">Title / description<textarea name="title" className={input} required maxLength={500} defaultValue={form.item?.title}/></label><Button disabled={busy} type="submit">Save item</Button></form></Dialog>}
 </section>;
}
