import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
import {qpgApi,label} from '@/api/qpgApi';
import type {Subject,SyllabusItem} from '@/api/qpgApi';
import Dialog from './QpgDialog';
type Kind='cos'|'units'|'topics';
type Item=SyllabusItem&{position:number};
type Structure={cos:Item[];units:Item[];topics:Item[]};
type Version={id:string;version:number;revision:number;status:string;content:Structure;created_by:string;created_at:string;published_at:string|null;document_filename:string|null;document_uploaded_by:string|null;document_uploaded_at:string|null};
type Syllabus={current:Version|null;published_id:string|null;structure:Structure;can_write:boolean};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgSyllabusPanel({subject,onChange}:{subject:Subject;onChange:()=>void}){
 const [data,setData]=useState<Syllabus|null>(null);const [versions,setVersions]=useState<Version[]>([]);const [history,setHistory]=useState<Version|null>(null);
 const [error,setError]=useState('');const [errors,setErrors]=useState<string[]>([]);const [busy,setBusy]=useState(false);
 const [form,setForm]=useState<{kind:Kind;unit?:string;item?:Item}|null>(null);
 const root=`subjects/${subject.id}/syllabus`;
 useEffect(()=>{const controller=new AbortController();Promise.all([qpgApi.get<Syllabus>(root,controller.signal),qpgApi.get<{items:Version[]}>(`${root}/versions`,controller.signal)]).then(([s,v])=>{setData(s);setVersions(v.items);}).catch(e=>{if(!controller.signal.aborted)setError(collegeError(e));});return ()=>controller.abort();},[root]);
 async function run(work:()=>Promise<Syllabus>){setBusy(true);setError('');setErrors([]);try{const next=await work();setData(next);setHistory(null);setVersions((await qpgApi.get<{items:Version[]}>(`${root}/versions`)).items);onChange();return true;}catch(e){const detail=(e as {response?:{data?:{detail?:{errors?:string[];message?:string}}}}).response?.data?.detail;if(detail?.errors){setError(detail.message||'Cannot publish syllabus.');setErrors(detail.errors);}else setError(collegeError(e));return false;}finally{setBusy(false);}}
 const current=data?.current;const view=history||current;const structure=history?history.content:data?.structure;
 const editable=Boolean(data?.can_write&&!history&&(!current||current.status==='DRAFT'));
 const revision=current?.revision||1;
 async function saveItem(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!form)return;const fields=new FormData(e.currentTarget);const success=await run(async()=>{if(form.item)return qpgApi.save<Syllabus>(`${root}/${form.kind}/${form.item.id}`,{code:fields.get('code'),title:fields.get('title'),expected_revision:revision},true);const path=form.kind==='topics'?`units/${form.unit}/topics`:`subjects/${subject.id}/${form.kind}`;await qpgApi.save(path,{code:fields.get('code'),title:fields.get('title'),...(current?{expected_revision:revision}:{})});return qpgApi.get<Syllabus>(root);});if(success)setForm(null);}
 function move(kind:Kind,items:Item[],index:number,direction:number,unit?:string){const ids=items.map(i=>i.id);[ids[index],ids[index+direction]]=[ids[index+direction],ids[index]];void run(()=>qpgApi.save<Syllabus>(`${root}/reorder`,{kind,unit_id:unit||null,ids,expected_revision:revision}));}
 function archive(kind:Kind,item:Item){if(!window.confirm(`Archive ${item.code}? Items referenced by questions must be retained.`))return;void run(async()=>{return (await apiClient.delete<Syllabus>(`/v3/college/question-papers/${root}/${kind}/${item.id}`,{data:{expected_revision:revision}})).data;});}
 function controls(kind:Kind,item:Item,items:Item[],index:number,unit?:string){return editable&&<div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind,item,unit})}>Edit {item.code}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>archive(kind,item)}>Archive {item.code}</Button><Button size="sm" variant="outline" aria-label={`Move ${item.code} up`} disabled={busy||index===0} onClick={()=>move(kind,items,index,-1,unit)}>↑</Button><Button size="sm" variant="outline" aria-label={`Move ${item.code} down`} disabled={busy||index===items.length-1} onClick={()=>move(kind,items,index,1,unit)}>↓</Button></div>;}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=new FormData(e.currentTarget);body.append('expected_revision',String(revision));await run(async()=>(await apiClient.post<Syllabus>(`/v3/college/question-papers/${root}/document`,body,{headers:{'Content-Type':'multipart/form-data'},timeout:125000})).data);}
 return <section className="erp-card" aria-label="Subject syllabus"><header className="mb-4"><h2>Syllabus · {subject.code} · {subject.name}</h2><p className="text-sm text-slate-500">{view?`Version ${view.version} · ${label(view.status)}`:'Draft · not saved yet'}{data?.published_id&&current?.status==='DRAFT'?' · A published version remains available in history.':''}</p></header>
 {error&&<div role="alert" className="my-4 text-sm text-red-700"><p>{error}</p>{errors.length>0&&<ul className="mt-2 list-inside list-disc">{errors.map(message=><li key={message}>{message}</li>)}</ul>}</div>}
 {!data&&!error&&<p role="status">Loading syllabus…</p>}
 {data&&structure&&<>
  {history&&<Button variant="outline" onClick={()=>setHistory(null)}>Back to current syllabus</Button>}
  <div className="my-4 flex flex-wrap gap-2">{data.can_write&&!history&&<>{editable?<><Button disabled={busy} onClick={()=>void run(()=>current?qpgApi.save<Syllabus>(root,{expected_revision:revision},true):qpgApi.save<Syllabus>(`${root}/draft`,{}))}>Save Draft</Button><Button variant="outline" disabled={busy||!current} onClick={()=>void run(()=>qpgApi.save<Syllabus>(`${root}/publish`,{expected_revision:revision}))}>Publish</Button></>:<Button disabled={busy} onClick={()=>void run(()=>qpgApi.save<Syllabus>(`${root}/draft`,{}))}>Start new draft</Button>}{current?.status==='PUBLISHED'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Archive this published syllabus? Its history will remain available.'))void run(()=>qpgApi.save<Syllabus>(`${root}/archive`,{expected_revision:revision}));}}>Archive syllabus</Button>}</>}</div>
  <section className="mb-6"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold">Course Outcomes</h3>{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'cos'})}>Add CO</Button>}</div>{structure.cos.map((co,i)=><div key={co.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-3"><p><strong>{co.code}</strong> — {co.title}</p>{controls('cos',co,structure.cos,i)}</div>)}{!structure.cos.length&&<p className="text-sm text-slate-500">No course outcomes added yet.</p>}</section>
  <section><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold">Units and Topics</h3>{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'units'})}>Add Unit</Button>}</div>{structure.units.map((unit,i)=>{const topics=structure.topics.filter(t=>t.unit_id===unit.id);return <details key={unit.id} className="mb-3 rounded-xl border border-slate-200 p-4" open><summary className="cursor-pointer font-medium">{unit.code} — {unit.title}</summary><div className="my-3 flex flex-wrap items-center justify-between gap-2">{controls('units',unit,structure.units,i)}{editable&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setForm({kind:'topics',unit:unit.id})}>Add Topic to {unit.code}</Button>}</div>{topics.map((topic,j)=><div key={topic.id} className="ml-3 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 py-3"><p className="text-sm"><strong>{topic.code}</strong> — {topic.title}</p>{controls('topics',topic,topics,j,unit.id)}</div>)}{!topics.length&&<p className="text-sm text-slate-500">No topics added to this unit yet.</p>}</details>;})}{!structure.units.length&&<p className="text-sm text-slate-500">No units added yet.</p>}</section>
  <section className="my-6"><h3 className="mb-3 font-semibold">Official syllabus document</h3>{view?.document_filename?<><p className="break-all text-sm">{view.document_filename} · Uploaded {view.document_uploaded_at?new Date(view.document_uploaded_at).toLocaleDateString():'—'} by {view.document_uploaded_by}</p><Button className="mt-3" size="sm" variant="outline" onClick={()=>{setError('');void qpgApi.get<{url:string}>(`${root}/versions/${view.id}/document`).then(r=>window.open(r.url,'_blank','noopener,noreferrer')).catch(e=>setError(collegeError(e)));}}>View official document</Button></>:<p className="text-sm text-slate-500">No official document attached.</p>}{editable&&current&&<form onSubmit={upload} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">Official document<input className={input} name="file" type="file" required accept=".pdf,.docx"/></label><Button type="submit" variant="outline" disabled={busy}>Attach document</Button><p className="text-xs text-slate-500 sm:col-span-2">PDF or DOCX · up to 10 MB · retained as a reference without automatic extraction.</p></form>}</section>
  <section><h3 className="mb-3 font-semibold">Syllabus history</h3>{versions.map(v=><div className="mb-2 flex flex-wrap items-center justify-between gap-3" key={v.id}><p className="text-sm">Version {v.version} · {label(v.status)} · Created {new Date(v.created_at).toLocaleDateString()} by {v.created_by}{v.published_at?` · Published ${new Date(v.published_at).toLocaleDateString()}`:''}</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void qpgApi.get<Version>(`${root}/versions/${v.id}`).then(setHistory).catch(e=>setError(collegeError(e)))}>View version {v.version}</Button></div>)}</section>
 </>}
 {form&&<Dialog title={`${form.item?'Edit':'Add'} ${form.kind==='cos'?'CO':form.kind==='units'?'Unit':'Topic'}`} onClose={()=>setForm(null)}><form className="grid gap-4" onSubmit={saveItem}>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<label className="grid gap-2 text-sm">Code<input name="code" className={input} required maxLength={80} defaultValue={form.item?.code}/></label><label className="grid gap-2 text-sm">Title / description<textarea name="title" className={input} required maxLength={500} defaultValue={form.item?.title}/></label><Button disabled={busy} type="submit">Save item</Button></form></Dialog>}
 </section>;
}
