import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
type Entry={code:string;title:string};
type Unit=Entry&{topics:Entry[]};
export type Course={code:string;name:string;cos:Entry[];units:Unit[];warnings:string[];source_text?:string;year_number?:number|null;semester_number?:number|null;program_name?:string|null;branch_name?:string|null};
const input='w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900';
export default function QpgSyllabusExtractPanel({root,revision,target,disabled,canSave=true,onChooseSubject,initialCourse,onCourseChange,onImport}:{root:string;revision:number;target:string;disabled:boolean;canSave?:boolean;onChooseSubject?:()=>void;initialCourse?:Course;onCourseChange?:(course:Course)=>void;onImport:(payload:{expected_revision:number;cos:Entry[];units:Unit[]})=>Promise<boolean>}){
 const [courses,setCourses]=useState<Course[]>(initialCourse?[initialCourse]:[]);const [selected,setSelected]=useState(0);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const course=courses[selected];
 const missing=course?[...course.cos,...course.units,...course.units.flatMap(u=>u.topics)].some(e=>!e.code.trim()||!e.title.trim()):false;
 const [reviewed,setReviewed]=useState(false);
 function change(next:Course){setReviewed(false);onCourseChange?.(next);setCourses(old=>old.map((c,i)=>i===selected?next:c));}
 async function extract(){if(!file)return;setBusy(true);setError('');setNotice('');try{const body=new FormData();body.append('file',file);const response=await apiClient.post<{courses:Course[]}>(`/v3/college/question-papers/${root}/extract`,body,{headers:{'Content-Type':'multipart/form-data'},timeout:125000});setCourses(response.data.courses);setSelected(0);}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 function fields(entry:Entry,onChange:(e:Entry)=>void){return <div className="grid gap-2 sm:grid-cols-[100px_1fr]"><input aria-label="Item code" className={input} value={entry.code} maxLength={80} onChange={e=>onChange({...entry,code:e.target.value})}/><textarea aria-label="Item description" className={input} value={entry.title} maxLength={500} onChange={e=>onChange({...entry,title:e.target.value})}/></div>;}
 return <section className="mb-6 rounded-xl border border-indigo-200 bg-white p-5 dark:bg-slate-900"><h3 className="font-semibold">{initialCourse?`Review syllabus · ${initialCourse.name}`:"Extract syllabus from a document"}</h3><p className="mt-1 text-sm text-slate-500">{initialCourse?'Review the outcomes, units and topics below. Use Change Subject above to choose another course.':'Upload a curriculum, choose its course and review the extracted outcomes, units and topics.'}</p>{!initialCourse&&<><div className="my-4 flex flex-wrap items-center gap-3"><input type="file" aria-label="Syllabus to extract" accept=".pdf,.docx" disabled={disabled||busy} onChange={e=>{setFile(e.target.files?.[0]||null);setCourses([]);setNotice('');}}/><Button disabled={disabled||busy||!file} onClick={()=>void extract()}>{busy?'Extracting…':'Extract & review'}</Button></div><p className="text-xs text-slate-500">PDF or DOCX · 10 MB maximum · PDF up to 250 pages. Scanned documents need OCR first.</p></>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>}
 {course&&<div className="mt-5 border-t pt-4">{!initialCourse&&<label className="grid gap-2 text-sm">Choose course ({courses.length} found)<select className={input} value={selected} disabled={busy||disabled} onChange={e=>setSelected(Number(e.target.value))}>{courses.map((c,i)=><option key={i} value={i}>{c.code} · {c.name}</option>)}</select></label>}<div className="my-4 grid gap-3 sm:grid-cols-3">{[["1","Review content","Current step"],["2","Save draft","Keep your reviewed syllabus"],["3","Review & Publish","Enable questions and papers"]].map(([n,title,help])=><div key={n} className={`rounded-xl border p-3 ${n==="1"?"border-indigo-300 bg-indigo-50 text-indigo-900":"border-slate-200 text-slate-500"}`}><p className="text-sm font-semibold">{n}. {title}</p><p className="mt-1 text-xs">{help}</p></div>)}</div><p className="mb-4 text-sm text-slate-500">Reviewing syllabus for <strong>{target}</strong>. Saving keeps a draft; publishing is a separate step.</p><details className="mb-4 text-sm"><summary className="cursor-pointer">Extraction notes</summary><ul className="list-disc pl-5">{course.warnings.map((w,i)=><li key={i}>{w}</li>)}<li>The original curriculum is retained in Saved curricula. Attaching a document to a published syllabus version is a separate action.</li></ul></details>
 {course.source_text&&<details className="mb-4 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Compare with extracted document text</summary><p className="my-2 text-xs text-slate-500">Original extracted course text, before your edits. PDF line breaks may differ from the printed document.</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap text-sm">{course.source_text}</pre></details>}
 <fieldset disabled={busy||disabled} className="space-y-4"><div><h4 className="mb-2 font-medium">Course Outcomes ({course.cos.length})</h4>{course.cos.map((co,i)=><div key={i} className="mb-2">{fields(co,next=>change({...course,cos:course.cos.map((c,j)=>j===i?next:c)}))}<button className="mt-1 text-xs text-slate-500" onClick={()=>change({...course,cos:course.cos.filter((_,j)=>i!==j)})}>Remove outcome</button></div>)}<Button size="sm" variant="outline" onClick={()=>change({...course,cos:[...course.cos,{code:`CO${course.cos.length+1}`,title:''}]})}>Add outcome</Button></div>
 <div><h4 className="mb-2 font-medium">Units and Topics ({course.units.length} units)</h4>{course.units.map((unit,i)=><details key={i} className="mb-3 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">{unit.code} · {unit.title} · {unit.topics.length} topics</summary><div className="mt-3 space-y-3">{fields(unit,next=>change({...course,units:course.units.map((u,j)=>i===j?{...u,...next}:u)}))}{unit.topics.map((topic,j)=><div key={j}>{fields(topic,next=>change({...course,units:course.units.map((u,k)=>k===i?{...u,topics:u.topics.map((t,n)=>n===j?next:t)}:u)}))}<button className="mt-1 text-xs text-slate-500" onClick={()=>change({...course,units:course.units.map((u,k)=>k===i?{...u,topics:u.topics.filter((_,n)=>n!==j)}:u)})}>Remove topic</button></div>)}<Button size="sm" variant="outline" onClick={()=>change({...course,units:course.units.map((u,k)=>k===i?{...u,topics:[...u.topics,{code:`T${u.topics.length+1}`,title:''}]}:u)})}>Add topic</Button><Button size="sm" variant="ghost" onClick={()=>change({...course,units:course.units.filter((_,k)=>k!==i)})}>Remove unit</Button></div></details>)}<Button size="sm" variant="outline" onClick={()=>change({...course,units:[...course.units,{code:`U${course.units.length+1}`,title:'',topics:[]}]})}>Add unit</Button></div></fieldset>
 <div className="sticky bottom-0 mt-5 rounded-xl border bg-white p-4 shadow-sm dark:bg-slate-900"><label className="mb-3 flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1 h-4 w-4" checked={reviewed} disabled={busy||disabled} onChange={e=>setReviewed(e.target.checked)}/>I have checked the outcomes, units and topics against the document.</label>{missing&&<p className="mb-3 text-sm text-amber-700">Complete every code and description before saving.</p>}{error&&<p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">{canSave?'Review every item. Import saves a draft; publish after checking it.':'Select or link a subject below to save. Your extraction preview stays here.'}</p><div className="flex flex-wrap gap-2">{!canSave&&onChooseSubject&&<Button variant="outline" onClick={onChooseSubject}>Choose destination subject</Button>}<Button disabled={busy||disabled||!canSave||!reviewed||missing||(!course.cos.length&&!course.units.length)} onClick={()=>void (async()=>{setBusy(true);setError('');try{const ok=await onImport({expected_revision:revision,cos:course.cos,units:course.units});if(ok){setCourses([]);setNotice('Reviewed items added to your draft. Open Manual Entry to check and publish.');}}catch(e){setError(collegeError(e));}finally{setBusy(false);}})()}>{busy?'Saving draft…':'Save draft & continue'}</Button></div></div></div></div>}
 </section>;
}
