import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
import Dialog from './QpgDialog';
import QpgRenderPreview from './QpgRenderPreview';
import type {RenderModel} from './QpgRenderPreview';
export type TemplateConfig={show_question_mapping?:boolean;header_alignment:string;institution_alignment:string;logo_placement:string;show_logo:boolean;show_address:boolean;show_page_numbers:boolean;show_fields:string[];address_text:string;contact_text:string;header_text:string;footer_text:string;section_style:string;numbering:string};
export type PaperTemplate={id:string;name:string;description:string;configuration:TemplateConfig;version:number;revision:number;status:string;used:boolean;has_logo:boolean};
const fields=['institution_short_name','program','branch','year','semester','academic_session','examination_session','course_code','course_name','duration','maximum_marks'];
const defaults:TemplateConfig={header_alignment:'CENTER',institution_alignment:'CENTER',logo_placement:'CENTER',show_logo:true,show_address:true,show_page_numbers:true,show_fields:fields.slice(1),address_text:'',contact_text:'',header_text:'',footer_text:'',section_style:'NORMAL',numbering:'CONTINUOUS'};
const input='w-full rounded-xl border p-2 text-sm dark:bg-slate-900';
export default function QpgTemplatesPanel(){
 const [rows,setRows]=useState<PaperTemplate[]>([]),[canWrite,setCanWrite]=useState(false),[branding,setBranding]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState<{row?:PaperTemplate;name:string;description:string;config:TemplateConfig;file?:File}|null>(null),[preview,setPreview]=useState<RenderModel|null>(null);
 async function refresh(){const r=await qpgApi.get<{items:PaperTemplate[];can_write:boolean;branding:{name:string}}>('templates');setRows(r.items||[]);setCanWrite(r.can_write);setBranding(r.branding?.name||'');}
 useEffect(()=>{const c=new AbortController();qpgApi.get<{items:PaperTemplate[];can_write:boolean;branding:{name:string}}>('templates',c.signal).then(r=>{setRows(r.items||[]);setCanWrite(r.can_write);setBranding(r.branding?.name||'');}).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 async function save(){if(!editor)return;const e=editor;let row=await qpgApi.save<PaperTemplate>(e.row?`templates/${e.row.id}`:'templates',{name:e.name,description:e.description,configuration:e.config,...(e.row?{expected_revision:e.row.revision}:{})},!!e.row);setEditor({...e,row});if(e.file){const data=new FormData();data.append('file',e.file);row=(await apiClient.post<PaperTemplate>(`/v3/college/question-papers/templates/${row.id}/logo?expected_revision=${row.revision}`,data,{headers:{'Content-Type':'multipart/form-data'}})).data;}setEditor(null);await refresh();}
 return <section className="erp-card"><div className="flex flex-wrap justify-between gap-3"><h2>Paper Templates</h2>{canWrite&&<Button onClick={()=>setEditor({name:'',description:'',config:{...defaults}})}>Create Template</Button>}</div><p className="my-3 text-sm text-slate-500">Institution branding: {branding||'maintained by institution management'}. Official exports capture the exact template version. Used layouts require a new version.</p>{error&&<p role="alert" className="my-3 text-amber-700">{error}</p>}{rows.map(t=><article className="my-3 rounded-xl border p-4" key={t.id}><h3 className="font-semibold">{t.name} · v{t.version}</h3><p className="text-sm">{label(t.status)} · {t.used?'Captured by official export':'Not yet used'} · {t.has_logo?'Logo uploaded':'No uploaded logo'}</p><p className="my-2 text-sm">{t.description}</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{setPreview((await qpgApi.get<{render_model:RenderModel}>(`templates/${t.id}/preview`)).render_model);})}>Preview Template</Button>{canWrite&&<>{t.status==='DRAFT'&&!t.used?<Button variant="outline" disabled={busy} onClick={()=>setEditor({row:t,name:t.name,description:t.description,config:{...t.configuration}})}>Edit Draft Template</Button>:<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{const r=await qpgApi.save<PaperTemplate>(`templates/${t.id}/new-version`,{expected_revision:t.revision});setEditor({row:r,name:r.name,description:r.description,config:{...r.configuration}});await refresh();})}>New Template Version</Button>}<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await qpgApi.save(`templates/${t.id}/activate`,{expected_revision:t.revision,active:t.status!=='ACTIVE'});await refresh();})}>{t.status==='ACTIVE'?'Deactivate Template':'Activate Template'}</Button></>}</div></article>)}{!rows.length&&<p className="my-4 text-sm">The Default Institution Template is available for locked-paper exports.</p>}
 {editor&&<Dialog title={editor.row?'Edit Draft Template':'Create Paper Template'} onClose={()=>setEditor(null)}><form className="grid gap-3" onSubmit={e=>{e.preventDefault();void run(save);}}><label>Template name<input aria-label="Template name" className={input} value={editor.name} maxLength={120} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label>Description<textarea className={input} value={editor.description} maxLength={500} onChange={e=>setEditor({...editor,description:e.target.value})}/></label>{(['header_text','footer_text','address_text','contact_text'] as const).map(k=><label key={k}>{label(k)}<input aria-label={label(k)} className={input} value={editor.config[k]} maxLength={k==='address_text'?500:300} onChange={e=>setEditor({...editor,config:{...editor.config,[k]:e.target.value}})}/></label>)}{(['header_alignment','institution_alignment','logo_placement','section_style','numbering'] as const).map(k=><label key={k}>{label(k)}<select aria-label={label(k)} className={input} value={editor.config[k]} onChange={e=>setEditor({...editor,config:{...editor.config,[k]:e.target.value}})}>{(k==='section_style'?['NORMAL','UPPERCASE']:k==='numbering'?['CONTINUOUS','SECTION']:['LEFT','CENTER','RIGHT']).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}{(['show_logo','show_address','show_page_numbers','show_question_mapping'] as const).map(k=><label className="flex gap-2" key={k}><input type="checkbox" checked={Boolean(editor.config[k])} onChange={e=>setEditor({...editor,config:{...editor.config,[k]:e.target.checked}})}/>{label(k)}</label>)}<fieldset><legend className="mb-2 font-semibold">Displayed exam fields</legend><div className="grid gap-2 sm:grid-cols-2">{fields.map(k=><label key={k} className="flex gap-2 text-sm"><input type="checkbox" disabled={['duration','maximum_marks'].includes(k)} checked={['duration','maximum_marks'].includes(k)||editor.config.show_fields.includes(k)} onChange={e=>setEditor({...editor,config:{...editor.config,show_fields:e.target.checked?[...editor.config.show_fields,k]:editor.config.show_fields.filter(x=>x!==k)}})}/>{label(k)}</label>)}</div></fieldset><label>Optional PNG/JPEG logo (1 MB)<input aria-label="Template logo" type="file" accept="image/png,image/jpeg" onChange={e=>setEditor({...editor,file:e.target.files?.[0]})}/></label><Button type="submit" disabled={busy||!editor.name.trim()}>Save Template Draft</Button></form></Dialog>}
 {preview&&<Dialog title="Illustrative Template Preview" onClose={()=>setPreview(null)}><p className="my-2 text-sm">Example layout only. Official documents use the exact locked paper.</p><QpgRenderPreview model={preview}/></Dialog>}
 </section>;
}
