import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {qpgApi,label} from '@/api/qpgApi';
import {collegeError} from '@/api/collegeApi';
type Check={status:string;explanation:string;origin:string;confidence:number|null;detected_bloom?:string|null;detected_difficulty?:string|null;suggestion?:string};
type Run={run_id:string;question_version:number;current_question_version:number;stale:boolean;overall_status:string;overall_score:number|null;checks:Record<string,Check>;warnings:string[];failures:string[];evidence:{filename:string;location:string;quote:string}[];suggestions:string[];claims:{claim:string;supported:boolean;explanation:string;severity:string}[];duplicate_matches:{question_id:string;question_text:string;match:string}[];source_support:string;validated_at:string};
export default function QpgValidationPanel({questionId,version,canWrite,archived}:{questionId:string;version:number;canWrite:boolean;archived:boolean}){
 const [runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setError('');qpgApi.get<{items:Run[]}>(`questions/${questionId}/validation-history`,c.signal).then(r=>setRuns(r.items||[])).catch(e=>{if(!c.signal.aborted)setError(collegeError(e));});return()=>c.abort();},[questionId,version,canWrite]);
 const current=runs.find(r=>r.question_version===version&&!r.stale);const run=selected?runs.find(r=>r.run_id===selected):current||runs[0];const stale=!!run&&(run.stale||run.question_version!==version);
 async function validate(){setBusy(true);setError('');try{const result=await qpgApi.save<Run>(`questions/${questionId}/validate`,{expected_version:version});setRuns(previous=>[result,...previous]);setSelected('');}catch(e){setError(collegeError(e));}finally{setBusy(false);}}
 return <section className="mt-5 rounded-xl border p-4" aria-label="AI Validation"><h3 className="font-semibold">AI Validation</h3><p className="my-2 text-sm text-slate-500">Advisory assessment. Faculty approval remains required. Scores and source support do not prove factual correctness.</p>{error&&<p role="alert" className="my-2 text-red-700">{error}</p>}{canWrite&&!archived&&<Button variant="outline" disabled={busy} onClick={()=>void validate()}>{busy?'Validating…':runs.length?'Revalidate':'Run Validation'}</Button>}{busy&&<p role="status">Checking this question version…</p>}{!run&&!busy&&<p className="my-2 text-sm">This question version has not been validated.</p>}
 {runs.length>0&&<label className="my-3 grid gap-2 text-sm">View Previous Validation<select aria-label="View Previous Validation" className="rounded-xl border bg-white p-2 dark:bg-slate-900" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Current / latest assessment</option>{runs.map(r=><option value={r.run_id} key={r.run_id}>Version {r.question_version} · {new Date(r.validated_at).toLocaleString()} · {label(r.overall_status)}{r.stale||r.question_version!==version?' · Stale':''}</option>)}</select></label>}
 {run&&<><p className="my-2 font-medium">{stale?'Stale — revalidation required for this version':label(run.overall_status)}{run.overall_score!==null?` · Advisory score ${run.overall_score}/100`:''}</p><p className="text-xs text-slate-500">Validated question version {run.question_version} · {new Date(run.validated_at).toLocaleString()} · {label(run.source_support)}</p>{stale&&<p className="my-2 text-amber-700">Historical assessment; it does not apply to the current question version or syllabus.</p>}
 {!canWrite&&<p className="my-3 text-sm text-slate-500">Assessment details require academic write permission.</p>}
 {canWrite&&<> <div className="my-3 space-y-2">{Object.entries(run.checks).map(([key,c])=><article key={key} className="rounded-lg border p-3 text-sm"><p className="font-medium">{label(key)} · {c.status}</p><p>{c.explanation}</p><p className="text-xs text-slate-500">{label(c.origin)}{c.confidence!==null?` · Confidence ${Math.round(c.confidence*100)}%`:''}{c.detected_bloom?` · Detected ${c.detected_bloom}`:''}{c.detected_difficulty?` · Detected ${label(c.detected_difficulty)}`:''}</p>{c.suggestion&&<p>Suggestion: {c.suggestion}</p>}</article>)}</div>
 {run.warnings.map((w,i)=><p key={i} className="my-2 text-sm text-amber-700">{w}</p>)}{run.failures.map((w,i)=><p key={i} className="my-2 text-sm text-red-700">{w}</p>)}{run.evidence.length>0&&<h4 className="mt-3 font-semibold">Source evidence</h4>}{run.evidence.map((e,i)=><blockquote key={i} className="my-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-900"><p>{e.filename} · {e.location}</p><p className="whitespace-pre-wrap">{e.quote}</p></blockquote>)}{run.claims.map((c,i)=><p key={i} className="my-2 text-sm">{c.supported?'Source-supported assessment':'Not supported by the provided source'} · {label(c.severity)}: {c.claim} — {c.explanation}</p>)}{run.duplicate_matches.map((m,i)=><p key={i} className="my-2 text-sm">{label(m.match)}: {m.question_text}</p>)}{run.suggestions.map((s,i)=><p key={i} className="my-2 text-sm">Suggested improvement: {s}</p>)}</>}</>}
 </section>;
}
