import { useState } from "react";
import { Filter, Plus, Trash2, X } from "lucide-react";
import { btn, field } from "./interviewAgentTypes";

export type ResultRule = { id: string; field: string; operator: string; value: string; valueEnd?: string; values?: string[] };
export type ResultFilterOptions = { departmentPrograms: [string, string][]; interviewRounds: [string, string][] };
type Definition = { label: string; kind: "number" | "enum" | "date" | "catalog"; options?: [string, string][] };

const resultFilterDefinitions: Record<string, Definition> = {
  department_program: { label: "Department / Program", kind: "catalog" }, interview_score: { label: "Interview Score", kind: "number" }, pri: { label: "PRI", kind: "number" }, job_fit: { label: "Job Fit", kind: "number" },
  readiness: { label: "Readiness", kind: "enum", options: [["Interview Ready", "Interview Ready"], ["Approaching Ready", "Approaching Ready"], ["Developing", "Developing"], ["Not Ready", "Not Ready"]] },
  recommendation: { label: "AI Recommendation", kind: "enum", options: [["Strong Hire", "Strong Hire"], ["Hire", "Hire"], ["Consider", "Consider"], ["Reject", "Reject"], ["Review Required", "Review Required"], ["Hold for Review", "Hold for Review"], ["Insufficient Evidence", "Insufficient Evidence"]] },
  recommendation_confidence: { label: "Recommendation Confidence", kind: "number" }, evaluation_confidence: { label: "Evaluation Confidence", kind: "number" }, assessment_coverage: { label: "Assessment Coverage", kind: "number" }, proctoring_score: { label: "AI Proctor Score", kind: "number" },
  officer_decision: { label: "Officer Decision", kind: "enum", options: [["undecided", "Undecided"], ["shortlist", "Shortlisted"], ["hold", "Hold"], ["reject", "Rejected"]] }, student_result: { label: "Student Result", kind: "enum", options: [["hidden", "Hidden"], ["scheduled", "Scheduled"], ["released", "Released"]] }, interview_round: { label: "Interview Round", kind: "catalog" }, completion_date: { label: "Completion Date", kind: "date" },
  integrity_status: { label: "AI Proctor Review", kind: "enum", options: [["review_required", "Review Required"], ["no_review_required", "No Review Required"], ["not_available", "Not Assessed"]] }, evaluation_status: { label: "Evaluation Status", kind: "enum", options: [["released", "Completed"], ["held_for_review", "Needs Review"], ["incomplete", "Incomplete"]] },
};
const numberOps = [["equals", "Equals"], ["greater_than", "Greater than"], ["less_than", "Less than"], ["between", "Between"]] as const;
const enumOps = [["equals", "Is"], ["not_equals", "Is not"], ["is_any_of", "Any of"]] as const;
const catalogOps = [["equals", "Is"], ["not_equals", "Is not"]] as const;
const dateOps = [["on", "On"], ["before", "Before"], ["after", "After"], ["between", "Between"]] as const;
const defaultOperator = (name: string) => resultFilterDefinitions[name].kind === "date" ? "on" : "equals";
const newRule = (): ResultRule => ({ id: crypto.randomUUID(), field: "department_program", operator: "equals", value: "" });

export default function ResultCohortBuilder({ rules, setRules, matchMode, setMatchMode, onReset, options }: { rules: ResultRule[]; setRules: (rules: ResultRule[]) => void; matchMode: "all" | "any"; setMatchMode: (value: "all" | "any") => void; total: number; excludeReview: boolean; setExcludeReview: (value: boolean) => void; onReset: () => void; options: ResultFilterOptions }) {
  const [open, setOpen] = useState(false), [draft, setDraft] = useState<ResultRule[]>(rules), [draftMode, setDraftMode] = useState<"all" | "any">(matchMode);
  const update = (id: string, change: Partial<ResultRule>) => setDraft(current => current.map(item => item.id === id ? { ...item, ...change } : item));
  const values = (item: ResultRule, definition: Definition) => definition.options || (item.field === "department_program" ? options.departmentPrograms : options.interviewRounds);
  return <div className="relative"><button className={`${btn} ${rules.length ? "border-indigo-300 bg-indigo-50 text-indigo-700" : ""}`} onClick={() => { if (!open) { setDraft(rules); setDraftMode(matchMode); } setOpen(value => !value); }}><Filter size={16} />Filters{rules.length ? ` (${rules.length})` : ""}</button>
    {open && <section className="absolute right-0 z-30 mt-2 w-[min(900px,calc(100vw-3rem))] rounded-2xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Advanced filters</h3><p className="text-xs text-slate-500">Build a cohort with controls matched to each field type.</p></div><button aria-label="Close filters" className="rounded-lg p-2 hover:bg-slate-100" onClick={() => setOpen(false)}><X size={18} /></button></div>
      <div className="mt-4 space-y-2">{draft.map(item => { const definition = resultFilterDefinitions[item.field], operators = definition.kind === "number" ? numberOps : definition.kind === "date" ? dateOps : definition.kind === "catalog" ? catalogOps : enumOps, choices = values(item, definition); return <div className="grid items-end gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-[1.2fr_.8fr_1.2fr_auto] dark:bg-slate-800/60" key={item.id}><label className="text-xs font-medium text-slate-500">Field<select className={`${field} mt-1`} value={item.field} onChange={event => { const name = event.target.value; update(item.id, { field: name, operator: defaultOperator(name), value: "", valueEnd: "", values: [] }); }}>{Object.entries(resultFilterDefinitions).map(([value, data]) => <option value={value} key={value}>{data.label}</option>)}</select></label><label className="text-xs font-medium text-slate-500">Operator<select className={`${field} mt-1`} value={item.operator} onChange={event => update(item.id, { operator: event.target.value, valueEnd: "", values: [] })}>{operators.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><div className="text-xs font-medium text-slate-500">Value{item.operator === "is_any_of" ? <div className="mt-1 max-h-32 overflow-auto rounded-xl border bg-white p-2 dark:border-slate-700 dark:bg-slate-900">{choices.map(([value, label]) => <label className="flex gap-2 py-1 text-sm" key={value}><input type="checkbox" checked={item.values?.includes(value) || false} onChange={event => update(item.id, { values: event.target.checked ? [...(item.values || []), value] : (item.values || []).filter(current => current !== value) })} />{label}</label>)}</div> : definition.kind === "enum" || definition.kind === "catalog" ? <select className={`${field} mt-1`} value={item.value} onChange={event => update(item.id, { value: event.target.value })}><option value="">Select value</option>{choices.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select> : item.operator === "between" ? <div className="mt-1 grid grid-cols-2 gap-2"><input className={field} type={definition.kind === "date" ? "date" : "number"} value={item.value} onChange={event => update(item.id, { value: event.target.value })} /><input className={field} type={definition.kind === "date" ? "date" : "number"} value={item.valueEnd || ""} onChange={event => update(item.id, { valueEnd: event.target.value })} /></div> : <input className={`${field} mt-1`} type={definition.kind === "date" ? "date" : "number"} value={item.value} onChange={event => update(item.id, { value: event.target.value })} />}</div><button aria-label={`Remove ${definition.label} filter`} className={`${btn} h-[42px] px-3`} onClick={() => setDraft(current => current.filter(rule => rule.id !== item.id))}><Trash2 size={16} /></button></div>; })}</div>
      <div className="mt-4 flex flex-wrap items-end gap-3 border-t pt-4"><button className={btn} onClick={() => setDraft(current => [...current, newRule()])}><Plus size={16} />Add rule</button><label className="text-xs font-medium text-slate-500">Match<select className={`${field} mt-1 w-32`} value={draftMode} onChange={event => setDraftMode(event.target.value as "all" | "any")}><option value="all">All rules</option><option value="any">Any rule</option></select></label><div className="ml-auto flex gap-2"><button className={btn} onClick={() => { setDraft([]); onReset(); setOpen(false); }}>Reset</button><button className={`${btn} bg-indigo-600 text-white`} onClick={() => { setRules(draft); setMatchMode(draftMode); setOpen(false); }}>Apply filters</button></div></div></section>}
  </div>;
}
