import {useMemo,useState} from 'react';
import {Plus,Save,Trash2,X} from 'lucide-react';
import {btn,field,panel} from './interviewAgentTypes';

export type ResultRule={id:string;field:string;operator:string;value:string;valueEnd?:string};
export type ResultFilterOptions={departmentPrograms:[string,string][];interviewRounds:[string,string][]};
type Definition={label:string;kind:'number'|'enum'|'date'|'catalog';options?:[string,string][]};
export const resultFilterDefinitions:Record<string,Definition>={
 department_program:{label:'Department / Program',kind:'catalog'},interview_score:{label:'Interview Score',kind:'number'},pri:{label:'PRI',kind:'number'},job_fit:{label:'Job Fit',kind:'number'},readiness:{label:'Readiness',kind:'enum',options:[['Interview Ready','Interview Ready'],['Approaching Ready','Approaching Ready'],['Developing','Developing'],['Not Ready','Not Ready']]},recommendation:{label:'AI Recommendation',kind:'enum',options:[['Strong Hire','Strong Hire'],['Hire','Hire'],['Consider','Consider'],['Reject','Reject'],['Review Required','Review Required']]},recommendation_confidence:{label:'AI Recommendation Confidence',kind:'number'},evaluation_confidence:{label:'Evaluation Confidence',kind:'number'},assessment_coverage:{label:'Assessment Coverage',kind:'number'},officer_decision:{label:'Officer Decision',kind:'enum',options:[['undecided','Undecided'],['shortlist','Shortlist'],['hold','Hold'],['reject','Reject']]},student_result:{label:'Student Result',kind:'enum',options:[['hidden','Hidden'],['scheduled','Scheduled'],['released','Released']]},interview_round:{label:'Interview Round',kind:'catalog'},completion_date:{label:'Completion Date',kind:'date'},integrity_status:{label:'Integrity / Proctor Review Status',kind:'enum',options:[['clear','Clear'],['review_required','Review Required']]},evaluation_status:{label:'Evaluation Status',kind:'enum',options:[['released','Comparable'],['held_for_review','Needs Review'],['incomplete','Incomplete']]}
};
const numericOperators=[['at_least','At least'],['at_most','At most']] as const;
const enumOperators=[['equals','Equals'],['not_equals','Does not equal'],['is_empty','Is empty'],['is_not_empty','Is not empty']] as const;
const dateOperators=[['on','On'],['before','Before'],['after','After'],['between','Between']] as const;
const quickViews:[string,string,ResultRule[]][]=[
 ['high-readiness','High Readiness, Undecided',[rule('readiness','equals','Interview Ready'),rule('officer_decision','equals','undecided')]],
 ['manual-review','Needs Manual Review',[rule('evaluation_status','equals','held_for_review')]],
 ['shortlist-review','Ready to Shortlist Review',[rule('evaluation_status','equals','released'),rule('readiness','equals','Interview Ready'),rule('officer_decision','equals','undecided')]],
 ['release-ready','Result Ready to Release',[rule('officer_decision','not_equals','undecided'),rule('student_result','equals','hidden')]],
 ['integrity-review','Integrity Review',[rule('integrity_status','equals','review_required')]],
];
function defaultOperator(fieldName:string){const kind=resultFilterDefinitions[fieldName].kind;return kind==='number'?'at_least':kind==='date'?'on':'equals'}
function rule(fieldName='department_program',operator=defaultOperator(fieldName),value=''):ResultRule{return{id:crypto.randomUUID(),field:fieldName,operator,value}}
export default function ResultCohortBuilder({rules,setRules,matchMode,setMatchMode,total,excludeReview,setExcludeReview,onReset,options}:{rules:ResultRule[];setRules:(rules:ResultRule[])=>void;matchMode:'all'|'any';setMatchMode:(value:'all'|'any')=>void;total:number;excludeReview:boolean;setExcludeReview:(value:boolean)=>void;onReset:()=>void;options:ResultFilterOptions}){
 const [saveOpen,setSaveOpen]=useState(false),[viewName,setViewName]=useState('');
 const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem('voicedots-result-views')||'[]') as {name:string;rules:ResultRule[];matchMode:'all'|'any'}[]}catch{return[]}},[saveOpen]);
 const update=(id:string,change:Partial<ResultRule>)=>setRules(rules.map(item=>item.id===id?{...item,...change}:item));
 const save=()=>{if(!viewName.trim())return;const next=[...saved.filter(item=>item.name!==viewName.trim()),{name:viewName.trim(),rules,matchMode}];localStorage.setItem('voicedots-result-views',JSON.stringify(next));setViewName('');setSaveOpen(false)};
 const values=(item:ResultRule,definition:Definition)=>definition.options||(item.field==='department_program'?options.departmentPrograms:options.interviewRounds);
 return <div className={`${panel} space-y-4`}>
  <div><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Quick placement views</p><div className="mt-2 flex flex-wrap gap-2">{quickViews.map(([id,label,template])=><button key={id} className={btn} onClick={()=>{setRules(template.map(item=>({...item,id:crypto.randomUUID()})));setMatchMode('all')}}>{label}</button>)}{saved.map(view=><button key={view.name} className={btn} onClick={()=>{setRules(view.rules.map(item=>({...item,id:crypto.randomUUID()})));setMatchMode(view.matchMode)}}>{view.name}</button>)}</div></div>
  <div className="flex flex-wrap items-end gap-3 border-t pt-4"><button className={btn} onClick={()=>setRules([...rules,rule()])}><Plus size={16}/>Add filter</button><label className="text-sm">Match<select className={`${field} mt-1 w-auto min-w-40`} value={matchMode} onChange={event=>setMatchMode(event.target.value as 'all'|'any')}><option value="all">All rules</option><option value="any">Any rule</option></select></label><button className={btn} disabled={!rules.length} onClick={()=>setSaveOpen(!saveOpen)}><Save size={16}/>Save view</button><label className="ml-auto flex items-center gap-2 pb-2 text-sm"><input type="checkbox" checked={excludeReview} onChange={event=>setExcludeReview(event.target.checked)}/>Exclude Review Required</label>{(rules.length>0||excludeReview)&&<button className={btn} onClick={onReset}><X size={16}/>Clear</button>}</div>
  {saveOpen&&<div className="flex max-w-lg gap-2"><input className={field} value={viewName} onChange={event=>setViewName(event.target.value)} placeholder="View name"/><button className={btn} disabled={!viewName.trim()} onClick={save}>Save</button></div>}
  {rules.length>0&&<div className="space-y-2">{rules.map(item=>{const definition=resultFilterDefinitions[item.field];const operators=definition.kind==='number'?numericOperators:definition.kind==='date'?dateOperators:enumOperators;const noValue=['is_empty','is_not_empty'].includes(item.operator);const optionValues=values(item,definition);return <div className="grid items-end gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:grid-cols-[minmax(180px,1.2fr)_minmax(140px,.8fr)_minmax(180px,1.2fr)_auto] dark:border-slate-700 dark:bg-slate-900" key={item.id}><label className="text-xs font-medium text-slate-500">Field<select className={`${field} mt-1`} value={item.field} onChange={event=>{const next=event.target.value;update(item.id,{field:next,operator:defaultOperator(next),value:'',valueEnd:''})}}>{Object.entries(resultFilterDefinitions).map(([value,item])=><option key={value} value={value}>{item.label}</option>)}</select></label><label className="text-xs font-medium text-slate-500">Operator<select className={`${field} mt-1`} value={item.operator} onChange={event=>update(item.id,{operator:event.target.value,valueEnd:''})}>{operators.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="text-xs font-medium text-slate-500"><span>Value</span>{noValue?<div className="mt-1 flex h-[42px] items-center rounded-xl border border-dashed px-3 text-slate-400">No value needed</div>:definition.kind==='catalog'||definition.kind==='enum'?<select aria-label={`${definition.label} value`} className={`${field} mt-1`} value={item.value} onChange={event=>update(item.id,{value:event.target.value})}><option value="">Select value</option>{optionValues.map(([value,label])=><option key={`${value}-${label}`} value={value}>{label}</option>)}</select>:definition.kind==='date'&&item.operator==='between'?<div className="mt-1 grid grid-cols-2 gap-2"><input aria-label={`${definition.label} start`} className={field} type="date" value={item.value} onChange={event=>update(item.id,{value:event.target.value})}/><input aria-label={`${definition.label} end`} className={field} type="date" value={item.valueEnd||''} onChange={event=>update(item.id,{valueEnd:event.target.value})}/></div>:<input aria-label={`${definition.label} value`} className={`${field} mt-1`} type={definition.kind==='date'?'date':'number'} min={definition.kind==='number'?0:undefined} max={definition.kind==='number'?100:undefined} value={item.value} onChange={event=>update(item.id,{value:event.target.value})}/>}</div><button aria-label={`Remove ${definition.label} filter`} className={`${btn} h-[42px] px-3`} onClick={()=>setRules(rules.filter(rule=>rule.id!==item.id))}><Trash2 size={16}/></button></div>})}</div>}
  <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><strong>{total} candidate{total===1?'':'s'} match</strong><button className={btn} disabled={!total} onClick={()=>document.getElementById('result-candidate-table')?.scrollIntoView({behavior:'smooth',block:'start'})}>Review {total} Candidates</button></div>
 </div>
}
