import {useState,type FormEvent} from 'react';
import {apiClient} from '@/api/apiClient';
import {collegeError} from '@/api/collegeApi';
type Result={records_created:number;records_updated:number;records_processed:number;errors_count:number;errors_sample:string[];warnings_count:number;warnings_sample:string[]};
export default function StudentImport({onComplete}:{onComplete:()=>void}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 async function template(format:string){setError('');try{const r=await apiClient.get(`/v3/college/students/template?format=${format}`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=`student-import-template.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(collegeError(e));}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),file=data.get('file');const photos=data.getAll('photos').filter(value=>value instanceof File&&value.size);data.delete('photos');for(const photo of photos)data.append('photos',photo);if(!(file instanceof File)||!file.size||file.size>10*1024*1024||!(/\.(csv|xlsx)$/i.test(file.name))){setError('Choose a CSV or Excel (.xlsx) file up to 10 MB.');return;}if([...data.values()].reduce((total,value)=>total+(value instanceof File?value.size:0),0)>10*1024*1024){setError('Roster and photos together must be at most 10 MB.');return;}setBusy(true);setError('');setResult(null);try{const response=await apiClient.post<Result>('/v3/college/students/upload',data,{headers:{'Content-Type':undefined},timeout:125000});setResult(response.data);onComplete();}catch(err){setError(collegeError(err));}finally{setBusy(false);}}
 return <details className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer font-semibold">Import students from CSV or Excel</summary><p className="my-3 text-sm text-slate-500">Download a template, fill your student details, then upload it. Fill photo_filename with each new student’s exact photo filename and attach those JPG/PNG files below. Each photo can be up to 2 MB; roster and photos together up to 10 MB. Existing roll numbers update existing students and keep their saved photo unless a replacement is supplied. Valid rows are saved; row errors are listed after import.</p><div className="mb-4 flex flex-wrap gap-3"><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>void template('csv')}>Download CSV template</button><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>void template('xlsx')}>Download Excel template</button></div><form onSubmit={upload} className="flex flex-wrap gap-3"><input aria-label="Student import file" type="file" name="file" accept=".csv,.xlsx" required disabled={busy}/><input aria-label="Student reference photos" type="file" name="photos" accept="image/jpeg,image/png" multiple disabled={busy}/><button className="rounded-lg bg-indigo-600 px-4 py-2 text-white" disabled={busy}>{busy?'Importing…':'Import students'}</button></form>{error&&<p role="alert" className="mt-3 text-rose-600">{error}</p>}{result&&<div role="status" className="mt-4 space-y-2 text-sm"><p>{result.records_created} created · {result.records_updated} updated · {result.errors_count} errors · {result.warnings_count} warnings</p>{[...(result.errors_sample||[]),...(result.warnings_sample||[])].map((message,i)=><p key={i}>{message}</p>)}{result.errors_count>result.errors_sample.length&&<p>Showing the first {result.errors_sample.length} row errors. Correct these and re-import.</p>}</div>}</details>;
}
