import {useEffect, useMemo, useState} from 'react';
import {Activity, ArrowDownToLine, CalendarDays, ChartNoAxesCombined, Clock3, X} from 'lucide-react';
import type {CollegeStudent} from '@/api/collegeApi';
import {collegeApi, collegeError} from '@/api/collegeApi';

type AnalysisReport={source:'drive'|'self_practice';label:string;assignment_id?:string|null;drive_id?:string|null;session_id?:string|null;overall_score?:number|null;readiness?:string|null;completed_at?:string|null;detail?:Record<string,any>};
type AnalysisDrive={assignment_id:string;drive_id:string;assignment_status:string;evaluation_status?:string|null;preparation_status?:string|null;invited_at?:string|null;started_at?:string|null;completed_at?:string|null;deadline_at?:string|null;assigned_at?:string|null;released_to_student_at?:string|null;company_name:string;role_title?:string|null;drive_status?:string|null;campaign_opens_at?:string|null;campaign_deadline_at?:string|null};
type Bundle={student:CollegeStudent;drives:AnalysisDrive[];reports:AnalysisReport[]};
const date=(value?:string|null)=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
const statusLabel=(value?:string|null)=>value?value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()):'Not available';
const panel='rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900';

export default function StudentAnalysis({student,onClose}:{student:CollegeStudent;onClose:()=>void}){
 const [bundle,setBundle]=useState<Bundle|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{setBundle(await collegeApi.get<Bundle>(`students/${encodeURIComponent(student.id)}/reports`))}catch(e){setError(collegeError(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[student.id]);
 const reports=bundle?.reports||[],drives=bundle?.drives||[];
 const scores=reports.map(r=>r.overall_score).filter((x):x is number=>typeof x==='number'&&Number.isFinite(x));
 const average=useMemo(()=>scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null,[scores]);
 return <div className="fixed inset-0 z-[80] flex items-stretch justify-end bg-slate-950/45" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
  <section role="dialog" aria-modal="true" aria-labelledby="student-analysis-title" className="flex h-full w-full max-w-5xl flex-col overflow-hidden bg-slate-50 shadow-2xl dark:bg-slate-950">
   <header className="flex items-start justify-between gap-4 border-b border-slate-200 bg-white px-6 py-5 dark:border-slate-800 dark:bg-slate-900">
    <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-600">Student roster · placement history</p><h2 id="student-analysis-title" className="mt-1 text-2xl font-bold">Student Analysis</h2><p className="mt-1 text-sm text-slate-500">{student.full_name} · {student.roll_number} · {student.program} / {student.department_code} · Class of {student.graduation_year}</p></div>
    <button className="rounded-xl border border-slate-200 p-2.5 hover:bg-slate-50 dark:border-slate-700" aria-label="Close student analysis" onClick={onClose}><X size={18}/></button>
   </header>
   <div className="flex-1 space-y-5 overflow-y-auto p-6">
    {error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">Student placement analysis could not be loaded. {error}<button onClick={()=>void load()} className="ml-3 font-semibold underline">Retry</button></div>}
    {busy&&!bundle&&<div role="status" className={`${panel} animate-pulse text-sm text-slate-500`}>Loading placement history and interview performance…</div>}
    {!busy&&bundle&&<>
     <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[[CalendarDays,'Drive participations',drives.length],[Activity,'Interviews taken',reports.length],[ChartNoAxesCombined,'Average interview score',average===null?'—':`${average}%`],[ArrowDownToLine,'Reports released',drives.filter(d=>d.evaluation_status==='released'||d.released_to_student_at).length]].map(([Icon,label,value]:any)=><article className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" key={label}><div className="flex items-center gap-2 text-sm text-slate-500"><Icon size={17} className="text-indigo-600"/>{label}</div><p className="mt-3 text-2xl font-bold">{value}</p></article>)}
     </div>
     <section className={panel}><div className="mb-4 flex items-center justify-between"><div><h3 className="text-lg font-semibold">Placement drives</h3><p className="mt-1 text-sm text-slate-500">All assignments, including drives with no interview attempt yet.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{drives.length} total</span></div>
      {!drives.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No placement drive assignments are recorded for this student.</p>:<div className="space-y-3">{drives.map(d=>{const report=reports.find(r=>r.source==='drive'&&r.drive_id===d.drive_id);return <article key={d.assignment_id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-semibold">{d.company_name}{d.role_title?` · ${d.role_title}`:''}</h4><p className="mt-1 text-xs text-slate-500">Assigned {date(d.assigned_at)} · Interview deadline {date(d.deadline_at||d.campaign_deadline_at)}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium dark:bg-slate-800">{statusLabel(d.assignment_status)}</span></div><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600 dark:text-slate-300"><span>Interview: {report?`Completed · ${date(report.completed_at)}`:d.started_at?'Started · '+date(d.started_at):d.invited_at?'Invited · '+date(d.invited_at):'Not started'}</span><span>Preparation: {statusLabel(d.preparation_status)}</span><span>Report: {d.evaluation_status==='released'||d.released_to_student_at?'Released':d.evaluation_status?statusLabel(d.evaluation_status):'Not available'}</span>{report&&<span>Readiness: {report.readiness||'Not assessed'}{typeof report.overall_score==='number'?` · ${Math.round(report.overall_score)}%`:''}</span>}</div></article>})}</div>}
     </section>
     <section className={panel}><div className="mb-4"><h3 className="text-lg font-semibold">Interview reports & performance</h3><p className="mt-1 text-sm text-slate-500">Placement interviews and self-practice sessions with available assessment detail.</p></div>
      {!reports.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No completed interview reports are available yet.</p>:<div className="space-y-3">{reports.map((r,i)=>{const details=r.detail||{},questions=Array.isArray(details.question_reviews)?details.question_reviews:[],dims=Array.isArray(details.agent_breakdown)?details.agent_breakdown:[];const assignment=drives.find(d=>r.assignment_id?d.assignment_id===r.assignment_id:d.drive_id===r.drive_id);const released=assignment?.evaluation_status==='released'||Boolean(assignment?.released_to_student_at);return <details key={`${r.session_id||r.label}-${i}`} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="mr-2 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium dark:bg-slate-800">{r.source==='drive'?'Placement drive':'Self-practice'}</span><strong>{r.label}</strong><p className="mt-2 text-xs text-slate-500">{date(r.completed_at)} · {r.readiness||'Readiness not assessed'}{r.overall_score!=null?` · ${Math.round(r.overall_score)}%`:''}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${released?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{r.source==='self_practice'?'Student practice':released?'Released report':'Staff review'}</span></div></summary>
       <div className="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800">{details.placement_readiness?.score!=null&&<p className="mb-3 text-sm">Placement readiness: <strong>{details.placement_readiness.score}</strong></p>}{dims.length>0&&<div className="mb-4 grid gap-2 sm:grid-cols-2">{dims.map((d:any,j:number)=><div key={j} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><span className="text-slate-500">{d.track||d.dimension||d.name||'Assessment'}</span><strong className="float-right">{d.score??d.band??'—'}</strong></div>)}</div>}{questions.length>0?<div className="space-y-3">{questions.slice(0,8).map((q:any,j:number)=><div key={j} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><p className="font-medium">{q.question||`Question ${j+1}`}</p><p className="mt-1 whitespace-pre-wrap text-slate-600 dark:text-slate-300">{q.answer||'No answer recorded.'}</p>{q.feedback&&<p className="mt-2 text-xs text-indigo-700 dark:text-indigo-300">{q.feedback}</p>}</div>)}</div>:<p className="text-sm text-slate-500">Detailed question-level evidence is not available for this report.</p>}{r.session_id&&<p className="mt-4 flex items-center gap-1 text-xs text-slate-500"><Clock3 size={14}/>Session recorded: {r.session_id}</p>}</div>
      </details>})}</div>}
     </section>
    </>}
   </div>
  </section>
 </div>
}
