import { useEffect, useState } from "react";
import { Inbox, MailPlus, Send, Sparkles, Link2, Loader2, Paperclip, RefreshCw } from "lucide-react";
import emailApi, { type EmailAccount, type EmailTemplate, type EmailThread, type EmailThreadDetail } from "@/api/emailApi";

type ThreadResponse = { threads: EmailThread[] };

function Empty({ icon: Icon, title, text }: { icon: typeof Inbox; title: string; text: string }) {
  return <div className="rounded-2xl border border-dashed border-violet-200 bg-white p-12 text-center dark:border-slate-700 dark:bg-slate-900"><Icon className="mx-auto text-indigo-600" size={30} /><h2 className="mt-4 font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p></div>;
}

export function InboxPage() {
  const [state, setState] = useState<ThreadResponse | null>(null);
  const [selected, setSelected] = useState<EmailThreadDetail | null>(null);
  const [notice, setNotice] = useState("");
  useEffect(() => { emailApi.threads().then(setState).catch(() => setState({ threads: [] })); }, []);
  if (!state) return <Empty icon={Loader2} title="Loading inbox" text="Your connected mailbox is being prepared." />;
  if (!state.threads?.length) return <Empty icon={Inbox} title="No conversations yet" text="Connect an account or sync your mailbox to see conversations." />;
  return <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><div className="rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900">{state.threads.map((x) => <button type="button" onClick={() => emailApi.thread(x.id).then(setSelected)} key={x.id} className="block w-full border-b p-4 text-left last:border-0 dark:border-slate-800"><b>{x.subject || "(No subject)"}</b><p className="text-xs text-slate-500">{x.participants?.join(", ")} · {x.unread_count} unread</p></button>)}</div>{selected ? <div className="space-y-4 rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">{selected.subject || "(No subject)"}</h2>{selected.messages.map(item => <article key={item.id} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><div className="mb-2 text-xs text-slate-500">{item.from} · {item.status}</div><div className="whitespace-pre-wrap text-sm">{item.body_text}</div></article>)}<form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); await emailApi.reply(selected.id, { body_text: form.get("body"), body_html: "", idempotency_key: crypto.randomUUID(), attachment_ids: [] }); setNotice("Reply queued."); event.currentTarget.reset(); }} className="space-y-3"><textarea name="body" required rows={5} placeholder="Reply" className="w-full rounded-xl border p-3"/><button className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Reply</button>{notice && <span className="ml-3 text-sm text-slate-500">{notice}</span>}</form></div> : <Empty icon={Inbox} title="Select a conversation" text="Choose a thread to view messages and reply." />}</div>;
}

export function SingleEmailPage() {
  const [accounts, setAccounts] = useState<EmailAccount[]>([]); const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { emailApi.accounts().then(setAccounts).catch(() => setAccounts([])); emailApi.templates().then(setTemplates).catch(() => setTemplates([])); }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!accounts[0]) return setMessage("Connect an Email account first."); const files = form.getAll("attachments").filter((value): value is File => value instanceof File && value.size > 0); const uploaded = await Promise.all(files.map(file => emailApi.uploadAttachment(file))); const selected = String(form.get("template") || ""); await emailApi.send({ account_id: accounts[0].id, to: [form.get("to")], subject: form.get("subject") || "", body_text: form.get("body") || "", body_html: "", template_version_id: selected || null, variables: JSON.parse(String(form.get("variables") || "{}")), attachment_ids: uploaded.map(x => x.id), idempotency_key: crypto.randomUUID() }); setMessage("Email queued successfully."); event.currentTarget.reset(); };
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">New Email</h2><select className="w-full rounded-xl border p-3" disabled={!accounts.length}>{accounts.map(a => <option key={a.id}>{a.email_address}</option>)}</select><select name="template" className="w-full rounded-xl border p-3"><option value="">No template</option>{templates.map(t => <option key={t.id} value={t.current_version_id}>{t.name}</option>)}</select><textarea name="variables" rows={2} defaultValue="{}" className="w-full rounded-xl border p-3 font-mono text-sm"/><input name="to" type="email" required placeholder="Recipient" className="w-full rounded-xl border p-3" /><input name="subject" placeholder="Subject (or use template)" className="w-full rounded-xl border p-3" /><textarea name="body" rows={10} placeholder="Write your message or use a template" className="w-full rounded-xl border p-3" /><label className="block rounded-xl border border-dashed p-3 text-sm"><Paperclip className="mr-2 inline" size={16}/>Attachments<input name="attachments" type="file" multiple className="ml-3" /></label><button className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white"><Send className="mr-2 inline" size={16} />Send Email</button>{message && <p className="text-sm text-slate-500">{message}</p>}</form>;
}

export function TemplatesPage() { const [items,setItems]=useState<EmailTemplate[]>([]); const [selected,setSelected]=useState<EmailTemplate|null>(null); const [preview,setPreview]=useState<Record<string,string>|null>(null); const load=()=>emailApi.templates().then(setItems); useEffect(()=>{void load()},[]); const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const p={name:f.get("name"),category:f.get("category"),subject:f.get("subject"),body_text:f.get("body_text"),body_html:f.get("body_html")}; selected?await emailApi.updateTemplate(selected.id,p):await emailApi.createTemplate(p);setSelected(null);await load()}; return <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><div className="space-y-2">{items.map(t=><button key={t.id} onClick={()=>emailApi.template(t.id).then(setSelected)} className="block w-full rounded-xl border bg-white p-4 text-left"><b>{t.name}</b><p className="text-xs text-slate-500">{t.category}</p></button>)}</div><form onSubmit={save} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">{selected?"Edit template":"New template"}</h2><input name="name" key={selected?.id+"name"} defaultValue={selected?.name} required placeholder="Template name" className="w-full rounded-xl border p-3"/><input name="category" key={selected?.id+"category"} defaultValue={selected?.category||"general"} className="w-full rounded-xl border p-3"/><input name="subject" key={selected?.id+"subject"} defaultValue={selected?.version?.subject} required placeholder="Subject with {{variables}}" className="w-full rounded-xl border p-3"/><textarea name="body_text" key={selected?.id+"text"} defaultValue={selected?.version?.body_text} rows={8} className="w-full rounded-xl border p-3"/><textarea name="body_html" key={selected?.id+"html"} defaultValue={selected?.version?.body_html} rows={8} className="w-full rounded-xl border p-3 font-mono text-sm"/><div className="flex gap-2"><button className="rounded-xl bg-indigo-600 px-4 py-2 text-white">Save version</button>{selected&&<button type="button" onClick={async()=>{await emailApi.duplicateTemplate(selected.id);await load()}} className="rounded-xl border px-4 py-2">Duplicate</button>}<button type="button" onClick={async()=>setPreview(await emailApi.previewTemplate({subject:new FormData(document.querySelector('form')!).get('subject'),body_text:"",body_html:"",variables:{}}))} className="rounded-xl border px-4 py-2">Preview</button></div>{selected?.version&&<p className="text-xs text-slate-500">Version {selected.version.version} · Variables: {selected.version.variables.join(", ")||"none"}</p>}{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}</form></div> }
export function CampaignsPage() { const [items,setItems]=useState<Array<Record<string,any>>>([]); const [templates,setTemplates]=useState<EmailTemplate[]>([]); const [notice,setNotice]=useState(""); const load=()=>emailApi.campaigns().then(x=>setItems(x.campaigns)); useEffect(()=>{void load();emailApi.templates().then(setTemplates)},[]); const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const campaign:any=await emailApi.createCampaign({name:f.get("name"),template_version_id:f.get("template"),sender_email:f.get("sender_email"),sender_name:f.get("sender_name"),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,transport:"brevo"});const recipients=String(f.get("recipients")||"").split(/[\n,]/).map(x=>x.trim()).filter(Boolean).map(email=>({email,variables:{}}));await emailApi.addCampaignRecipients(campaign.id,recipients);await emailApi.scheduleCampaign(campaign.id,new Date(String(f.get("scheduled_for"))).toISOString());setNotice("Campaign scheduled through Brevo.");await load()}; return <div className="space-y-5"><form onSubmit={create} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><h2 className="font-bold md:col-span-2">New Brevo campaign</h2><input name="name" required placeholder="Campaign name" className="rounded-xl border p-3"/><select name="template" required className="rounded-xl border p-3"><option value="">Choose template</option>{templates.map(t=><option key={t.id} value={t.current_version_id}>{t.name}</option>)}</select><input name="sender_name" required placeholder="Verified sender name" className="rounded-xl border p-3"/><input name="sender_email" type="email" required placeholder="Verified Brevo sender email" className="rounded-xl border p-3"/><textarea name="recipients" required rows={5} placeholder="Recipients, one email per line" className="rounded-xl border p-3 md:col-span-2"/><input name="scheduled_for" type="datetime-local" required className="rounded-xl border p-3"/><button className="rounded-xl bg-indigo-600 px-4 py-2 text-white"><MailPlus className="mr-2 inline" size={16}/>Schedule campaign</button>{notice&&<p className="text-sm text-slate-500 md:col-span-2">{notice}</p>}</form><div className="space-y-2">{items.map(c=><div key={c.id} className="rounded-xl border bg-white p-4"><b>{c.name}</b><p className="text-xs text-slate-500">{c.status} · {c.sender_email} · {JSON.stringify(c.analytics||{})}</p></div>)}</div></div> }
export function AutomationsPage() { return <Empty icon={Sparkles} title="No Email automations" text="Build a trigger, condition, delay and template-based action." />; }

export function EmailSettingsPage() {
  const [accounts, setAccounts] = useState<EmailAccount[] | null>(null); const load = () => emailApi.accounts().then(setAccounts).catch(() => setAccounts([])); useEffect(() => { void load(); }, []);
  const connect = async (provider: "google" | "microsoft") => { const result = await emailApi.connect(provider); window.location.assign(result.authorization_url); };
  return <div className="space-y-5"><div className="flex flex-wrap gap-3">{!accounts?.length && <button onClick={() => connect("google")} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white"><Link2 className="mr-2 inline" size={16} />Connect Gmail</button>}</div>{!accounts?.length ? <Empty icon={Link2} title="No Gmail account connected" text="Connect the pilot Gmail mailbox securely using OAuth. VoiceDots never receives your password." /> : accounts.map(a => <div key={a.id} className="flex items-center justify-between rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div><b>{a.email_address}</b><p className="text-xs capitalize text-slate-500">Gmail · {a.status}{a.last_sync_at ? ` · synced ${new Date(a.last_sync_at).toLocaleString()}` : ""}</p></div><div className="flex gap-3">{a.status === "connected" ? <><button onClick={async () => { await emailApi.sync(a.id); }} className="text-sm font-semibold text-indigo-600"><RefreshCw className="mr-1 inline" size={14}/>Sync</button><button onClick={async () => { await emailApi.disconnect(a.id); load(); }} className="text-sm font-semibold text-red-600">Disconnect</button></> : <button onClick={async () => { const result = await emailApi.reconnect(a.id); window.location.assign(result.authorization_url); }} className="text-sm font-semibold text-indigo-600">Reconnect Gmail</button>}</div></div>)}</div>;
}
